### PR TITLE
'setSelectionRange' method fixed (closes #1025)

### LINKED ISSUE #1025: Input type should be changed while setting selection range in Firefox
https://html.spec.whatwg.org/multipage/forms.html#do-not-apply
This [rule](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/selection.js#L107) should  also include Firefox browser since 51 version, cause it doesn't allow to set selectionRange originally, which leads to this [issue](https://github.com/DevExpress/testcafe/issues/1187)

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @churkin, @AlexanderMoskovkin
With this fix testcafe qunit tests passes in Firefox 51 locally and in Firefox beta on Sauce Labs. Currently i'm checking functional tests with this set.

### CODE REVIEW

File: src/client/sandbox/event/selection.js [hunk 1]
```diff
@@ -26,13 +27,23 @@ export default class Selection {
...
 
-                if (changeType)
+                if (changeType) {
                     el.type = 'text';
 
+                    if (useInternalSelection) {
+                        el[INTERNAL_PROPS.selectionProperty] = {
+                            selectionStart:     selectionStart,
+                            selectionEnd:       selectionEnd,
+                            selectionDirection: selection
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: remove this internal property setter

File: src/client/sandbox/event/selection.js [hunk 2]
```diff
@@ -117,33 +143,46 @@ export default class Selection {
...
             el.type = 'text';
         }
 
-        selection = {
-            start:     el.selectionStart,
-            end:       el.selectionEnd,
-            direction: el.selectionDirection
-        };
+        if (useInternalSelection && changeType && el[INTERNAL_PROPS.selectionProperty]) {
+            selection = {
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: no need to change el.type when this conditions are true

File: src/client/sandbox/event/selection.js [hunk 3]
```diff
@@ -117,33 +143,46 @@ export default class Selection {
...
+                start:     el[INTERNAL_PROPS.selectionProperty].selectionStart,
+                end:       el[INTERNAL_PROPS.selectionProperty].selectionEnd,
+                direction: el[INTERNAL_PROPS.selectionProperty].selectionDirection
+            };
+        }
+        else {
+            selection = {
+                start:     el.selectionStart,
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: need to return default values or real

File: src/client/sandbox/event/selection.js [hunk 4]
```diff
@@ -117,33 +143,46 @@ export default class Selection {
...
+        }
+
 
         if (changeType) {
             el.type = savedType;
 
-            if (isElementActive)
+            // NOTE: In Firefox since version 51 element lost focus if we try to get its
+            // selection properties after changing its type and browser windows isn't in focus
+            if (isElementActive || domUtils.getActiveElement(domUtils.findDocument(el)) !== el)
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: the second condition breaks behavior

File: src/client/sandbox/event/selection.js [hunk 5]
```diff
@@ -104,7 +122,15 @@ export default class Selection {
...
 
     static _needChangeInputType (el) {
-        return domUtils.isInputElement(el) && browserUtils.isWebKit && /^(number|email)$/.test(el.type);
+        return (browserUtils.isWebKit || Selection._needForInternalSelection())
+               && domUtils.isInputElement(el) && /^(number|email)$/.test(el.type);
+    }
+
+    // NOTE: input elements in Firefox since version 51 are needing
+    // for alternative selection properties, because original are
+    // clearing while input type changes to url, email etc
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: Something like: `we need to store element state because it's cleared when it's type is changed`.

File: src/client/sandbox/event/selection.js (hunk 4 above)
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: tests required

File: src/client/sandbox/event/selection.js [hunk 6]
```diff
@@ -117,27 +135,30 @@ export default class Selection {
...
             el.type = 'text';
         }
 
+        var internalSelection = el[INTERNAL_PROPS.selectionProperty];
+
         selection = {
-            start:     el.selectionStart,
-            end:       el.selectionEnd,
-            direction: el.selectionDirection
+            start:     internalSelection ? internalSelection.selectionStart : el.selectionStart,
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: if we didn't set internal selection to this element before it will return `{ null, null, null }`, but should some default values. I told you before about it

File: src/client/sandbox/event/selection.js [hunk 7]
```diff
@@ -117,27 +135,30 @@ export default class Selection {
...
+        var savedType            = el.type;
+        var selection            = null;
 
         // HACK: (A problem with input type = ‘number’ after Chrome is updated to v.33.0.1750.117 and in
         // Firefox 29.0. T101195) To get selection, if the input type is  'number' or 'email', we need to change
         // the type to text (B254340). However, the type is changed asynchronously in this case. To force type changing,
         // we need to call blur.Then call focus to make the element active.
         if (changeType) {
-            if (isElementActive)
+            if (!useInternalSelection && isElementActive)
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]:
```js
if (!useInternalSelection && isElementActive)
    this.focusBlurSandbox.blur(el, null, true);
```
but
```js
if (isElementActive)
    this.focusBlurSandbox.focus(el, null, true);

```
??

File: src/client/sandbox/event/selection.js [hunk 8]
```diff
@@ -26,8 +27,9 @@ export default class Selection {
             var isElementActive    = false;
 
             var selectionSetter = () => {
-                var changeType = Selection._needChangeInputType(el);
-                var savedType  = el.type;
+                var changeType           = Selection._needChangeInputType(el);
+                var useInternalSelection = Selection._needForInternalSelection();
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: with this code if `input.type` is `text` and it's Firefox v51, the `useInternalSelection` var is true. But I suppose we should not use internal selection in this case...

File: src/client/sandbox/event/selection.js (hunk 6 above)
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: And we need a test for this case

File: test/client/fixtures/sandbox/selection-test.js [hunk 9]
```diff
@@ -0,0 +1,26 @@
...
+
+test('Set and get selection on input with "email" type', function () {
+    var input = document.createElement('input');
+
+    input.type  = 'email';
+    input.value = inputTestValue;
+
+    document.body.appendChild(input);
+
+    input.setSelectionRange(0, inputTestValue.length, 'backward');
```
Comment (AlexanderMoskovkin) [inline test/client/fixtures/sandbox/selection-test.js]: use some custom selection in this test (not form start to end, but something like 1..3)

File: src/client/sandbox/event/selection.js (hunk 6 above)
Comment (georgiy-abbasov) [inline src/client/sandbox/event/selection.js]: >> if we didn't set internal selection to this element before it will return { null, null, null }

It returns { input.valueLength, input.valueLength, 'forward' }, cause type is changed to text, Firefox set these values as selection props.
```html
<input id="number" type="email" value="test@host.net">
<script>
    var input = document.querySelector('input');

    console.log(input.selectionStart); // null
    console.log(input.selectionEnd); // null
    console.log(input.selectionDirection); // null

    input.type = 'text';

    console.log(input.selectionStart); // 13
    console.log(input.selectionEnd); // 13
    console.log(input.selectionDirection); // forward
</script>
```

Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/selection.js]: ok

File: src/client/sandbox/event/selection.js (hunk 7 above)
Comment (georgiy-abbasov) [inline src/client/sandbox/event/selection.js]: I have faced with situation while ran qunit tests in testcafe - firefox doesn't focus on the element again while executes (after blur is executed)
```js
if (isElementActive)
    this.focusBlurSandbox.focus(el, null, true);
```

**Comment by georgiy-abbasov** [comment]
TestCafe functional test is blinking, but it's not related to this commit, so FPR

**Comment by AlexanderMoskovkin** [comment]
@churkin Please review it again, it was reworked

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/sandbox/selection-test.js [hunk 10]
```diff
@@ -0,0 +1,51 @@
...
+        start:     2,
+        end:       9,
+        direction: 'backward'
+    };
+
+    input.setSelectionRange(testSelection.start, testSelection.end, testSelection.direction);
+
+    var selection = selectionSandbox.getSelection(input);
+
+    equal(selection.start, testSelection.start);
```
Comment (churkin) [inline test/client/fixtures/sandbox/selection-test.js]: We are using `strictEqual` anywhere

File: test/client/fixtures/sandbox/selection-test.js [hunk 11]
```diff
@@ -0,0 +1,51 @@
+var selectionSandbox = hammerhead.eventSandbox.selection;
+var browserUtils     = hammerhead.utils.browser;
+
+var inputTestValue  = 'test@host.net';
+var isIE            = browserUtils.isIE;
+var isMobileBrowser = browserUtils.isIOS || browserUtils.isAndroid;
+
+var createTestInput = function () {
+    var input = $('<input type="email">').appendTo(document.body)[0];
```
Comment (churkin) [inline test/client/fixtures/sandbox/selection-test.js]: We try to not use `jquery` in our `qunit` tests

Comment (georgiy-abbasov) [inline test/client/fixtures/sandbox/selection-test.js]: It's impossible to change input type in IE9, after object is created.

Comment (churkin) [inline test/client/fixtures/sandbox/selection-test.js]: You can use `.innertHTML = "<input type="email">"` for example

Comment (AlexanderMoskovkin) [inline test/client/fixtures/sandbox/selection-test.js]: what? jquery is just a wrapper around native js. what's the problem to do the same as jquery?

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest
