### PR TITLE
fix `A page hangs during a loop on collection with 5k elements before DOMContentLoaded event` (close #2198)

### LINKED ISSUE #2198: A page hangs during a loop on collection with 5k elements before DOMContentLoaded event
We need to improve HTMLCollectionWrapper;

SC: T837528

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

File: src/client/sandbox/node/window.ts [hunk 1]
```diff
@@ -551,7 +553,8 @@ export default class WindowSandbox extends SandboxBase {
 
                         return storedGet.call(this, getterTarget, name, receiver);
                     };
-                    handler.__overwritten__ = true;
+
+                    handler.get[PROXY_HANDLER_FLAG] = true;
```
Comment (miherlosev) [inline src/client/sandbox/node/window.ts]: Hide the internal flag from enumeration.
```js
nativeMethods.objectDefineProperty.call(handler.get, PROXY_HANDLER_FLAG, { value: true, writable: true });
```

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest
