### PR TITLE
The getProxyUrl client function works incorrectly (fix #471)

### LINKED ISSUE #471: The getProxyUrl client function works incorrectly
```javascript
test('', function () {
    var destUrl  = 'https://example.com/path/path/sdfjhsdkjf/http://example.com/image.png';
    var proxyUrl = urlUtils.getProxyUrl(destUrl, '127.0.0.1', '1337', 'sessionId');
    // proxyUrl = http://127.0.0.1:1337/sessionId/http://example.com/image.png

    strictEqual(proxyUrl, 'http://127.0.0.1:1337/sessionId/' + destUrl);
});
```

### PR DESCRIPTION
**Pull request by LavrovArtem**
\cc @churkin @AlexanderMoskovkin 
@VasilyStrelyaev please check test name

### CODE REVIEW

File: src/client/utils/url.js [hunk 1]
```diff
@@ -13,11 +19,17 @@ export function getProxyUrl (url, proxyHostname, proxyPort, sessionId, resourceT
...
+    proxyHostname = proxyHostname || location.hostname;
+    proxyPort     = proxyPort || location.port.toString();
+    sessionId     = sessionId || settings.get().sessionId;
+
     // NOTE: If the relative URL contains no slash (e.g. 'img123'), the resolver will keep
     // the original proxy information, so that we can return such URL as is.
     // TODO: Implement the isProxyURL function.
     var parsedAsProxy   = sharedUrlUtils.parseProxyUrl(url);
-    var isValidProxyUrl = !!parsedAsProxy;
+    var isValidProxyUrl = !!parsedAsProxy && parsedAsProxy.proxy.hostname === proxyHostname &&
```
Comment (AlexanderMoskovkin) [inline src/client/utils/url.js]: It looks strange for me that `parsedAsProxy` has some fields because. I expect a boolean value from this variable.
Maybe we should rename it to `parsedProxyUrl` or something else? /cc @LavrovArtem @churkin

File: test/client/fixtures/utils/url-test.js [hunk 2]
```diff
@@ -295,6 +295,13 @@ test('location.port must return the empty string (T262593)', function () {
     /* eslint-enable no-undef */
 });
 
+test('get proxy url from destination with url into path (GH-471)', function () {
```
Comment (VasilyStrelyaev) [inline test/client/fixtures/utils/url-test.js]:
```
test('A correct proxy URL should be obtained from a destination that has a URL in its path (GH-471)', function () {
```

Comment (VasilyStrelyaev) [inline test/client/fixtures/utils/url-test.js]: not too long, eh?

Comment (LavrovArtem) [inline test/client/fixtures/utils/url-test.js]: no, thanks)

File: src/client/utils/url.js (hunk 1 above)
Comment (LavrovArtem) [inline src/client/utils/url.js]: I agree we should rename this variable to parsedProxyUrl @churkin

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by churkin** [comment]
@LavrovArtem fpr?

**Comment by LavrovArtem** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
FPR

**Comment by churkin** [comment]
lgtm
