### PR TITLE
fix `[todomvc2] - wrong client render (http://todomvc.com/examples/jsblocks)` (close #953)

### LINKED ISSUE #953: [todomvc2] - wrong client render (http://todomvc.com/examples/jsblocks)
http://screencast.com/t/wKIQDIUjpt2

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev @MarinaRukavitsyna

### CODE REVIEW

File: src/client/utils/feature-detection.js [hunk 1]
```diff
@@ -2,5 +2,10 @@ import nativeMethods from '../sandbox/native-methods';
 
 // NOTE: In some browsers, elements without the url attribute return the location url
 // when accessing this attribute directly. See form.action in Edge 25 as an example.
-export var emptyActionAttrFallbacksToTheLocation = nativeMethods.createElement.call(document, 'form').action ===
-                                                   window.location.toString();
+export const emptyActionAttrFallbacksToTheLocation = nativeMethods.createElement.call(document, 'form').action ===
+                                                     window.location.toString();
+
+// NOTE: In Chrome, toString(new Blob([])) equals '[object Blob]' and toString(Blob.prototype) equals '[object Blob]',
```
Comment (MarinaRukavitsyna) [inline src/client/utils/feature-detection.js]: // NOTE: In Chrome, toString(new Blob([])) equals '[object Blob]' and toString(Blob.prototype) equals '[object Blob]';
// this condition is also satisfied for Window, Document, XMLHttpRequest, etc

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: src/client/utils/dom.js [hunk 2]
```diff
@@ -8,15 +8,19 @@ import { sameOriginCheck } from './destination-location';
...
-var arraySlice = Array.prototype.slice;
+const arraySlice = Array.prototype.slice;
 
 var scrollbarSize = null;
 
+const IS_NOT_DOM_ELEMENT_RE = /^\[object (Element|Node|EventTarget)(Prototype)?]$/;
+const IS_WINDOW_RE          = /^\[object (Window|global)]$/;
+const IS_DOCUMENT_RE        = /^\[object (HTML)?Document]$/;
+const IS_SVG_ELEMENT_RE     = /^\[object SVG\w+?Element]$/i;
+
```
Comment (miherlosev) [inline src/client/utils/dom.js]: `indexOf` is faster then regex. https://jsperf.com/regex-versus-indexofwithtwoelements2
use  `['[object Window]', '[object global]']`.indexOf` instead of `IS_WINDOW_RE`.

File: src/client/utils/dom.js [hunk 3]
```diff
@@ -580,8 +575,7 @@ export function isSVGElement (instance) {
     if (instance instanceof nativeMethods.svgElementClass)
         return true;
 
-    return instance && typeof instance === 'object' && instance.ownerSVGElement !== void 0 &&
-           nativeToString(instance).toLowerCase() === '[object svg' + getTagName(instance) + 'element]';
+    return instance && IS_SVG_ELEMENT_RE.test(instanceToString(instance));
```
Comment (miherlosev) [inline src/client/utils/dom.js]: `IS_SVG_ELEMENT_RE` is slower than simple string comparison

Comment (miherlosev) [inline src/client/utils/dom.js]: Ok. I was wrong

**Comment by miherlosev** [comment]
This pull request also will fix #https://github.com/DevExpress/testcafe-hammerhead/issues/959

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/utils/dom-test.js [hunk 4]
```diff
@@ -131,10 +131,39 @@ test('isWindow', function () {
...
+
+    window.QUnitGlobals.waitForIframe(iframe)
+        .then(function () {
+            var iframeWindow = iframe.contentWindow;
+
+            ok(domUtils.isWindow(iframeWindow));
+
+            // NOTE: The firefox does not provide access to the cross-domain location.
+            if (!browserUtils.isFirefox)
+                ok(!domUtils.isWindow(iframeWindow.location));
```
Comment (miherlosev) [inline test/client/fixtures/utils/dom-test.js]: I think we should move `!browserUtils.isFirefox condition before test and remove `ok(!domUtils.isWindow(iframeWindow.location));`.
Because you test checks `window`.

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/utils/dom-test.js (hunk 4 above)
Comment (miherlosev) [inline test/client/fixtures/utils/dom-test.js]: Ok. I understand test logic.

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR
