### PR TITLE
fix `File upload doesn't work with inputs with a required attribute` (close #1645)

### LINKED ISSUE #1645: File upload doesn't work with inputs with a required attribute
see https://github.com/DevExpress/testcafe/issues/2509

We need to remove the `required` attribute from an input element which has emulation of the file uploading.

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/1645

### Changes
1. Override `HTMLInputElement.required` attribute.
2. Override  `HTMLInputElement.type` attribute.
3. Fix default credential fetch tests: 'headers is object', 'headers is window.Headers' (test/client/fixtures/sandbox/fetch-test.js)

### `required` attribute `input` types
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input:
**'file'**, 'text', 'search', 'url', 'tel', 'email', 'password', 'date', 'datetime-local', 'month', 'week', 'time', 'number', 'checkbox', 'radio'

### Notes
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_%3Cinput%3E_types:
> How an `<input>` works varies considerably depending on the value of its type attribute, hence the different types are covered in their own separate reference pages. **If this attributes is not specified, the default type adopted is `text`**.

### CODE REVIEW

File: test/client/fixtures/sandbox/node/attributes-test.js [hunk 1]
```diff
@@ -751,6 +759,183 @@ test('"rel" property', function () {
 });
 
 
+module('"required" attribute (HTMLInputElement)');
+
+test('process html', function () {
+    var storedRequiredAttr = DomProcessor.getStoredAttrName('required');
+    var requiredAttrCases  = [
+        { requiredValue: '', hasRequiredAttr: false, hasStoredRequiredAttr: true },
```
[the remark this answers is not in the document]
Comment (LavrovArtem) [reply test/client/fixtures/sandbox/node/attributes-test.js]:
```js
testCases = [
    { typeValue: 'file', requiredValue: 'required'},
    { typeValue: 'file', requiredValue: ''},
    { typeValue: 'radio', requiredValue: 'required'},
    { typeValue: null, requiredValue: ''}
]
```

File: test/client/fixtures/sandbox/node/attributes-test.js [hunk 2]
```diff
@@ -751,6 +759,183 @@ test('"rel" property', function () {
...
+            strictEqual(nativeMethods.getAttribute.call(input, 'required'),
+                inputTypeCase === 'file' ? null : requiredAttrCase.requiredValue);
+            strictEqual(nativeMethods.getAttribute.call(input, storedRequiredAttr),
+                inputTypeCase === 'file' ? requiredAttrCase.requiredValue : null);
+        });
+    });
+});
+
+test('setAttribute', function () {
+    var input = nativeMethods.createElement.call(document, 'input');
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/attributes-test.js]: `nativeMethods` is unnecessary

File: src/client/sandbox/node/element.js [hunk 3]
```diff
@@ -338,12 +371,26 @@ export default class ElementSandbox extends SandboxBase {
...
+
+            removeAttrFunc.call(el, storedRequiredAttr);
+        }
+        else if (!isNs && formatedAttr === 'type' && domUtils.isInputElement(el)) {
+            const storedRequiredAttr = DomProcessor.getStoredAttrName('required');
+
+            if (nativeMethods.hasAttribute.call(el, storedRequiredAttr)) {
+                const currentRequired = nativeMethods.getAttribute.call(el, storedRequiredAttr);
+
+                nativeMethods.setAttribute.apply(el, ['required', currentRequired]);
```
Comment (LavrovArtem) [inline src/client/sandbox/node/element.js]: use `call`

File: test/client/fixtures/sandbox/node/attributes-test.js [hunk 4]
```diff
@@ -11,6 +11,14 @@ var nativeMethods = hammerhead.nativeMethods;
 var browserUtils  = hammerhead.utils.browser;
 var unloadSandbox = hammerhead.sandbox.event.unload;
 
+var requireAttrInputTypeCases = [
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/attributes-test.js]: It is unnecessary

**Comment by Farfurix** [comment]
@testcafe-build-bot retest
