### PR TITLE
fix 'Wrong version number for Chrome' (close #777).

### LINKED ISSUE #777: Wrong version number for Chrome
For 52 and 53 Chrome it returns `537`

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem @helen-dikareva 
see https://github.com/DevExpress/testcafe-hammerhead/issues/777#issuecomment-246616642

### CODE REVIEW

File: src/client/utils/browser.js [hunk 1]
```diff
@@ -32,16 +26,46 @@ export var isIE11 = /trident\/7.0/.test(userAgent) && !(browser.name === 'msie'
...
+    if (isMSEdge)
+        browserVersion = getMSEdgeVersion();
+    else if (isChrome)
+        browserVersion = getChromeVersion();
+
+    return browserVersion;
+}
+
+function getEngineVersion () {
+    return isWebKit ? browser.version : 0;
```
Comment (helen-dikareva) [inline src/client/utils/browser.js]: I think we should return engine version not only for WebKit

File: src/client/utils/browser.js [hunk 2]
```diff
@@ -1,9 +1,3 @@
-function getMSEdgeVersion (userAgent) {
-    var edgeStrIndex = userAgent.indexOf('edge/');
-
-    return parseInt(userAgent.substring(edgeStrIndex + 5, userAgent.indexOf('.', edgeStrIndex)), 10);
-}
-
 function calculateBrowserAndVersion (userAgent) {
     var webkitRegEx  = /(webkit)[ \/]([\w.]+)/;
```
Comment (helen-dikareva) [inline src/client/utils/browser.js]: Sometimes it returns version of browser and sometimes version of engine. I don't really like it

File: src/client/utils/browser.js [hunk 3]
```diff
@@ -32,16 +26,46 @@ export var isIE11 = /trident\/7.0/.test(userAgent) && !(browser.name === 'msie'
...
 export var isMSEdge          = !!/edge\//.test(userAgent);
-export var version           = isMSEdge ? getMSEdgeVersion(userAgent) : majorBrowserVersion;
+export var isChrome          = /chrome/.test(userAgent);
+export var isWebKit          = browser.name === 'webkit' && !isMSEdge;
+
+function getBrowserVersion () {
+    var browserVersion = majorBrowserVersion;
+
+    if (isMSEdge)
+        browserVersion = getMSEdgeVersion();
```
Comment (helen-dikareva) [inline src/client/utils/browser.js]: better use `return`

File: src/client/utils/browser.js [hunk 4]
```diff
@@ -32,16 +26,46 @@ export var isIE11 = /trident\/7.0/.test(userAgent) && !(browser.name === 'msie'
 if (isIE11)
     majorBrowserVersion = 11;
```
Comment (helen-dikareva) [inline src/client/utils/browser.js]: why we need to store `majorBrowserVersion` and recalculate `browser` and `engine` version. We can do it one time (like `majorBrowserVersion`). `majorBrowserVersion` now isn't good name (see https://github.com/DevExpress/testcafe-hammerhead/pull/781/files#r78536076).

Comment (helen-dikareva) [inline src/client/utils/browser.js]: I think better use ternary in this case, something like this:
`var majorBrowserVersion = isIE11 ? parseInt(browser.version, 10) : 11;`
just swap strings

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
Don't perform retest command. Feature in progress.

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
ping @LavrovArtem @helen-dikareva

File: src/client/utils/browser.js [hunk 5]
```diff
@@ -1,48 +1,50 @@
...
+                        ie9And10RegEx.exec(userAgent) ||
+                        userAgent.indexOf('trident') >= 0 && ie11RegEx.exec(userAgent) ||
+                        userAgent.indexOf('compatible') < 0 && firefoxRegEx.exec(userAgent) ||
+                        [];
 
     return {
-        name:    match[1] || '',
-        version: match[2] || '0'
+        name:    match[5] || match[3] || match[1] || '',
+        version: parseInt(match[4] || match[2] || '0', 10)
```
Comment (helen-dikareva) [inline src/client/utils/browser.js]: I think it'll too complicated to change this part of code in the future because it strongly depends on order of matches

Comment (miherlosev) [inline src/client/utils/browser.js]: How do you suggest to change this?

Comment (helen-dikareva) [inline src/client/utils/browser.js]: If it's possible better use clearly way to calculate name and version, e.g. at first get name and after get version. In this way chages for one RegExp for UA (the order of matches may be changed) will not affect for others.

File: src/client/utils/browser.js [hunk 6]
```diff
@@ -1,48 +1,50 @@
...
 function calculateBrowserAndVersion (userAgent) {
-    var webkitRegEx  = /(webkit)[ \/]([\w.]+)/;
-    var msieRegEx    = /(msie) ([\w.]+)/;
-    var firefoxRegEx = /(firefox)/;
-
-    var match = webkitRegEx.exec(userAgent) ||
-                msieRegEx.exec(userAgent) ||
-                userAgent.indexOf('compatible') < 0 && firefoxRegEx.exec(userAgent) ||
-                [];
+    var msEdgeRegEx   = /(edge)\/([\w.]+)/;
```
Comment (miherlosev) [inline src/client/utils/browser.js]: We use another naming convention for inplace regexps:
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/simulator.js#L303
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/dom.js#L29

Comment (miherlosev) [inline src/client/utils/browser.js]: Ok. I lost `p` character. 
It will added.

File: src/client/utils/browser.js (hunk 5 above)
Comment (miherlosev) [inline src/client/utils/browser.js]: If it is well-known browser then name and version will calcualte at once.
It it is browser based on popular engine (e.g. Yander browser) we will try calculate name and version, then engine name and version etc.

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
ping @churkin

**Comment by miherlosev** [comment]
The version was bumped before sprint release.

**Comment by miherlosev** [comment]
FPR
