### PR TITLE
fix `fetch API rasies TypeError when argument is URL object` (close #1613)

### LINKED ISSUE #1613: fetch API rasies TypeError when argument is URL object
"testcafe": "0.19.2"

https://developer.mozilla.org/en-US/docs/Web/API/URL contains an example there URL object is using in fetch API argruments:
``` 
const response = await fetch(new URL('http://www.example.com/démonstration.html'));
```
The same works fine on a page, but it throws 'Error: TypeError' exception when the page is testing in testcafe.

As temporary workaround I added .toString() method to our code:
``` 
const response = await fetch(new URL('http://www.example.com/démonstration.html').toString());
```

### PR DESCRIPTION
**Pull request by Farfurix**
`fetch` supports the following browsers: Chrome, Firefox, Edge, Safari.

### References
https://github.com/DevExpress/testcafe-hammerhead/issues/1613
https://github.com/DevExpress/testcafe-hammerhead/issues/939

### Changes
1. Change arguments processing logic in `fetch()` src/client/sandbox/fetch.js:
If the input argument(args[0]) is not a `string` and is not a `Request` object,
we are trying to convert the input argument to `string` primitive value using `String()`.
This approach helps us simulate the browsers behavior by throwing the 'TypeError' exception
if the input object can not be converted to a primitive value.
2. Fix "request promise should be rejected on invalid calling (GH-939)" test.
3. Fix `XMLHttpRequest`: convert url argument to string before `getProxyUrl`. Fix test/client/before-test.js `checkNativeFunctionCalling`.
4. Fix  `locationWrapper` (`href` setter, `assgin`, `replace`): convert url argument to string.
5. Fix  `location` property case. Add routes in test/client/config-qunit-server-app.js for iframe loading in IE 11 (`location` property test)
6. Fix "xhr.response.url" test: exclude Internet Explorer 11 with 0 assertions.
7. Remove checkNativeFunctionArgs('open', 'xhrOpen', xhr) test case from windows-test.js because of the url argument string conversion.

### Fix "request promise should be rejected on invalid calling (GH-939)" test
Browsers process all of these arguments in `fetch` without `Promise` rejection:
```javascript
var testCases = [
    123,
    function () {
    },
    null
];
```
**Simple example:**
```javascript
var testFetch = function (firstArg) {
    fetch(firstArg)
        .then(function (res) {
            console.log(res.url);
        })
        .catch(function (err) {
            console.log(err);
        });
}
```
```
> testFetch(123) 
http://127.0.0.1:8080/123

> testFetch(null) 
http://127.0.0.1:8080/null

> testFetch(function () {} ) 
http://127.0.0.1:8080/function%20()%20%7B%20%20%20%20%7D
```
### Safari processed `fetch()` without `Promise` rejection
```
> fetch()
http://127.0.0.1:8080/undefined
```

### Browsers process inaccessible `null` and `undefined` arguments without `Promise` rejection
```
> testFetch(null) 
http://127.0.0.1:8080/null

> testFetch(undefined) 
http://127.0.0.1:8080/undefined
```
### `Object` in the `fetch` first argument
`URL`:
```
> testFetch(new URL('http://127.0.0.1:8080/index2.html')) 
http://127.0.0.1:8080/index2.html
```
`Object` without `toString` method:
```javascript
var firstArg = {
    url: 'http://127.0.0.1:8080/index2.html'
};
```
```
> testFetch(firstArg)
http://127.0.0.1:8080/[object%20Object]
```

`Object` with`toString` method:
```javascript
var firstArg = {
    url:      'http://127.0.0.1:8080/index2.html',
    toString: function () {
        return this.url;
    }
};
```
```
> testFetch(firstArg)
http://127.0.0.1:8080/index2.html
```

### CODE REVIEW

File: src/client/sandbox/fetch.js [hunk 1]
```diff
@@ -53,7 +55,24 @@ export default class FetchSandbox extends SandboxBase {
     }
 
     static _isValidRequestArgs (args) {
-        return typeof args[0] === 'string' || isFetchRequest(args[0]);
+        if (typeof args[0] === 'string' || isFetchRequest(args[0]))
```
Comment (miherlosev) [inline src/client/sandbox/fetch.js]: Bad design. `_isValidRequestArgs` should not modify the arguments.
So `isValidRequestArgs` should be rewritten as
```js
return typeof args[0] === 'string' || isFetchRequest(args[0]) || objectWithToStringMethod;
```

Move argument processing logic for `null`, `undefined` and custom object with `toString` method to  `FetchSandbox._processArguments(args)`.

File: test/client/fixtures/sandbox/fetch-test.js [hunk 2]
```diff
@@ -62,6 +62,50 @@ if (window.fetch) {
...
+                expectedUrl: 'https://example.com/some-path'
+            },
+            {
+                firstArg: {
+                    url:      '/some-path',
+                    toString: function () {
+                        return this.url;
+                    }
+                },
+                expectedUrl: 'https://example.com/some-path'
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/fetch-test.js]: Add test for object without `toString` method

File: test/client/fixtures/sandbox/fetch-test.js [hunk 3]
```diff
@@ -416,29 +416,31 @@ if (window.fetch) {
...
                     })
-                ]);
-            });
-        }
+                    .catch(function () {
+                        ok(true);
+                    });
+            };
+
+            var promises = [];
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/fetch-test.js]:
```js
var cases = [
    checkArg({
        toString: function () {
            return {};
        }
    })
];
```

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/code-instrumentation/location/wrapper.js [hunk 4]
```diff
@@ -61,6 +61,10 @@ export default class LocationWrapper extends EventEmitter {
             return ensureTrailingSlash(href, locationUrl);
         };
         const getProxiedHref = href => {
+            // NOTE: we must convert url-object to 'string' (GH-1613)
```
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/location/wrapper.js]: remove this comment

File: src/client/sandbox/fetch.js [hunk 5]
```diff
@@ -43,23 +44,17 @@ export default class FetchSandbox extends SandboxBase {
         const inputIsFetchRequest = isFetchRequest(input);
         let init                  = args[1];
 
-        if (inputIsString) {
-            args[0] = getProxyUrl(input);
+        if (!inputIsFetchRequest) {
+            // NOTE: we must convert url-object to 'string' (GH-1613)
```
Comment (miherlosev) [inline src/client/sandbox/fetch.js]: remove this comment

File: src/client/sandbox/xhr.js [hunk 6]
```diff
@@ -111,8 +111,11 @@ export default class XhrSandbox extends SandboxBase {
         // NOTE: Redirect all requests to the Hammerhead proxy and ensure that requests don't
         // violate Same Origin Policy.
         xmlHttpRequestProto.open = function () {
-            if (typeof arguments[1] === 'string')
-                arguments[1] = getProxyUrl(arguments[1]);
+            const url         = arguments[1];
+            const urlIsString = typeof input === 'string';
+
+            // NOTE: we must convert url-object to 'string' (GH-1613)
```
Comment (miherlosev) [inline src/client/sandbox/xhr.js]: remove this comment

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/fetch.js [hunk 7]
```diff
@@ -109,13 +103,23 @@ export default class FetchSandbox extends SandboxBase {
...
 
         window.fetch = function (...args) {
-            if (!args.length)
+            // NOTE: Safari processed the empty `fetch()` request without `Promise` rejection (GH-1613)
+            if (!args.length && !browserUtils.isSafari)
                 return nativeMethods.fetch.apply(this);
 
-            if (!FetchSandbox._requestIsValid(args))
-                return sandbox.window.Promise.reject(new TypeError());
+            // NOTE: If the input argument(args[0]) is not a `string` and is not a `Request` object,
```
Comment (miherlosev) [inline src/client/sandbox/fetch.js]: Remove this comment

File: src/client/sandbox/fetch.js [hunk 8]
```diff
@@ -109,13 +103,23 @@ export default class FetchSandbox extends SandboxBase {
...
+            // if the input object can not be converted to a primitive value. (GH-1613)
+            try {
+                FetchSandbox._processArguments(args);
+            }
+            catch (e) {
+                return sandbox.window.Promise.reject(e);
+            }
 
-            FetchSandbox._processArguments(args);
+            if (!FetchSandbox._sameOriginCheck(args))
```
Comment (miherlosev) [inline src/client/sandbox/fetch.js]: Move `FetchSandbox._sameOriginCheck` to the `FetchSandbox._processArguments`

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 9]
```diff
@@ -192,6 +192,204 @@ test('special pages (GH-339)', function () {
     destLocation.forceLocation(storedForcedLocation);
 });
 
+test('should process some url types in locationWrapper (href, replace, assign) (GH-1613)', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: `test('different url types for locationWrapper methods (href, replace, assign) (GH-1613)'`

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 10]
```diff
@@ -192,6 +192,204 @@ test('special pages (GH-339)', function () {
...
+
+        locationWrapper.replace(testCase.url);
+        strictEqual(windowMock.location.href, urlUtils.getProxyUrl(testCase.expectedUrl));
+
+        locationWrapper.assign(testCase.url);
+        strictEqual(windowMock.location.href, urlUtils.getProxyUrl(testCase.expectedUrl));
+    });
+});
+
+test('should throwing an error on invalid url-object in locationWrapper (href, replace, assign) (GH-1613)', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: `test('throwing errors on calling locationWrapper methods (href, replace, assign) with invalid arguments`

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 11]
```diff
@@ -192,6 +192,204 @@ test('special pages (GH-339)', function () {
...
+            locationWrapper.assign(invalidUrlObject);
+            strictEqual(windowMock.location.href, urlUtils.getProxyUrl(''));
+        }
+        catch (e) {
+            ok(true, 'assign');
+        }
+    }
+});
+
+test('should process some url types in the "location" property (GH-1613)', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: `test('different url types for "location" property  (GH-1613)')`

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 12]
```diff
@@ -192,6 +192,204 @@ test('special pages (GH-339)', function () {
...
+    var checkLocation = function (iframe) {
+        return new Promise(function (resolve) {
+            iframe.addEventListener('load', function () {
+                resolve(iframe.contentWindow.location.toString());
+            });
+        });
+    };
+
+    var checkIframesLocation = function (nativeIframeUrl, processedIframeUrl) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: `var checkLocationAssignment = ...`

File: test/client/fixtures/sandbox/fetch-test.js [hunk 13]
```diff
@@ -62,6 +62,52 @@ if (window.fetch) {
             });
     });
 
+    test('should process some argument types (GH-1613)', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/fetch-test.js]: `different url types for 'fetch' (GH-1613)`

File: test/client/fixtures/sandbox/xhr-test.js [hunk 14]
```diff
@@ -76,6 +78,66 @@ test('toString, instanceof, constructor and static properties', function () {
     strictEqual(XMLHttpRequest.DONE, nativeMethods.XMLHttpRequest.DONE);
 });
 
+test('overridden "open" function should process some url argument types before the native "XMLHttpRequest.open" method calling (GH-1613)', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/xhr-test.js]: `test('different url types for xhr.open method (GH-1613)')`

File: test/client/fixtures/sandbox/xhr-test.js [hunk 15]
```diff
@@ -76,6 +78,66 @@ test('toString, instanceof, constructor and static properties', function () {
...
+    xhr.open('GET', {
+        toString: function () {
+            return '/some-path';
+        }
+    });
+
+    nativeMethods.xhrOpen = storedNativeXhrOpen;
+});
+
+test('should throwing an error on invalid calling "open" (GH-1613)', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/xhr-test.js]: test('should throwing an error on invalid calling "open" method (GH-1613)'

File: test/client/fixtures/sandbox/xhr-test.js [hunk 16]
```diff
@@ -127,24 +189,27 @@ test('the internal 222 status code should be replaced with 0 on the client side'
...
-            strictEqual(this.responseURL, 'https://example.com/xhr-large-response');
-            ++testCount;
-        }
-
-        if (this.readyState === XMLHttpRequest.DONE) {
-            expect(testCount);
-            start();
-        }
+// NOTE: IE11 doesn't support 'XMLHttpRequest.responseURL'
+if (browserUtils.isIE11) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/xhr-test.js]: Why does this condition need?
