### PR TITLE
Fix task script injection for the TestCafe (close #364)

### LINKED ISSUE #364: Syntax error in task.js
Open in Playground http://google.com
In Console you can see the error:
```javascript
task.js:9 Uncaught SyntaxError: Unexpected token ILLEGAL
```
Also see Health Monitor run - https://testcafe-hhhm.devexpress.com/history?timestamp=1453230178869.
Passed - 0, failed - 159.

It causes because `iframeWithoutSrcTaskTemplate` rendered wrongly.

### PR DESCRIPTION
**Pull request by churkin**
\cc @LavrovArtem @miherlosev

### CODE REVIEW

File: src/client/sandbox/iframe.js [hunk 1]
```diff
@@ -40,10 +41,14 @@ export default class IframeSandbox extends SandboxBase {
...
+                this.emit(this.EVAL_HAMMERHEAD_SCRIPT, { iframe });
 
-                // NOTE: Raise this event to eval the "task" script and to call the Hammerhead initialization method.
-                this.emit(this.IFRAME_READY_TO_INIT_EVENT, { iframe });
+                // NOTE: Raise this event to eval external code script.
+                this.emit(this.EVAL_EXTERNAL_SCRIPT, { iframe });
+
+                // NOTE: Raise this event to eval the "task" script and to call the Hammerhead initialization method
+                // and external script initialization code.
+                this.emit(this.RUN_TASK_SCRIPT, { iframe });
```
Comment (miherlosev) [inline src/client/sandbox/iframe.js]: rename to `EVAL_TASK_SCRIP`

**Comment by miherlosev** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm
