### PR TITLE
Fix string representation of native func wrappers

### LINKED ISSUE #2394: Uncaught TypeError: Illegal invocation
The page is not loaded, there is the following error in DevTools console:
```
Uncaught TypeError: Illegal invocation
    at Window.addEventListener (hammerhead.js:7)
    at <anonymous>:2355:89162
    at Object.<anonymous> (<anonymous>:2355:89829)
    at Object.jQuery (<anonymous>:2355:89881)
    at n (<anonymous>:15:228)
    at Object.<anonymous> (<anonymous>:2355:87883)
    at Object.jQuery (<anonymous>:2355:88125)
    at n (<anonymous>:15:228)
    at Object.jQuery (<anonymous>:2355:87042)
    at n (<anonymous>:15:228)
```

Please see the [T915177](https://supportcenter.devexpress.com/internal/ticket/details/T915177) private ticket for details.

testcafe-hammerhead version: 17.1.11

### PR DESCRIPTION
**Pull request by wentwrong**
## Purpose 
        
Customer who submitted the [original](https://supportcenter.devexpress.com/internal/ticket/details/T915177/) ticket to our Support Center is using `Power BI` library, which causes an issue when the customer tries to run tests on their site. First, the library creates a fake copy of `window` object ([issue](https://github.com/microsoft/PowerBI-visuals/issues/165)). Then it detects native functions by running a regexp search with pattern `/\{\s*\[native code\]\s*\}/` against the result of `Function.prototype.toString()` call. When a native function is found, the library binds it to a newly created `window` instance. But in our case, Power BI library can't detect any native functions because we're wrapping them, so their string representations are just the code of these wrappers. To resolve this, we need to override string representations of our native functions' wrappers so that `Function.prototype.toString()` method returns the expected value.

## Approach

The approach we decided on is to save the original string representation of a native function right in its wrapper as an additional property. Then override `Function.prototype.toString()` method so it returns this data if the function passed to it has our property, otherwise dispatch to default native method call.

It should be noted that instead of saving the initial string representation as a property, we could save a reference to the original native function in its wrapper and dispatch to that when needed (which is the same way `zone.js` library does it).

## References
Closes #2394 
Fixed missed typo that was introduced in #2203: should be `EventTarget` instead of `EventLisener`

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

### CODE REVIEW

**Comment by wentwrong** [comment]
Also, I think that the process of creating new wrappers for native functions should be streamlined somehow. Because otherwise everytime someone adds a new wrapper they'll have to manually override its string representation by calling
```js
overrideStringRepresentation(ourWrapper, nativeFunction);
```
Which they can easily forget to do.

As a suggestion, we can refactor our wrappers to make them child classes inherited from the same base class, which will contain the code responsible for correcting string representations. That would also let us reduce the size of a gigantic `attach` method of the `WindowSandbox` class.

**Comment by wentwrong** [comment]
@testcafe-build-bot retest

**Comment by adriancable** [comment]
This looks great - does it also address #2423 ?

**Comment by AndreyBelym** [comment]
This PR fixes only a part of #2423. We will need a lot more work to fix all the cases described there.

File: src/client/utils/property-overriding.ts [hunk 1]
```diff
@@ -54,3 +55,56 @@ export function overrideDescriptor<O extends object, K extends keyof O> (obj: O,
...
+        });
+    }
+}
+
+export function overrideConstructor<O extends object, K extends keyof O> (obj: O, fnName: K, wrapper: Function, overrideProtoConstructor: boolean = false): void {
+    const nativePrototype = obj[fnName]['prototype'];
+    
+    overrideFunction(obj, fnName, wrapper);
+
+    if (nativePrototype) {
```
Comment (LavrovArtem) [inline src/client/utils/property-overriding.ts:96]: I don't understand why we need this condition. Each function has the `prototype` property and that `prototype` has `constructor`.

File: src/client/utils/property-overriding.ts [hunk 2]
```diff
@@ -54,3 +55,56 @@ export function overrideDescriptor<O extends object, K extends keyof O> (obj: O,
...
+        // NOTE: restore native prototype (to make `instanceof` work as expected)
+        nativeMethods.objectDefineProperty(obj[fnName], 'prototype', {
```
Comment (LavrovArtem) [inline src/client/utils/property-overriding.ts:98]: We don't need to use `objectDefineProperty` there.

File: src/processing/dom/internal-properties.ts [hunk 3]
```diff
@@ -15,5 +15,7 @@ export default {
     forceProxySrcForImage:     'hammerhead|image|force-proxy-src-flag',
     skipNextLoadEventForImage: 'hammerhead|image|skip-next-load-event-flag',
     cachedImage:               'hammerhead|image|cached-image',
-    sandboxIsReattached:       'hammerhead|sandbox-is-reattached'
+    sandboxIsReattached:       'hammerhead|sandbox-is-reattached',
+    
+    nativeStringRepresentation: 'hammerhead|nativeStringRepresentation'
```
Comment (LavrovArtem) [inline src/processing/dom/internal-properties.ts:20]: `nativeStringRepresentation: 'hammerhead|native-string-representation'`

File: test/client/before-test.js [hunk 4]
```diff
@@ -199,6 +199,24 @@
...
     };
 
+    window.checkStringRepresentation = function (wrappedFn, originalFn) {
+        strictEqual(
+            wrappedFn.toString(),
+            originalFn.toString(),
+            'the outputs of the "toString()" method should be the same'
+        );
+        strictEqual(
+            Function.prototype.toString.call(wrappedFn),
```
Comment (LavrovArtem) [inline test/client/before-test.js:209]: `Function.prototype.toString` and `nativeMethods.Function.prototype.toString` are the same functions

**Review by LavrovArtem — CHANGES_REQUESTED** [review]

File: test/client/before-test.js (hunk 4 above)
Comment (wentwrong) [reply test/client/before-test.js:209]: Good catch! I found the same problem with `Worker.prototype`, `XMLHttpRequest.prototype` and `Function.prototype` ctor's.

**Comment by wentwrong** [comment]
@testcafe-build-bot retest

File: src/client/utils/property-overriding.ts [hunk 5]
```diff
@@ -54,3 +55,48 @@ export function overrideDescriptor<O extends object, K extends keyof O> (obj: O,
...
+    if (wrapperNameDescriptor) {
+        // eslint-disable-next-line no-restricted-properties
+        wrapperNameDescriptor.value = name;
+
+        nativeMethods.objectDefineProperty(fn, 'name', wrapperNameDescriptor);
+    }
+}
+
+export function overrideStringRepresentation (nativeFnWrapper: Function, nativeFn: Function): void {
+    overrideFunctionName(nativeFnWrapper, nativeFn['name']);
```
Comment (LavrovArtem) [inline src/client/utils/property-overriding.ts:71]:
```diff
-nativeFn['name']
+nativeFn.name
```

File: src/client/utils/property-overriding.ts [hunk 6]
```diff
@@ -54,3 +55,48 @@ export function overrideDescriptor<O extends object, K extends keyof O> (obj: O,
...
+
+    nativeFnWrapper[INTERNAL_PROPS.nativeStrRepresentation] = nativeMethods.Function.prototype.toString.call(nativeFn);
```
Comment (LavrovArtem) [inline src/client/utils/property-overriding.ts:73]:
```js
nativeMethods.objectDefineProperty(nativeFnWrapper, INTERNAL_PROPS.nativeStrRepresentation, { value: nativeMethods.Function.prototype.toString.call(nativeFn) });
```

**Review by LavrovArtem — CHANGES_REQUESTED** [review]
minor issues

**Comment by wentwrong** [comment]
@testcafe-build-bot retest

**Comment by wentwrong** [comment]
@testcafe-build-bot retest

File: src/client/utils/property-overriding.ts [hunk 7]
```diff
@@ -1,4 +1,5 @@
 import nativeMethods from '../sandbox/native-methods';
+import INTERNAL_PROPS from '../../processing/dom/internal-properties';
```
Comment (miherlosev) [inline src/client/utils/property-overriding.ts:2]: Rename the
`src/client/utils/property-overriding.ts` file to
to `src/client/utils/overriding.ts` since now this file contains functions for override not only properties.

File: src/client/utils/property-overriding.ts [hunk 8]
```diff
@@ -54,3 +55,53 @@ export function overrideDescriptor<O extends object, K extends keyof O> (obj: O,
 
     nativeMethods.objectDefineProperty(obj, prop, descriptor);
 }
+
+function overrideFunctionName (fn: Function, name: string) {
+    const wrapperNameDescriptor = nativeMethods.objectGetOwnPropertyDescriptor(fn, 'name');
```
Comment (miherlosev) [inline src/client/utils/property-overriding.ts:60]: `const nameDescriptor =...`

Comment (miherlosev) [reply src/client/utils/property-overriding.ts:60]: Use `//eslint-disable-line` because it makes the code more readable.
Use `fast forward` strategy here to avoid additional brackets:
```js
 if (!nameDescriptor)
    return;

nameDescriptor.value = name; // eslint-disable-line no-restricted-properties
```

File: src/client/utils/property-overriding.ts [hunk 9]
```diff
@@ -54,3 +55,53 @@ export function overrideDescriptor<O extends object, K extends keyof O> (obj: O,
...
+    }
+}
+
+export function overrideStringRepresentation (nativeFnWrapper: Function, nativeFn: Function): void {
+    overrideFunctionName(nativeFnWrapper, nativeFn.name);
+
+    // NOTE:
+    // `configurable`, `enumerable` and `writable` optional keys of the descriptor are set implicitly to false
+    // because we want to hide our internal property from the user code
+    nativeMethods.objectDefineProperty(nativeFnWrapper, INTERNAL_PROPS.nativeStrRepresentation, {
```
Comment (miherlosev) [inline src/client/utils/property-overriding.ts:76]: Move this instruction to the `overrideToString` function.

File: src/client/utils/property-overriding.ts [hunk 10]
```diff
@@ -54,3 +55,53 @@ export function overrideDescriptor<O extends object, K extends keyof O> (obj: O,
...
+        value: nativeMethods.Function.prototype.toString.call(nativeFn)
+    });
+}
+
+export function isNativeFunction (fn: Function): boolean {
+    return !nativeMethods.objectHasOwnProperty.call(fn, INTERNAL_PROPS.nativeStrRepresentation);
+}
+
+export function overrideFunction<O extends object, K extends keyof O> (obj: O, fnName: K, wrapper: Function): void {
```
Comment (miherlosev) [inline src/client/utils/property-overriding.ts:85]: I propose to change the function signature to 
```js
overrideFunction (target: Function, wrapper: Function);
```

File: src/client/utils/property-overriding.ts [hunk 11]
```diff
@@ -54,3 +55,53 @@ export function overrideDescriptor<O extends object, K extends keyof O> (obj: O,
...
+
+    if (wrapperNameDescriptor) {
+        // eslint-disable-next-line no-restricted-properties
+        wrapperNameDescriptor.value = name;
+
+        nativeMethods.objectDefineProperty(fn, 'name', wrapperNameDescriptor);
+    }
+}
+
+export function overrideStringRepresentation (nativeFnWrapper: Function, nativeFn: Function): void {
```
Comment (miherlosev) [inline src/client/utils/property-overriding.ts:70]: The name of this function is unclear.
Instead of it use combination of  the `overrideFunctionName` and `overrideToString` functions.

File: test/client/data/node-sandbox/iframe-override-elems-after-write.html [hunk 12]
```diff
@@ -20,6 +20,7 @@
 <script>
     var iframeSandbox = window['%hammerhead%'].sandbox.iframe;
     var INTERNAL_PROPS = hammerhead.get('../processing/dom/internal-properties');
+    var propertyOverridingUtils = hammerhead.get('../client/utils/property-overriding');
```
Comment (miherlosev) [inline test/client/data/node-sandbox/iframe-override-elems-after-write.html:23]: Align assignments:
```js
var iframeSandbox     = ...
var INTERNAL_PROPS =...
...
```

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/sandbox/event/index.ts [hunk 13]
```diff
@@ -171,33 +172,45 @@ export default class EventSandbox extends SandboxBase {
...
-        window.Event.prototype.preventDefault = this._overriddenMethods.preventDefault;
+        overrideFunction(window.Event.prototype, 'preventDefault', this._overriddenMethods.preventDefault);
 
         // @ts-ignore Window constructor has no the focus method
         window.Window.focus = this._overriddenMethods.focus;
+
+        // NOTE:
+        // we cannot use 'overrideFunction' here since the focus method may not exist
+        // @ts-ignore Window constructor has no the focus method
+        overrideStringRepresentation(window.Window.focus, nativeMethods.focus);
```
Comment (miherlosev) [inline src/client/sandbox/event/index.ts:200]: Add the necessary checks into the `overrideFunction` and use it here.

Remove the `overrideStringRepresentation` function and use the combination of `overrideFunctionName` and `overrdieToString` instead.

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: test/client/fixtures/sandbox/node/document-test.js [hunk 14]
```diff
@@ -1,9 +1,10 @@
...
-var INTERNAL_PROPS      = hammerhead.get('../processing/dom/internal-properties');
-var urlUtils            = hammerhead.get('./utils/url');
-var destLocation        = hammerhead.get('./utils/destination-location');
-var settings            = hammerhead.get('./settings');
+var processScript           = hammerhead.get('../processing/script').processScript;
+var SHADOW_UI_CLASSNAME     = hammerhead.get('../shadow-ui/class-name');
+var INTERNAL_PROPS          = hammerhead.get('../processing/dom/internal-properties');
+var urlUtils                = hammerhead.get('./utils/url');
+var destLocation            = hammerhead.get('./utils/destination-location');
+var propertyOverridingUtils = hammerhead.get('./utils/property-overriding');
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/node/document-test.js:6]: `var overriding = ...` here and above

File: test/client/fixtures/sandbox/iframe-test.js [hunk 15]
```diff
@@ -143,13 +144,11 @@ test('native methods are properly initialized in an iframe without src (GH-279)'
             var iframeDocument         = iframe.contentDocument;
             var iframeWindow           = iframe.contentWindow;
             var iframeHammerhead       = iframeWindow['%hammerhead%'];
-            var nativeCreateElement    = iframeHammerhead.sandbox.nativeMethods.createElement.toString();
-            var nativeAppendChild      = iframeHammerhead.sandbox.nativeMethods.appendChild.toString();
-            var overridedCreateElement = iframeDocument.createElement.toString();
-            var overridedAppendChild   = iframeDocument.createElement('div').appendChild.toString();
+            var overridedCreateElement = iframeDocument.createElement;
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/iframe-test.js:147]: Not `overrided`. Use the `overridden` word here and elsewhere.

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/sandbox/event/index.ts (hunk 13 above)
Comment (wentwrong) [reply src/client/sandbox/event/index.ts:200]: I assume that we shouldn't assign our wrapper to a native function when it is missing (e.g. `window.Window.focus`, which is undefined in IE11). It would be much better to flag these cases somehow (which I did by combining plain assignment and using `overrideStringRepresentation` function). We need to ensure that we override only those native functions that exist.

Comment (miherlosev) [reply src/client/sandbox/event/index.ts:200]: In this case we can omit any flags because it clear behavior - override only existing functions.
Also, in general case the flag is the worst way to pass parameters.
See https://github.com/ryanmcdermott/clean-code-javascript#dont-use-flags-as-function-parameters

Comment (wentwrong) [reply src/client/sandbox/event/index.ts:200]: After a more in-depth discussion with @miherlosev and @LavrovArtem, we decided to use `overrideStringRepresentation` in cases like this. It's temporarily and later it'll be implemented properly through `overrideFunction`.

**Comment by wentwrong** [comment]
@testcafe-build-bot retest

File: src/client/sandbox/node/document/index.ts [hunk 16]
```diff
@@ -198,46 +193,46 @@ export default class DocumentSandbox extends SandboxBase {
             }
         };
 
-        window[nativeMethods.documentOpenPropOwnerName].prototype.open       = overridenMethods.open;
-        window[nativeMethods.documentClosePropOwnerName].prototype.close     = overridenMethods.close;
-        window[nativeMethods.documentWritePropOwnerName].prototype.write     = overridenMethods.write;
-        window[nativeMethods.documentWriteLnPropOwnerName].prototype.writeln = overridenMethods.writeln;
+        overrideFunction(window[nativeMethods.documentOpenPropOwnerName].prototype, 'open', overridenMethods.open);
```
Comment (miherlosev) [inline src/client/sandbox/node/document/index.ts:196]: `overriden` -> `overridden` here and everywhere.

`overriddenMethods.open`

File: src/client/sandbox/style.ts [hunk 17]
```diff
@@ -168,19 +168,21 @@ export default class StyleSandbox extends SandboxBase {
...
             const nativeFn = this.nativeMethods.objectGetOwnPropertyDescriptor.call(window.Object, styleDeclarationProto, prop).value;// eslint-disable-line no-restricted-properties
 
             if (this.nativeMethods.objectHasOwnProperty.call(styleDeclarationProto, prop) &&
                 typeof nativeFn === 'function') {
-                styleDeclarationProto[prop] = function () {
+                (styleDeclarationProto[prop] as unknown as Function) = function () {
                     return nativeFn.apply(this[CSS_STYLE_PROXY_TARGET] || this, arguments);
                 };
+
+                // NOTE:
```
Comment (miherlosev) [inline src/client/sandbox/style.ts:183]: Use the follwong comment style:

```js
// NOTE: we cannot use 'overrideFunction' here since the function may not exist

// TODO: this function should not be used outside this file
```

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/utils/overriding.ts [hunk 18]
```diff
@@ -0,0 +1,113 @@
...
+    if (!nameDescriptor)
+        return;
+
+    nameDescriptor.value = name; // eslint-disable-line no-restricted-properties
+
+    nativeMethods.objectDefineProperty(fn, 'name', nameDescriptor);
+}
+
+function overrideToString (nativeFnWrapper: Function, nativeFn: Function): void {
+    // NOTE:
```
Comment (miherlosev) [inline src/client/utils/overriding.ts:71]: I guess we can remove this comment because the all INTERNAL_PROPS added in the same way.

Also, hiding the proxy from the web site client code is a main concept.

File: src/client/sandbox/xhr.ts [hunk 19]
```diff
@@ -85,35 +84,33 @@ export default class XhrSandbox extends SandboxBase {
             });
         }
 
-        window.XMLHttpRequest           = xmlHttpRequestWrapper;
-        xmlHttpRequestWrapper.prototype = xmlHttpRequestProto;
-        xmlHttpRequestWrapper.toString  = () => xmlHttpRequestToString;
-
         // NOTE: We cannot just assign constructor property in OS X 10.11 safari 9.0
+        overrideConstructor(window, 'XMLHttpRequest', xmlHttpRequestWrapper);
```
Comment (miherlosev) [inline src/client/sandbox/xhr.ts:88]: `// NOTE: We cannot just assign constructor property in OS X 10.11 safari 9.0`

Is this comment still actual?

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/sandbox/xhr.ts (hunk 19 above)
Comment (wentwrong) [reply src/client/sandbox/xhr.ts:88]: Yes, we still cannot just assign constructor property (as `overrideConstructor` does when the fourth parameter `overrideProtoConstructor` is set to true). In the code below this line, we are using 'objectDefineProperty' in order to override constructor property.

Comment (wentwrong) [reply src/client/sandbox/xhr.ts:88]: I think a better way to phrase it to make the comment clearer would be:
```
// NOTE: We cannot just assign constructor property of the prototype of XMLHttpRequest in OS X 10.11 safari 9.0
```

Comment (miherlosev) [reply src/client/sandbox/xhr.ts:88]: At present, we don't use the Safari 9.0 (Safari 11.3 and 12.0 versions are used).
If this code is necessary, then update comment to 
`// NOTE: We cannot just assign constructor property of the prototype of XMLHttpRequest starts from safari 9.0`

**Review by miherlosev — APPROVED** [review]

**Review by LavrovArtem — APPROVED** [review]
