### PR TITLE
fix `Tests sometimes (frequently) lose connection` (close #1647, related to DevExpress/testcafe#2711)

### LINKED ISSUE #1647: Tests sometimes (frequently) lose connection
Sometimes when I launch tests, the tests suddenly stops; I get this error message when I look at the console. 

It doesn't matter what browser I use. I am on MacOS

```
.../node_modules/testcafe-hammerhead/lib/request-pipeline/connection-reset-guard.js:20
        throw new Error(err);
        ^

Error: Error: write EPIPE
    at Domain.<anonymous> (.../node_modules/testcafe-hammerhead/lib/request-pipeline/connection-reset-guard.js:20:15)
    at Domain.emit (events.js:182:13)
    at Domain.EventEmitter.emit (domain.js:442:20)
    at Domain._errorHandler (domain.js:224:23)
    at Object.setUncaughtExceptionCaptureCallback (domain.js:140:29)
    at process._fatalException (internal/bootstrap/node.js:447:31)```

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

File: src/request-pipeline/connection-reset-guard.js [hunk 1]
```diff
@@ -1,12 +1,14 @@
...
+import os from 'os';
 
 const connectionResetDomain = domain.create();
 
 connectionResetDomain.on('error', err => {
-    if (err.code !== 'ECONNRESET') {
-        connectionResetDomain.removeAllListeners('error');
-        throw new Error(err);
-    }
+    if (err.code === 'ECONNRESET' || os.type() === 'Darwin' && err.code === 'EPIPE')
```
Comment (miherlosev) [inline src/request-pipeline/connection-reset-guard.js]: Comment this line
