### PR TITLE
fix 'Client html util cleanUpHtml doesn't clean `data-hammerhead-focused` attribute' (close #1143)

### LINKED ISSUE #1143: Client html util cleanUpHtml doesn't clean `data-hammerhead-focused` attribute
Here is `data-hammerhead-hovered` is removed: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/html.js#L158
Here should be `data-hammerhead-focused` removing too.

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin  @miherlosev

### CODE REVIEW

File: test/client/fixtures/utils/html-test.js [hunk 1]
```diff
@@ -31,14 +31,24 @@ test('hover marker', function () {
...
+    var expected      = '<a href="http://domain.com"></a><div></div><div></div>';
+    var processedHtml = htmlUtils.processHtml(html);
 
-    strictEqual(htmlUtils.cleanUpHtml(pocessedHtml), expexted);
+    strictEqual(htmlUtils.cleanUpHtml(processedHtml), expected);
 
     urlUtils.getProxyUrl = storedGetProxyUrl;
 });
 
+test('focus marker and autocomplete stored', function () {
```
Comment (miherlosev) [inline test/client/fixtures/utils/html-test.js]: I don't see test code for autocomplete attribute.

I propose to have to two tests:
- `focus marker`
 - `autocomplete attribute`

Note, we have the special logic in `hasAttribute` for `autocomplete` attribute. See https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/node/attributes-test.js#L583

File: test/client/fixtures/utils/html-test.js [hunk 2]
```diff
@@ -31,14 +31,29 @@ test('hover marker', function () {
...
+test('focus marker', function () {
+    var html = '<input ' + INTERNAL_ATTRS.focusPseudoClass + '>' +
+               '<input ' + INTERNAL_ATTRS.focusPseudoClass + '="">';
+
+    strictEqual(htmlUtils.cleanUpHtml(html), '<input><input>');
+});
+
+test('autocomplete attribute', function () {
+    var html = '<input ' + domProcessor.getStoredAttrName('autocomplete') +
+               '="hammerhead|autocomplete-attribute-absence-marker" autocomplete="off">' +
```
Comment (miherlosev) [inline test/client/fixtures/utils/html-test.js]: Use constant as `domProcessor.AUTOCOMPLETE_ATTRIBUTE_ABSENCE_MARKER`

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

File: src/client/utils/html.js [hunk 3]
```diff
@@ -30,6 +30,14 @@ const UNWRAP_DOCTYPE_RE     = new RegExp(`<${ FAKE_DOCTYPE_TAG_NAME }>([\\S\\s]*
 const FIND_SVG_RE      = /<svg\s?[^>]*>/ig;
 const FIND_NS_ATTRS_RE = /\s(?:NS[0-9]+:[^"']+('|")[\S\s]*?\1|[^:]+:NS[0-9]+=(?:""|''))/g;
 
+const ATTRS_FOR_CLEANING        = domProcessor.URL_ATTRS.concat('autocomplete');
+const STORED_ATTRS_FOR_CLEANING = (storedAttrs => {
+    for (var i = 0; i < ATTRS_FOR_CLEANING.length; i++)
```
Comment (miherlosev) [inline src/client/utils/html.js]: use `for.. of` loop for more readable code

File: src/client/utils/html.js [hunk 4]
```diff
@@ -110,21 +118,18 @@ export function cleanUpHtml (html) {
     return processHtmlInternal(html, container => {
         var changed = false;
 
-        /*eslint-disable no-loop-func */
-        for (var i = 0; i < domProcessor.URL_ATTRS.length; i++) {
-            var attr       = domProcessor.URL_ATTRS[i];
-            var storedAttr = domProcessor.getStoredAttrName(attr);
+        find(container, '[' + STORED_ATTRS_FOR_CLEANING.join('],[') + ']', el => {
```
Comment (miherlosev) [inline src/client/utils/html.js]: Declare all selectors used in `find` as constants

File: src/client/utils/html.js [hunk 5]
```diff
@@ -110,21 +118,18 @@ export function cleanUpHtml (html) {
...
+            for (var i = 0; i < ATTRS_FOR_CLEANING.length; i++) {
```
Comment (miherlosev) [inline src/client/utils/html.js]: use `for ..of` loop

**Comment by LavrovArtem** [comment]
FPR

File: src/client/utils/html.js [hunk 6]
```diff
@@ -155,8 +171,9 @@ export function cleanUpHtml (html) {
             }
         });
 
-        find(container, '[' + INTERNAL_ATTRS.hoverPseudoClass + ']', el => {
+        find(container, '[' + INTERNAL_ATTRS.hoverPseudoClass + '],[' + INTERNAL_ATTRS.focusPseudoClass + ']', el => {
```
Comment (miherlosev) [inline src/client/utils/html.js]: Move all calculated selectors to contants.
```js
'[class*="' + SHADOW_UI_CLASSNAME.postfix + '"]',
'[' + INTERNAL_ATTRS.hoverPseudoClass + '],[' + INTERNAL_ATTRS.focusPseudoClass + ']',
`${FAKE_TAG_NAME_PREFIX}head, ${FAKE_TAG_NAME_PREFIX}body`
```

It is perfomance optimization.
Before selectors is calculated on each `cleanHtml` call.
After it will be calculated only on module creation.

**Comment by LavrovArtem** [comment]
FPR

File: src/client/utils/html.js [hunk 7]
```diff
@@ -30,6 +30,29 @@ const UNWRAP_DOCTYPE_RE     = new RegExp(`<${ FAKE_DOCTYPE_TAG_NAME }>([\\S\\s]*
...
+    var storedAttrs = [];
+
+    for (var { storedAttr } of ATTRS_FOR_CLEANING)
+        storedAttrs.push(storedAttr);
+
+    return '[' + storedAttrs.join('],[') + ']';
+})();
+
+const SHADOW_UI_ELEMENTS_SELECTOR    = `[class*="${SHADOW_UI_CLASSNAME.postfix}"]`;
+const PSEUDO_CLASS_ELEMENTS_SELECTOR = `[${INTERNAL_ATTRS.hoverPseudoClass}],[${INTERNAL_ATTRS.focusPseudoClass}]`;
```
Comment (miherlosev) [inline src/client/utils/html.js]: Unclear name.
Rename to `HOVER_AND_FOCUS_PSEUDO_CLASS_SELECTOR`

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: src/client/utils/html.js [hunk 8]
```diff
@@ -30,6 +30,29 @@ const UNWRAP_DOCTYPE_RE     = new RegExp(`<${ FAKE_DOCTYPE_TAG_NAME }>([\\S\\s]*
...
+    var storedAttrs = [];
+
+    for (var { storedAttr } of ATTRS_FOR_CLEANING)
+        storedAttrs.push(storedAttr);
+
+    return '[' + storedAttrs.join('],[') + ']';
+})();
+
+const SHADOW_UI_ELEMENTS_SELECTOR           = `[class*="${SHADOW_UI_CLASSNAME.postfix}"]`;
+const HOVER_AND_FOCUS_PSEUDO_CLASS_SELECTOR = `[${INTERNAL_ATTRS.hoverPseudoClass}],[${INTERNAL_ATTRS.focusPseudoClass}]`;
```
Comment (miherlosev) [inline src/client/utils/html.js]: `HOVER_AND_FOCUS_PSEUDO_CLASS_ELEMENTS_SELECTOR`
see https://github.com/DevExpress/testcafe-hammerhead/pull/1145#discussion_r118677713

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Comment by miherlosev** [comment]
ping @churkin
