### PR TITLE
fix `The overridden postMessage function lose the transfer argument` (close #1535)

### LINKED ISSUE #1535: The overridden postMessage function lose the transfer argument
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

https://github.com/DevExpress/testcafe-hammerhead/blob/2d7455c13418d34b1c0a2756848c784ecc20d210/src/client/sandbox/event/message.js#L190

site: https://pinterest.com/

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/1535

### Changes
1. Pass all arguments to native `PostMessage` function after process.

### Notes
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage:
> targetWindow.postMessage(message, targetOrigin, [transfer]);

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage:

> `transfer`:
> Is a sequence of Transferable objects that are transferred with the message. The ownership of these objects is given to the destination side and they are no longer usable on the sending side.

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: test/client/fixtures/sandbox/event/message-test.js [hunk 1]
```diff
@@ -19,6 +19,24 @@ asyncTest('onmessage event (handler has "object" type) (GH-133)', function () {
     callMethod(window, 'postMessage', [testMessage, '*']);
 });
 
+asyncTest('should pass "transfer" argument for "postMessage" (GH-1535)', function () {
+    expect(2);
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/event/message-test.js]: `expect` is unnecessary

**Comment by Farfurix** [comment]
@testcafe-build-bot retest
