### PR TITLE
fix `The XhrSandbox.openNativeXhr function calls non native the xhr.setRequestHeader function` (close #1252)

### LINKED ISSUE #1252: The XhrSandbox.openNativeXhr function calls non native the xhr.setRequestHeader function
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/xhr.js#L45
Page: https://www.starbucks.com/green-apron-delivery/

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @miherlosev @churkin

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/sandbox/xhr-test.js [hunk 1]
```diff
@@ -17,6 +17,13 @@ QUnit.testDone(function () {
     iframeSandbox.off(iframeSandbox.RUN_TASK_SCRIPT_EVENT, initIframeTestHandler);
 });
 
+function findPrototypeWithProp (obj, prop) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/xhr-test.js]: `getPrototypeFromChainContainsProp (obj, prop)`

File: test/client/fixtures/sandbox/xhr-test.js [hunk 2]
```diff
@@ -43,6 +50,23 @@ test('createNativeXHR', function () {
     ok(xhr instanceof nativeMethods.XMLHttpRequest);
 
     window.XMLHttpRequest = nativeMethods.XMLHttpRequest;
+
+    var isWrappedFunctionRE = /^return 'function wrapped'$/;
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/xhr-test.js]: `var isWrappedFunctionRE = /^return 'function is wrapped'$/;`
