### PR TITLE
fix `The document.body.children.length has wrong value in IE and Edge` (close #1763)

### LINKED ISSUE #1763: The document.body.children.length has wrong value in IE and Edge.
Reproducible on `https://localvoid.github.io/uibench/`.

Without hammerhead the `document.body.children.length` property is `5`.

In Chrome with hammerhead playground it's still `5`.

In IE and Edge, it's `6`. The last element of the `document.body.children` collection is hammerhead's shadow root, and it turns into `undefined` when trying to get it from an instrumented code. It causes infinite recursion in `testcafe-react-selectors` here: https://github.com/DevExpress/testcafe-react-selectors/blob/master/src/react-16/get-root-els.js#L19

### PR DESCRIPTION
**Pull request by Farfurix**
DevExpress/testcafe-hammerhead#1763

### Changes
1. Fix `length` getter of `HTMLCollection` (`body.children`, `head.children`) for IE11, Edge.
2. Pass list length using native `HTMLCollection`/`NodeList` getter to `_filterNodeList`.
3. `src/utils/create-self-removing-script.js` fix: use native `htmlCollectionLengthGetter` for scripts `HTMLCollection`.
4. Use _short_ invocation without `call`/`apply`: ` nativeMethods.objectDefineProperty(collection, ...);`.

### Native introducing example (Edge, Internet Explorer 11)
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
<script>
    Object.defineProperty(document.body.children, 'hh-flag-children', {value: true} );
    Object.defineProperty(document.body, 'hh-flag-body', {value: true} );
    Object.defineProperty(document.body.childNodes, 'hh-flag-body-childNodes', {value: true} );
    Object.defineProperty(document.head, 'hh-flag-head', {value: true} );

    setInterval(function () {
        console.log('hh-flag-children === ' + document.body.children['hh-flag-children']);
        console.log('hh-flag-body === ' + document.body['hh-flag-body']);
        console.log('hh-flag-body-childNodes === ' + document.body.childNodes['hh-flag-body-childNodes']);
        console.log('hh-flag-head === ' + document.head['hh-flag-head']);
        console.log('////////////////////////////////');
    }, 500)
</script>
</html>
```
After `document`, `document.body` call in console `hh-flag-children` may become `undefined`:
```
 hh-flag-children === true
 hh-flag-body === true
 hh-flag-body-childNodes === true
 hh-flag-head === true
 ////////////////////////////////

> document.body
< <body>...</body>

 hh-flag-children === undefined
 hh-flag-body === true
 hh-flag-body-childNodes === true
 hh-flag-head === true
 ////////////////////////////////
```
### Notes
https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByName:
> Both IE and Edge return an `HTMLCollection`, not a `NodeList`

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: src/client/sandbox/shadow-ui.js [hunk 1]
```diff
@@ -600,6 +619,10 @@ export default class ShadowUI extends SandboxBase {
             ShadowUI._markElementAsShadow(childElement);
     }
 
+    static markCollectionAsShadow (collection) {
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: `markAsShadowContainerCollection (collection)`

File: src/client/sandbox/shadow-ui.js [hunk 2]
```diff
@@ -64,15 +64,15 @@ export default class ShadowUI extends SandboxBase {
...
 
-    _filterNodeList (nodeList) {
-        return this._filterList(nodeList, item => ShadowUI._filterElement(item));
+    _filterNodeList (nodeList, nodeListLength) {
+        return this._filterList(nodeList, nodeListLength, item => ShadowUI._filterElement(item));
     }
 
-    _filterStyleSheetList (styleSheetList) {
-        return this._filterList(styleSheetList, item => ShadowUI._filterElement(item.ownerNode));
+    _filterStyleSheetList (styleSheetList, styleSheetListLength) {
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: ` _filterStyleSheetList (styleSheetList, originLength)`

File: src/client/sandbox/node/document/index.js [hunk 3]
```diff
@@ -257,8 +257,9 @@ export default class DocumentSandbox extends SandboxBase {
         overrideDescriptor(documentScriptsPropOwnerPrototype, 'scripts', {
             getter: function () {
                 const scripts = nativeMethods.documentScriptsGetter.call(this);
+                const length = nativeMethods.htmlCollectionLengthGetter.call(scripts);
```
Comment (miherlosev) [inline src/client/sandbox/node/document/index.js]: formatting

File: src/client/sandbox/shadow-ui.js [hunk 4]
```diff
@@ -64,15 +64,15 @@ export default class ShadowUI extends SandboxBase {
             });
         }
 
-        return filteredList.length === nlLength ? list : filteredList;
+        return filteredList.length === listLength ? list : filteredList;
     }
 
-    _filterNodeList (nodeList) {
-        return this._filterList(nodeList, item => ShadowUI._filterElement(item));
+    _filterNodeList (nodeList, nodeListLength) {
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: `_filterNodeList (nodeList, originLength)`

File: src/client/sandbox/shadow-ui.js [hunk 5]
```diff
@@ -131,15 +134,18 @@ export default class ShadowUI extends SandboxBase {
...
+                    return sandbox._filterNodeList(list, length);
                 };
             }
         };
     }
 
     _markShadowUIContainerAndCollections (containerEl) {
         nativeMethods.objectDefineProperty.call(this.window.Object, containerEl, IS_SHADOW_CONTAINER_FLAG, { value: true });
-        nativeMethods.objectDefineProperty.call(this.window.Object, containerEl.children, IS_SHADOW_CONTAINER_COLLECTION_FLAG, { value: true });
+        ShadowUI.markCollectionAsShadow(containerEl.children);
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: Let's create the `ShadowUI.markAsShadowUIContainer` too and replace with it in all appropriate places.

File: test/client/fixtures/sandbox/shadow-ui-test.js [hunk 6]
```diff
@@ -22,6 +22,36 @@ QUnit.testStart(function () {
     $(TEST_CLASS_SELECTOR).remove();
 });
 
+// IE11 and Edge have a strange behavior: shadow container collection flag may be lost (GH-1763)
+if (browserUtils.isIE) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/shadow-ui-test.js]: Remove this condition, because the fix should work with all supported browsers.

File: test/client/fixtures/sandbox/shadow-ui-test.js [hunk 7]
```diff
@@ -22,6 +22,36 @@ QUnit.testStart(function () {
...
+    test('shadow container collection flag should not be lost (GH-1763)', function () {
+        var anchor               = document.createElement('a');
+        var childrenOriginLength = nativeMethods.htmlCollectionLengthGetter.call(document.body.children);
+
+        function wait (timeout) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/shadow-ui-test.js]: It's an util function. Move this to the `test/client/before-test.js` file.

File: src/client/sandbox/shadow-ui.js [hunk 8]
```diff
@@ -131,15 +134,18 @@ export default class ShadowUI extends SandboxBase {
                     if (typeof args[0] === 'string')
                         args[0] = NodeSandbox.processSelector(args[0]);
 
-                    return sandbox._filterNodeList(nativeMethods[nativeQuerySelectorAllFnName].apply(this, args));
+                    const list = nativeMethods[nativeQuerySelectorAllFnName].apply(this, args);
```
Comment (LavrovArtem) [inline src/client/sandbox/shadow-ui.js]: formatting

File: src/client/sandbox/shadow-ui.js (hunk 1 above)
Comment (LavrovArtem) [reply src/client/sandbox/shadow-ui.js]: I think that the `Container` word is extra.

Comment (Farfurix) [reply src/client/sandbox/shadow-ui.js]: We have:
`container-collection-flag`,
`isShadowContainerCollection` check,

but 

`getShadowUICollectionLength` function

File: src/client/sandbox/shadow-ui.js [hunk 9]
```diff
@@ -131,15 +134,18 @@ export default class ShadowUI extends SandboxBase {
...
+                    const list   = nativeMethods[nativeQuerySelectorAllFnName].apply(this, args);
+                    const length = nativeMethods.nodeListLengthGetter.call(list);
+
+                    return sandbox._filterNodeList(list, length);
                 };
             }
         };
     }
 
     _markShadowUIContainerAndCollections (containerEl) {
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: Rewrite as follows:
```js
_markShadowUIContainerAndCollections (containerEl) { 
     ShadowUI.markAsShadowContainer(containerEl);
     ShadowUI.markAsShadowContainerCollection(containerEl.children);
     ShadowUI.markAsShadowContainerCollection(containerEl.childNodes);
}
```

File: test/client/before-test.js [hunk 10]
```diff
@@ -8,6 +8,8 @@
     var hammerhead    = window['%hammerhead%'];
     var nativeMethods = hammerhead.nativeMethods;
 
+    var Promise = hammerhead.Promise;
```
Comment (miherlosev) [inline test/client/before-test.js]: You define `Promise` as a global object. It may bring to wrong tests for browsers that doesn't support `Promises` (i.e `IE11`).  Put `Promise` declaration into `window.wait` function.

File: test/client/before-test.js [hunk 11]
```diff
@@ -19,6 +19,14 @@
 
     destLocation.forceLocation('http://localhost/sessionId/https://example.com/');
 
+    window.wait = function (timeout) {
+        var Promise = hammerhead.Promise;
+
+        return new Promise(function (resolve) {
```
Comment (miherlosev) [inline test/client/before-test.js]: You can combine to
```js
return new hammerhead.Promise(function (resolve) {
```

File: src/client/sandbox/shadow-ui.js (hunk 9 above)
Comment (Farfurix) [reply src/client/sandbox/shadow-ui.js]: Done.
