### PR TITLE
fix tests for Google Chrome 47 (close #317)

### LINKED ISSUE #317: Some tests fail in latest Google Chrome (47.0.2526.73)
/fixtures/sandbox/code-instrumentation/getters-test.js
/fixtures/sandbox/node/attributes-test.js
/fixtures/utils/dom-test.js

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @churkin @inikulin

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 1]
```diff
@@ -134,36 +134,38 @@ test('document.referrer', function () {
...
 if (browserUtils.isWebKit) {
     test('url in stylesheet properties', function () {
-        var el       = document.createElement('div');
-        var url      = 'http://google.com/image.png';
-        var proxyUrl = urlUtils.getProxyUrl(url);
+        var el                 = document.createElement('div');
+        var url                = 'http://google.com/image.png';
+        var proxyUrl           = urlUtils.getProxyUrl(url);
+        var buildExpectedValue = function (value) {
+            var usedQuoteString = browserUtils.isSafari || browserUtils.isAndroid ? '' : '"';
```
Comment (inikulin) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: It's `quote`, not `userQuoteString`. And let's use feature detection to determine actual format of the quotes, so if it will change we will be notified about it.

File: src/client/utils/dom.js [hunk 2]
```diff
@@ -277,8 +277,7 @@ export function isDomElement (el) {
         return false;
 
     // NOTE: B252941
-    return el && (typeof el === 'object' || isFirefox && typeof el === 'function') &&
-           el.nodeType !== 11 && typeof el.nodeName === 'string' && el.tagName;
+    return el && el.nodeType !== 11 && typeof el.nodeName === 'string' && el.tagName;
```
Comment (inikulin) [inline src/client/utils/dom.js]: We need to investigate that it will not introduce regression for the B252941

**Comment by inikulin** [comment]
\r-

File: src/client/utils/dom.js (hunk 2 above)
Comment (miherlosev) [inline src/client/utils/dom.js]: We have the problem with Flash in Firefox #332

**Comment by miherlosev** [comment]
FPR

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 3]
```diff
@@ -134,36 +134,45 @@ test('document.referrer', function () {
...
+                var div = document.createElement('div');
+
+                div.style.backgroundImage = 'url(http://example.com/img.jpg)';
+
+                return div.style.backgroundImage.match(/url\((.*)http:\/\/example.com\/img.jpg/)[1];
+            };
+            var quote              = calculateQuote();
+
+            return 'url(' + quote + value + quote + ')';
+        };
```
Comment (inikulin) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: You can do this once:
```js
var quote = (function() {
   var div = document.createElement('div');
   
   div.style.backgroundImage = 'url(http://example.com/img.jpg)';

   return div.style.backgroundImage.match(/url\((.*)http:\/\/example.com\/img.jpg/)[1];
})();

function getExpected (url) {
     return 'url(' + quote + url + quote + ')';
}
```

**Comment by inikulin** [comment]
\r-

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 4]
```diff
@@ -134,36 +134,43 @@ test('document.referrer', function () {
...
+        var quote              = (function () {
+            var div = document.createElement('div');
+
+            div.style.backgroundImage = 'url(http://example.com/img.jpg)';
+
+            return div.style.backgroundImage.match(/url\((.*)http:\/\/example.com\/img.jpg/)[1];
+        })();
+        var buildExpectedValue = function (value) {
+            return 'url(' + quote + value + quote + ')';
+        };
```
Comment (inikulin) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: Just name it `getExpected` as I suggested previously. There is nothing to `build` here

**Comment by inikulin** [comment]
\r-

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

File: src/client/utils/dom.js (hunk 2 above)
Comment (miherlosev) [inline src/client/utils/dom.js]: I tried to click <object> tag in playground and using testcafe.
All works right.

**Comment by miherlosev** [comment]
> We need to investigate that it will not introduce regression for the B252941

I tried to click <object> tag in playground and using testcafe (FF, Chrome and IE).
All works right.

FRP

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm
