### PR TITLE
fix 'A service message will not be send from iframe if it was unloaded' (close #729)

### LINKED ISSUE #729: A service message will not be send from iframe if it was unloaded
see T413262

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @helen-dikareva

### CODE REVIEW

File: src/client/sandbox/event/message.js [hunk 1]
```diff
@@ -124,19 +125,22 @@ export default class MessageSandbox extends SandboxBase {
...
         // NOTE: The window.top property may be changed after an iframe is removed from DOM in IE, so we save it.
-        this.topWindow = window.top;
+        this.topWindow        = window.top;
+        this.isWindowUnloaded = false;
 
         this.unloadSandbox.on(this.unloadSandbox.UNLOAD_EVENT, () => {
             while (this.iframeInternalMsgQueue.length) {
                 var msgInfo = this.iframeInternalMsgQueue[0];
 
+                this.isWindowUnloaded = true;
```
Comment (helen-dikareva) [inline src/client/sandbox/event/message.js]: we can do it before the cycle

File: src/client/sandbox/event/message.js [hunk 2]
```diff
@@ -210,13 +214,22 @@ export default class MessageSandbox extends SandboxBase {
...
             };
 
-            // NOTE: Imitation of a delay for the postMessage method.
-            // We use the same-domain top window
-            // so that the function called by setTimeout is executed after removing the iframe
-            var topSameDomainWindow = getTopSameDomainWindow(this.window);
-            var timeoutId           = nativeMethods.setTimeout.call(topSameDomainWindow, sendFunc, 10);
-
-            this.iframeInternalMsgQueue.push({ timeoutId, sendFunc });
+            if (this.isWindowUnloaded) {
```
Comment (helen-dikareva) [inline src/client/sandbox/event/message.js]: I would make smthng like 'force' flag for skip calling `_removeInternalMsgFromQueue` method in `sendFunc` and call it if `this.isWindowUnloaded` is true.

**Comment by helen-dikareva** [comment]
\r-

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/event/message.js [hunk 3]
```diff
@@ -196,8 +195,17 @@ export default class MessageSandbox extends SandboxBase {
...
         // NOTE: For iframes without src.
-        if (!this._isIframeRemoved() && (isIframeWithoutSrc || !isCrossDomainWindows(targetWindow, this.window) &&
-                                                               targetWindow[this.RECEIVE_MSG_FN])) {
+        if (isIframeWithoutSrc || !isCrossDomainWindows(targetWindow, this.window) && targetWindow[this.RECEIVE_MSG_FN]) {
+            if (this.isWindowUnloaded) {
+                targetWindow[this.RECEIVE_MSG_FN]({
+                    // NOTE: Cloning a message to prevent this modification.
+                    data:   parseJSON(stringifyJSON(message)),
+                    source: this.window
+                });
```
Comment (churkin) [inline src/client/sandbox/event/message.js]:
```javascript
targetWindow[this.RECEIVE_MSG_FN]({
                     // NOTE: Cloning a message to prevent this modification.
                     data:   parseJSON(stringifyJSON(message)),
                     source: this.window
                 });
```
duplicate code

**Comment by churkin** [comment]
-\r

**Comment by LavrovArtem** [comment]
FPR

**Comment by churkin** [comment]
lgtm
