### PR TITLE
fix `Remove `integrity` attributes from resources` (close #235)

### LINKED ISSUE #235: Remove `integrity` attributes from resources
See: http://www.w3.org/TR/SRI/

This attribute is used to avoid MITM attacks. Attribute contains SHA of the desired resource. Which doesn't work for us. This is widely used currently. And it brokes e.g. GitHub proxying. I suggest to remove this attribute entirely. It applies only to `<script>` and `<link>` elements.

### PR DESCRIPTION
**Pull request by Farfurix**
### References:
https://github.com/DevExpress/testcafe-hammerhead/issues/235
https://github.com/DevExpress/testcafe-hammerhead/pull/236/files

### Notes
Edge, Internet Explorer 11 and Safari 11 have no `integrity` property:
```
> Object.getOwnPropertyDescriptor(Object.getPrototypeOf(document.createElement('script')), 'integrity');
< undefined
> Object.getOwnPropertyDescriptor(Object.getPrototypeOf(document.createElement('link')), 'integrity');
< undefined
```

### CODE REVIEW

File: test/client/fixtures/sandbox/node/dom-processor-test.js [hunk 1]
```diff
@@ -486,7 +488,9 @@ test('remove the "integrity" attribute from the link and script tags (GH-235)',
     domProcessor.processElement(link, urlReplacer);
 
     ok(!script.hasAttribute('integrity'));
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/dom-processor-test.js]: Wrong assertion.

File: test/client/fixtures/sandbox/node/dom-processor-test.js [hunk 2]
```diff
@@ -486,7 +488,9 @@ test('remove the "integrity" attribute from the link and script tags (GH-235)',
...
+    strictEqual(nativeMethods.getAttribute.call(script, storedIntegrityAttrName), integrityValue);
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/dom-processor-test.js]:
```js
strictEqual(script.getAttribute('integrity'), integrityValue);
strictEqual(nativeMethods.getAttribute.call(script, 'integrity'), null);
```
Instead of this assertion.

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/native-methods.js [hunk 3]
```diff
@@ -310,6 +312,14 @@ class NativeMethods {
         this.elementInnerHTMLSetter     = elementInnerHTMLDescriptor.set;
         this.elementOuterHTMLSetter     = elementOuterHTMLDescriptor.set;
 
+        // NOTE: Some browsers have no 'integrity' property in HTMLScriptElement
```
Comment (miherlosev) [inline src/client/sandbox/native-methods.js]: Which browsers do not have `integrity`? Specify, please in comment

File: src/client/sandbox/node/element.js [hunk 4]
```diff
@@ -98,6 +99,16 @@ export default class ElementSandbox extends SandboxBase {
             else if (el.hasAttribute(storedAttrName))
                 args[isNs ? 1 : 0] = storedAttrName;
         }
+        // NOTE: We simply remove the 'integrity' attribute because its value will not be relevant after the script
+        // content changes (http://www.w3.org/TR/SRI/). If this causes problems in the future, we will need to generate
+        // the correct SHA for the changed script.
+        // getAttributeCore returns stored 'integrity' attribute value. (GH-235)
```
Comment (miherlosev) [inline src/client/sandbox/node/element.js]: I think we can remove this line (only 105 line).  I don't see benefit of this comment.

File: test/client/fixtures/sandbox/node/attributes-test.js [hunk 5]
```diff
@@ -181,6 +181,50 @@ test('script src', function () {
...
+    }
+
+    script.setAttribute('integrity', integrityValue);
+    link.setAttribute('integrity', integrityValue);
+
+    checkIntegrityAttr(script);
+    checkIntegrityAttr(link);
+});
+
+if (nativeMethods.scriptIntegrityGetter) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/node/attributes-test.js]: Can we split two these tests?

File: src/client/sandbox/node/element.js [hunk 6]
```diff
@@ -98,6 +99,16 @@ export default class ElementSandbox extends SandboxBase {
...
+        else if (loweredAttr === 'integrity' && DomProcessor.isTagWithIntegrityAttr(tagName) && !isNs) {
```
Comment (miherlosev) [inline src/client/sandbox/node/element.js]: Add tests for `setAttributeNS` and `getAttributeNS` cases.

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/native-methods.js [hunk 7]
```diff
@@ -310,6 +312,13 @@ class NativeMethods {
         this.elementInnerHTMLSetter     = elementInnerHTMLDescriptor.set;
         this.elementOuterHTMLSetter     = elementOuterHTMLDescriptor.set;
 
+        // NOTE: Some browsers (for example, Edge, Internet Explorer 11, Safari) have no 'integrity' property
```
Comment (miherlosev) [inline src/client/sandbox/native-methods.js]: // NOTE: Some browsers (for example, Edge, Internet Explorer 11, Safari) do not support an `integrity` attribute.

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/sandbox/node/attributes-test.js [hunk 8]
```diff
@@ -181,6 +181,54 @@ test('script src', function () {
     settings.get().sessionId = storedSessionId;
 });
 
+test('"integrity" attribute (GH-235)', function () {
+    var script         = nativeMethods.createElement.call(document, 'script');
+    var link           = nativeMethods.createElement.call(document, 'link');
+    var integrityValue = 'sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC';
+
+    function checkIntegrityAttr (el, hasCorrectIntegrityAttr) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/node/attributes-test.js]: rename `hasCorrectIntegrityAttr` to `hasIntegrityAttr`.

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest
