### PR TITLE
fix 'Wrong url resolving for page with <base> tag' (close #371)

### LINKED ISSUE #371: Wrong url resolving for page with <base> tag
http://66.55.147.18:13500/history?timestamp=1453575754575&siteUrl=http://www.alibaba.com/

Test for reproduction:

```javascript
test('Maximum call stack size exceeded', function () {
    var baseEl = document.createElement('base');

    baseEl.href = 'http://localhost:1337/sessionId/http://test.example.com';
    document.head.appendChild(baseEl);

    strictEqual(urlUtils.getProxyUrl('{{inquiry.imgSrc}}-->'), // <-- Maximum call stack size exceeded
        'http://localhost:1337/sessionId/http://test.example.com/%7B%7Binquiry.imgSrc%7D%7D--%3E');

    document.head.removeChild(baseEl);
});
```

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @inikulin @churkin

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/index.js [hunk 1]
```diff
@@ -18,6 +18,8 @@ import XhrSandbox from './xhr';
 import StorageSandbox from './storages';
 import { isIE, isWebKit } from '../utils/browser';
 import { create as createSandboxBackup, get as getSandboxBackup } from './backup';
+import { get } from '../utils/destination-location';
```
Comment (inikulin) [inline src/client/sandbox/index.js]: You shouldn't export single method, since it's lacks context completely. Export `destinationLocation` as a whole

File: src/client/utils/url-resolver.js [hunk 2]
```diff
@@ -0,0 +1,59 @@
+import nativeMethods from '../sandbox/native-methods';
+import { ensureTrailingSlash } from '../../utils/url';
+import { get } from '../utils/destination-location';
+
+const DOCUMENT_URL_RESOLVER = 'hammerhead|document-url-resolver';
+
+function createResolver (doc) {
```
Comment (inikulin) [inline src/client/utils/url-resolver.js]: This module should be an object and not the set of the utility methods. Since now it's single entity - `urlResolver`

File: src/client/utils/url-resolver.js [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+
+    return htmlDocument;
+}
+
+function getResolver (doc) {
+    // NOTE: IE cleans the document up after document.open is called.
+    if (!doc[DOCUMENT_URL_RESOLVER])
+        doc[DOCUMENT_URL_RESOLVER] = createResolver(doc);
+
+    return doc[DOCUMENT_URL_RESOLVER];
```
Comment (inikulin) [inline src/client/utils/url-resolver.js]: I forgot, why we need to always get it from the document? Why we can't store it in the var?

**Comment by inikulin** [comment]
\r-

File: src/client/utils/url-resolver.js (hunk 3 above)
Comment (miherlosev) [inline src/client/utils/url-resolver.js]: After `document.open` is called the `nativeMethods` will refresh.
If we will try to call `urlResolve.updateBase` after `document.open` 
we will use native method from actual document.
But document that contains `a` element for url resolving created using previous `nativeMethods` version.

Comment (inikulin) [inline src/client/utils/url-resolver.js]: We need a comment that clarifies this behavior in details then. I bet I've already asked about this piece of code and already forgot why we have it.

**Comment by LavrovArtem** [comment]
this pull request fix #20

**Comment by miherlosev** [comment]
wating for #384

**Comment by miherlosev** [comment]
FPR

File: src/client/sandbox/index.js [hunk 4]
```diff
@@ -84,6 +86,10 @@ export default class Sandbox extends SandboxBase {
             this.nativeMethods.refreshWindowMeths(window);
     }
 
+    _initUrlResolver (document) {
```
Comment (churkin) [inline src/client/sandbox/index.js]: static?

Comment (churkin) [inline src/client/sandbox/index.js]: Actually, I think this method should be in the urlResolver

File: src/client/utils/url.js [hunk 5]
```diff
@@ -86,7 +87,7 @@ export function changeDestUrlPart (proxyUrl, prop, value, resourceType) {
     var parsed = sharedUrlUtils.parseProxyUrl(proxyUrl);
 
     if (parsed) {
-        var resolver  = destLocation.getResolver(document);
+        var resolver  = urlResolver.getResolverElement(document);
```
Comment (churkin) [inline src/client/utils/url.js]: I would have moved all associated with the resolver element code in the urlResolver

File: src/client/utils/url-resolver.js [hunk 6]
```diff
@@ -0,0 +1,62 @@
+import nativeMethods from '../sandbox/native-methods';
+import { ensureTrailingSlash } from '../../utils/url';
+
+const DOCUMENT_URL_RESOLVER = 'hammerhead|document-url-resolver';
+
+var urlResolver = {
```
Comment (churkin) [inline src/client/utils/url-resolver.js]: why not use classes?

Comment (miherlosev) [inline src/client/utils/url-resolver.js]: see https://github.com/DevExpress/testcafe-hammerhead/pull/383#discussion-diff-51120556

File: src/client/sandbox/node/element.js [hunk 7]
```diff
@@ -349,12 +350,23 @@ export default class ElementSandbox extends SandboxBase {
 
             if (domUtils.isFileInput(el))
                 this.addFileInputInfo(el);
+
+            else if (domUtils.isBaseElement(el)) {
+                var storedHrefAttrName  = domProcessor.getStoredAttrName('href');
+                var storedHrefAttrValue = el.getAttribute(storedHrefAttrName);
+
+                urlResolver.updateBase(storedHrefAttrValue, this.document);
```
Comment (churkin) [inline src/client/sandbox/node/element.js]: What if I change `href` value through a `setAttribute` method?

Comment (churkin) [inline src/client/sandbox/node/element.js]: Test needed

File: src/client/sandbox/node/element.js [hunk 8]
```diff
@@ -349,12 +350,23 @@ export default class ElementSandbox extends SandboxBase {
...
+            }
+
         }
     }
 
     onElementRemoved (el) {
         if (domUtils.isBodyElement(el))
             this.shadowUI.onBodyElementMutation();
+
+        else if (domUtils.isBaseElement(el))
```
Comment (churkin) [inline src/client/sandbox/node/element.js]: I think we should make `DomMutation` event

File: src/client/utils/url-resolver.js (hunk 6 above)
Comment (churkin) [inline src/client/utils/url-resolver.js]:
```javascript
class UrlResolver {
...
}
export default new UrlResolver();
```
?

**Comment by churkin** [comment]
-\r

File: src/client/sandbox/node/element.js (hunk 7 above)
Comment (miherlosev) [inline src/client/sandbox/node/element.js]: already present - https://github.com/DevExpress/testcafe-hammerhead/pull/383/files#diff-d69a730a5366fcee8825a74b81d833f4R309

File: src/client/sandbox/index.js (hunk 4 above)
Comment (miherlosev) [inline src/client/sandbox/index.js]: Ok

File: src/client/utils/url.js (hunk 5 above)
Comment (miherlosev) [inline src/client/utils/url.js]: Ok

File: src/client/utils/url-resolver.js (hunk 6 above)
Comment (inikulin) [inline src/client/utils/url-resolver.js]: No. This was a bad practice. Since it's a singletone it can be just plain object. No need for class here.

Comment (inikulin) [inline src/client/utils/url-resolver.js]: But it's done wrong here anyway. Just `export default {}`, no need for explicit `var` here. Use `this` to refer object fields

File: src/client/sandbox/node/element.js (hunk 8 above)
Comment (miherlosev) [inline src/client/sandbox/node/element.js]: create the separate issue - https://github.com/DevExpress/testcafe-hammerhead/issues/385

**Comment by miherlosev** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by miherlosev** [comment]
I disagree with @churkin .
We should not move this code to `_overrideSetAttributeCore`.
This method perform only 2 actions: set origin attribute with proxing value and set stored attribute with origin value.
In this sundbox all actions with external submodules are performed like I wrote: 
```javascript
 overridenMethod () {
    sandbox.before();
    var result = nativeMethodCall();
    sanbox.after();    
    return result;
 }
```
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/element.js#L247
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/element.js#L252
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/element.js#L291

For `_overridedRemoveAttributeCore` the same.

**Comment by churkin** [comment]
The `_overridedSetAttributeCore` already contains all attribute checks. What sense make one of them to a higher level?

**Comment by miherlosev** [comment]
So, after discussing with @churkin we decide to move `urlResolver.updateBase` call inside _overridedSetAttributeCore.
Also I added the 5 point in the issue https://github.com/DevExpress/testcafe-hammerhead/issues/385

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm
