### PR TITLE
fix "Location assignment doesn't work" (close #640)

### LINKED ISSUE #640: Location assignment doesn't work
Run in playground:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<input type="button" id="btn">

<script>
    document.querySelector('#btn').addEventListener('click', function () {
        location = 'https://google.com';
    });
</script>
</body>
</html>
```

Clicking `btn` doesn't change location. I'm surprised we didn't encountered it yet. Also, it's worth checking other properties that instrumented the way location does. BTW, replacing `location` with `document.location` or `window.location` works just fine.

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @inikulin 

Also I planned to add functional test in `testcafe` for case with top level window.

### CODE REVIEW

**Comment by inikulin** [comment]
@miherlosev Do we have a test for this case: https://github.com/DevExpress/testcafe-hammerhead/issues/640#issuecomment-228679853

**Comment by inikulin** [comment]
Also, it's odd that WPT tests doesn't show this problem, do they run correctly?

**Comment by miherlosev** [comment]
> Also, it's odd that WPT tests doesn't show this problem, do they run correctly?
We run tests that don't contain location change.
I cloned web platform test repository and search using keywords 'location =', ' location = ', ' location='.
See fixture list https://github.com/DevExpress/hammerhead-health-monitor/blob/master/web-platform/tests_big.json.

**Comment by miherlosev** [comment]
> @miherlosev Do we have a test for this case: #640 (comment)

Create the separate issue https://github.com/DevExpress/testcafe-hammerhead/issues/642

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
ping @churkin @inikulin

File: src/client/sandbox/code-instrumentation/location/index.js [hunk 1]
```diff
@@ -34,11 +37,17 @@ export default class LocationAccessorsInstrumentation extends SandboxBase {
...
         window[INSTRUCTION.setLocation] = (location, value) => {
             if (isLocation(location)) {
-                location = value;
+                var resourceType = null;
 
-                return location;
-            }
+                if (window.self !== window.top) {
+                    value        = destLocation.resolveUrl(value, window.top.document);
+                    resourceType = stringifyResourceType(true);
```
Comment (inikulin) [inline src/client/sandbox/code-instrumentation/location/index.js]: Can we have full form here: `stringifyResourceType(true, false, false)`? Also, it took me a while to figure out what it does. First of all `stringify` suggest that you pass something to be stringified. It more likely `getResourceTypeString`. The second issue it's not clear what arguments mean here. In such cases it's always better to have options object:
`getResourceTypeString({ isIframe: true})`

**Comment by inikulin** [comment]
\r-

File: src/client/sandbox/code-instrumentation/location/index.js (hunk 1 above)
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/location/index.js]: So we need to do the following:
1)rename `stringifyResourceType` to the `getResourceTypeString`
2)move 3 function arguments to the single parameters object

**Comment by miherlosev** [comment]
FPR

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
Error for node 0.10.
```javascript
/home/travis/build/testcafe-build-bot/testcafe-hammerhead/node_modules/eslint-plugin-import/lib/index.js:6

const rules = exports.rules = {

^^^^^
```
Possible reason - https://github.com/DevExpress/testcafe-hammerhead/commit/62eed525fdd3b08ba9def5924dcf6e06fa0020ad

SyntaxError: Failed to load plugin import: Use of const in strict mode.

**Comment by miherlosev** [comment]
FPR

File: src/client/sandbox/code-instrumentation/location/index.js [hunk 2]
```diff
@@ -34,11 +37,17 @@ export default class LocationAccessorsInstrumentation extends SandboxBase {
 
         window[INSTRUCTION.setLocation] = (location, value) => {
             if (isLocation(location)) {
-                location = value;
+                var resourceType = null;
 
-                return location;
-            }
+                if (window.self !== window.top) {
```
Comment (churkin) [inline src/client/sandbox/code-instrumentation/location/index.js]: @LavrovArtem @miherlosev  Guys, we no longer use the `window.self` property, it can be overriden `window.self = {};`, just use `window === window.top` check.

**Comment by churkin** [comment]
-\r

**Comment by miherlosev** [comment]
FPR
ping @inikulin @churkin

File: src/client/sandbox/code-instrumentation/location/index.js (hunk 2 above)
Comment (inikulin) [inline src/client/sandbox/code-instrumentation/location/index.js]: BTW, it would be nice to have eslint rule for this. @LavrovArtem can you take care of this, please?

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Comment by churkin** [comment]
rebase pls.

**Comment by miherlosev** [comment]
Done.
FPR

**Comment by miherlosev** [comment]
ping @churkin
