### PR TITLE
fix `Override WebSocket class` (close #911)

### LINKED ISSUE #911: Override WebSocket class
Request for socket opening sends the 'cookie' header with `document.cookie` value, but we don't write cookie in `document.cookie`, we save cookie in hammehread's settings.

https://testcafe-discuss.devexpress.com/t/set-cookies-on-client-side/65/6

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
http://www.websocket.org/echo.html

**Comment by AlexanderMoskovkin** [comment]
> http://www.websocket.org/echo.html
Also need to check this PR on websocket demos

@LavrovArtem Have you done this?

File: test/client/fixtures/sandbox/node/classes-test.js [hunk 1]
```diff
@@ -178,6 +181,79 @@ if (window.MutationObserver) {
...
+
+    test('checking parameters', function () {
+        var nativeWebSocket = nativeMethods.WebSocket;
+        var originHeader    = encodeURIComponent(destLocation.getOriginHeader());
+
+        nativeMethods.WebSocket = function (url) {
+            strictEqual(url, 'ws://' + location.host + '/sessionId!w!' + originHeader + '/http://localhost/socket');
+        };
+
+        /* eslint-disable no-new */
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/node/classes-test.js]: Apply eslint disable rule to a whole page

File: test/client/fixtures/sandbox/node/classes-test.js [hunk 2]
```diff
@@ -178,6 +181,79 @@ if (window.MutationObserver) {
...
+        var socket = new WebSocket('ws://' + location.host);
+
+        ok(socket instanceof WebSocket);
+
+        strictEqual(WebSocket.CONNECTING, socket.CONNECTING);
+        strictEqual(WebSocket.OPEN, socket.OPEN);
+        strictEqual(WebSocket.CLOSING, socket.CLOSING);
+        strictEqual(WebSocket.CLOSED, socket.CLOSED);
+
+        socket.close();
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/node/classes-test.js]: Add checking for the second parameter of constructor

File: src/client/sandbox/node/window.js [hunk 3]
```diff
@@ -420,6 +420,28 @@ export default class WindowSandbox extends SandboxBase {
...
+                    return new nativeMethods.WebSocket();
+
+                const proxyUrl = getProxyUrl(url, { resourceType: stringifyResourceType({ isWebSocket: true }) });
+
+                if (arguments.length === 1)
+                    return new nativeMethods.WebSocket(proxyUrl);
+                else if (arguments.length === 2)
+                    return new nativeMethods.WebSocket(proxyUrl, protocols);
+
+                return new nativeMethods.WebSocket(proxyUrl, protocols, arguments[2]);
```
Comment (miherlosev) [inline src/client/sandbox/node/window.js]: Add test for this case. 
Rewrite as `WebSocket(arguments)` because constructor can be called as `new WebSocket(url, protocols, wrongParam1, wrongParam2, etc)`.

File: src/client/sandbox/node/window.js [hunk 4]
```diff
@@ -420,6 +420,28 @@ export default class WindowSandbox extends SandboxBase {
             };
         }
 
+        if (window.WebSocket) {
+            window.WebSocket = function (url, protocols) {
+                if (arguments.length === 0)
```
Comment (miherlosev) [inline src/client/sandbox/node/window.js]: `WebSocket.url` should be proxied.
I guess you can override property value descriptor here for `window.WebSocket.prototype.url`.

File: src/client/utils/url.js [hunk 5]
```diff
@@ -4,25 +4,30 @@ import * as destLocation from './destination-location';
 import * as urlResolver from './url-resolver';
 import settings from '../settings';
 
-const HASH_RE = /#[\S\s]*$/;
+const HASH_RE                          = /#[\S\s]*$/;
+const SUPPORTED_WEB_SOCKET_PROTOCOL_RE = /^wss?:/i;
```
Comment (miherlosev) [inline src/client/utils/url.js]: Can we have a single regexp for isSupportedProtocol function (src/utils/url.js)?

File: src/request-pipeline/index.js [hunk 6]
```diff
@@ -168,6 +173,37 @@ function sendResponseHeaders (ctx) {
     ctx.res.addTrailers(ctx.destRes.trailers);
 }
 
+function performWebSocketConnection (ctx) {
```
Comment (miherlosev) [inline src/request-pipeline/index.js]: rename to `respondForWebSocket`.

Move `performWebSocketConnection` and `writeWebSocketHead` to the separate file `websocket.js`

File: src/client/utils/url.js (hunk 5 above)
Comment (LavrovArtem) [reply src/client/utils/url.js]: We don't support the web socket url for something other than the WebSocket class(ancor, link, iframe, etc). The server side of proxy should perform connection only for WebSocket class.

Comment (miherlosev) [reply src/client/utils/url.js]: OK

**Comment by LavrovArtem** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
> http://www.websocket.org/echo.html
Also need to check this PR on websocket demos

Have you checked?

**Comment by LavrovArtem** [comment]
@AlexanderMoskovkin yep

File: src/client/sandbox/node/window.js [hunk 7]
```diff
@@ -420,6 +430,56 @@ export default class WindowSandbox extends SandboxBase {
...
+                    return new nativeMethods.WebSocket();
+
+                const proxyUrl = getProxyUrl(url, { resourceType: stringifyResourceType({ isWebSocket: true }) });
+                let socket     = null;
```
Comment (miherlosev) [inline src/client/sandbox/node/window.js]: `let webSocket = `

**Comment by LavrovArtem** [comment]
@miherlosev 
The difference between proxy and without proxy occurs due to next code:
https://github.com/DevExpress/testcafe-hammerhead/blob/98fc917a2be63f4894aaef9314b1a52b99b0661c/src/client/sandbox/node/window.js#L240-L246
We process the blob data because type is missing.

File: src/client/sandbox/node/window.js [hunk 8]
```diff
@@ -420,6 +430,56 @@ export default class WindowSandbox extends SandboxBase {
...
+
+                if (arguments.length === 1)
+                    webSocket = new nativeMethods.WebSocket(proxyUrl);
+                else if (arguments.length === 2)
+                    webSocket = new nativeMethods.WebSocket(proxyUrl, protocols);
+                else
+                    webSocket = new nativeMethods.WebSocket(proxyUrl, protocols, arguments[2]);
+
+                // NOTE: We need to use deprecated methods instead of the defineProperty method in Android 5.1
+                // because the defineProperty does not redefine descriptor
```
Comment (miherlosev) [inline src/client/sandbox/node/window.js]: Add a one more sentence: `Try to drop this after moving to a higher Android version`

File: src/request-pipeline/context.js [hunk 9]
```diff
@@ -244,7 +248,7 @@ export default class RequestPipelineContext {
     closeWithError (statusCode, resBody) {
         this.res.statusCode = statusCode;
 
-        if (resBody && !this.res.headersSent) {
+        if (resBody && !this.res.headersSent && this.res.setHeader) {
```
Comment (miherlosev) [inline src/request-pipeline/context.js]: Test for this change

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/node/window.js [hunk 10]
```diff
@@ -6,9 +6,16 @@ import { processScript } from '../../../processing/script';
...
+    isSubDomain,
+    parseUrl,
+    getProxyUrl,
+    parseProxyUrl,
+    convertToProxyUrl,
+    stringifyResourceType
+} from '../../utils/url';
 import { isFirefox, isIE9, isIE } from '../../utils/browser';
-import { isCrossDomainWindows, isImgElement, isBlob } from '../../utils/dom';
+import { isCrossDomainWindows, isImgElement, isBlob, isWebSocket } from '../../utils/dom';
```
Comment (miherlosev) [inline src/client/sandbox/node/window.js]: Add client tests for `isWebSocket` function

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
FPR

**Comment by miherlosev** [comment]
Before merge we will run health monitor on this PR

**Comment by miherlosev** [comment]
Health Monitor [run](https://testcafe-hhhm.devexpress.com/history?timestamp=1510734580773) finished without errors and performance issues.
@AlexanderMoskovkin review and merge
