### PR TITLE
Dispatched focus/blur events have a correct type (closes #947)

### LINKED ISSUE #947: Wrong dispatched focus event types
It does not pass check instanseof. Focus and blur events should has type `FocusEvent`, but now they have `Event` type 
It connected with https://github.com/DevExpress/testcafe-hammerhead/issues/941

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @churkin @AlexanderMoskovkin

### CODE REVIEW

File: src/client/sandbox/event/simulator.js [hunk 1]
```diff
@@ -538,17 +538,30 @@ export default class EventSimulator {
     }
 
     _dispatchEvent (el, name, shouldBubble, flag) {
-        var ev = null;
+        var event                     = null;
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/simulator.js]: @helen-dikareva Do you like the idea to split this into two functions `_dispatchEvent` and `_dispatchFocusEvent` ? On my opinion it would be better

Comment (helen-dikareva) [inline src/client/sandbox/event/simulator.js]: ok, let's

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by helen-dikareva** [comment]
FPR
