### PR TITLE
fix `Hammerhead is missed after 'document.close' in Firefox` (close #1821)

### LINKED ISSUE #1821: Hammerhead is missed after 'document.close' in Firefox
Test for reproduce
```js
test('test', function () {
    return createTestIframe()
        .then(function (iframe) {
            iframe.contentDocument.open();
            iframe.contentDocument.write('Hello!');
            iframe.contentDocument.close();

            var iframeHammerhead = iframe.contentWindow['%hammerhead%'];
            ok(iframeHammerhead);
        });
});

```

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/1821

### Changes
1. Add `onIframeBeganToRun` in `document.close`.
2. Fix failed Internet Explorer 11 tests (`NetworkError` occurs after some Windows 10 update, `iframe` without `src` case), modify `test/client/data/iframe/simple-iframe.html`.

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: test/client/fixtures/sandbox/xhr-test.js [hunk 1]
```diff
@@ -208,14 +208,36 @@ asyncTest('xhr.responseURL', function () {
...
+
+    function checkIframe (iframe) {
+        var script = document.createElement('script');
+
+        nativeMethods.scriptTextSetter.call(script, '(' + xhrTestFunc.toString() + ')()');
+
+        iframe.contentDocument.body.appendChild(script);
+
+        if (!window.skipIframeCheck)
+            strictEqual(iframe.contentWindow.response, 'https://example.com', iframe.src ? 'iframe with src' : 'iframe without src');
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/xhr-test.js]: Let's use a function argument (e.g. `assertionText`) instead of this condition.

File: test/client/fixtures/sandbox/xhr-test.js [hunk 2]
```diff
@@ -227,18 +249,16 @@ test('send the origin header correctly (GH-284)', function () {
...
-
-            iframe.contentDocument.body.appendChild(script);
-
-            strictEqual(iframe.contentWindow.response, 'https://example.com', 'iframe');
+    return Promise.all([
+        createTestIframe(),
+        createTestIframe({ src: getSameDomainPageUrl('../../data/iframe/simple-iframe.html') })
+    ])
+        .then(function (iframes) {
+            var iframeWithoutSrc = iframes[0];
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/xhr-test.js]: I think that this variable is unnecessary.

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest
