### PR TITLE
fix `LocationWrapper does not process 'javascript:""' urls passed to the 'replace' function` (close #1274)

### LINKED ISSUE #1274: LocationWrapper does not process 'javascript:""' urls passed to the 'replace' function
Site http://www.8684.cn/ , http://www.linternaute.com/

Example for reproducing:
```html
<body>
    <script>
        var iframe = document.createElement('iframe');

        iframe.onload = function () {
            iframe.onload = null;
            iframe.contentWindow.location.replace('javascript:\'<a href="/some">Link</a>\'')
        };
		
        document.body.appendChild(iframe);
    </script>
</body>
```
Also with hammerhead this example throws an error:
`Uncaught TypeError: Cannot read property 'destUrl' of null`

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @miherlosev @churkin

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/code-instrumentation/location/wrapper.js [hunk 1]
```diff
@@ -51,6 +53,9 @@ export default class LocationWrapper extends EventEmitter {
             return ensureTrailingSlash(resolveElement.href, locationUrl);
         };
         const getProxiedHref = href => {
+            if (domProcessor.JAVASCRIPT_PROTOCOL_REG_EX.test(href))
```
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/location/wrapper.js]: Let's move this to the `domProcessor.isJsProtocol (value)` static method and remove `JAVASCRIPT_PROTOCOL_REG_EX` from domProcessor's constructor.

File: src/client/sandbox/code-instrumentation/location/wrapper.js [hunk 2]
```diff
@@ -51,6 +53,9 @@ export default class LocationWrapper extends EventEmitter {
...
+                return DomProcessor.processJsAttrValue(href, true, false);
```
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/location/wrapper.js]: `DomProcessor.processJsAttrValue({ value: href, isJsProtocol: true, isEventAttr: false})`

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 3]
```diff
@@ -421,7 +421,7 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
                         const parentDocument = domUtils.findDocument(parentEl);
                         const parentWindow   = parentDocument ? parentDocument.defaultView : null;
 
-                        el.outerHTML = processHtml('' + value, parentEl.tagName);
+                        el.outerHTML = processHtml({ html: '' + value, parentTag: parentEl.tagName });
```
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Use `String` constructor instead of `'' + value`.
Here and below.

`processHtml({ html: String(value), parentTag: parentEl.tagName })`

File: src/client/sandbox/node/document/index.js [hunk 4]
```diff
@@ -47,8 +47,17 @@ export default class DocumentSandbox extends SandboxBase {
         return result;
     }
 
+    _isNeedToUpdateDocumentWriter (window, document) {
```
Comment (miherlosev) [inline src/client/sandbox/node/document/index.js]: `_needToUpdateDocumentWriter`

File: src/processing/dom/index.js [hunk 5]
```diff
@@ -297,47 +320,16 @@ export default class DomProcessor {
...
     }
 
-    _processJsAttr (el, attr, jsProtocol) {
-        const storedUrlAttr = this.getStoredAttrName(attr);
-        const processed     = this.adapter.hasAttr(el, storedUrlAttr);
-        const attrValue     = this.adapter.getAttr(el, processed ? storedUrlAttr : attr);
-
-        const code    = jsProtocol ? attrValue.replace(JAVASCRIPT_PROTOCOL_REG_EX, '') : attrValue;
-        const matches = code.match(HTML_STRING_REG_EX);
+    _processJsAttr (el, attr, isJsProtocol, isEventAttr) {
```
Comment (miherlosev) [inline src/processing/dom/index.js]: change the method signature as `_processJsAttr ({ el, attr, isJsProtocol, isEventAttr })`

File: src/processing/script/index.js [hunk 6]
```diff
@@ -164,7 +165,7 @@ export function isScriptProcessed (code) {
     return PROCESSED_SCRIPT_RE.test(code);
 }
 
-export function processScript (src, withHeader) {
+export function processScript (src, withHeader, wrapLastExprViaProcessHtml) {
```
Comment (miherlosev) [inline src/processing/script/index.js]: `processScript (src, { withHeader, wrapLastExprViaProcessHtml })`
two parameters: first - `src`, second - processing options

`wrapLastExprViaProcessHtml` -> `wrapLastExprWithProcessHtml`

File: test/client/fixtures/sandbox/event/message-test.js [hunk 7]
```diff
@@ -310,7 +310,7 @@ asyncTest('send message from iframe with "about:blank" src (GH-1026)', function
 asyncTest('service messages from embedded iframe (GH-803)', function () {
     var iframe = document.createElement('iframe');
 
-    iframe.id = 'test-' + Date.now;
+    iframe.id = 'test-' + Date.now();
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/event/message-test.js]: Can we rewrite this with `createTestIframe` function?

File: src/processing/script/index.js (hunk 6 above)
Comment (LavrovArtem) [reply src/processing/script/index.js]: The `processScript` function is used in testcafe.

Comment (miherlosev) [reply src/processing/script/index.js]: Ok. Don't change this. It is used in `testcafe-legacy-api` too

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
**Initially**, we process two cases of a `javascript:` protocol url:
* process like `html` if string follows after protocol (`javascript: "some html"`)
* else process like `js`

**Currently**, we process everything like `js` and  cover last expression to the `__proc$Html` function call. For example:
* `javascript: "some html"` -> `javascript: __proc$Html(window, "some html")`
* `javascript: "a = 5; generateHtml();"` -> `javascript: a = 5; __proc$Html(window, generateHtml());`

Also javascript url processing adds to location wrapper code.

Other changes:
* `getStoredAttrName` -> `static getStoredAttrName`
* `processHtml (html, parentTag, prepareDom)` -> `processHtml (html, { parentTag, prepareDom, processedContext } = {})`
* `_processJsAttr (el, attr, jsProtocol)` -> `_processJsAttr (el, attrName, { isJsProtocol, isEventAttr })`

**Comment by LavrovArtem** [comment]
ping @miherlosev @churkin
