### PR TITLE
fix `The onreadystatechange property of XMLHttpRequest.prototype redefined by Angular` (close #1283)

### LINKED ISSUE #1283: The onreadystatechange property of XMLHttpRequest.prototype redefined by Angular
The error occurs with Hammerhead:
`RangeError: Maximum call stack size exceeded`

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @miherlosev @churkin @AlexanderMoskovkin

### CODE REVIEW

File: src/client/sandbox/xhr.js [hunk 1]
```diff
@@ -103,55 +124,24 @@ export default class XhrSandbox extends SandboxBase {
...
             // Access-Control_Allow_Origin flag and skip "preflight" requests.
-            nativeMethods.xhrSetRequestHeader.call(this, XHR_HEADERS.requestMarker, 'true');
-
-            nativeMethods.xhrSetRequestHeader.call(this, XHR_HEADERS.origin, getOriginHeader());
+            nativeMethods.xhrSetRequestHeader.call(xhr, XHR_HEADERS.requestMarker, 'true');
+            nativeMethods.xhrSetRequestHeader.call(xhr, XHR_HEADERS.origin, getOriginHeader());
 
             if (xhrSandbox.corsSupported)
-                nativeMethods.xhrSetRequestHeader.call(this, XHR_HEADERS.corsSupported, 'true');
+                nativeMethods.xhrSetRequestHeader.call(xhr, XHR_HEADERS.corsSupported, 'true');
```
Comment (miherlosev) [inline src/client/sandbox/xhr.js]: We don't need the additional variable `xhr`.
Another methods (`abort`, `open`) don't declare an additional variable.
So, drop `const xhr = this;` line and change `xhr` to `this` for places in `send` method.

File: test/client/fixtures/sandbox/xhr-test.js [hunk 2]
```diff
@@ -201,3 +205,26 @@ asyncTest('authorization headers by client should be processed (GH-1016)', funct
...
+    var timeout  = null;
+    var testDone = function (eventObj) {
+        clearTimeout(timeout);
+        ok(!!eventObj);
+        start();
+    };
+
+    var readyStateChangeHandler = function (e) {
+        if (this.readyState === this.DONE)
+            e.stopImmediatePropagation();
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/xhr-test.js]: add `ok(false, 'outer handler is called before XHR_COMPLETED_EVENT');`

Comment (LavrovArtem) [reply test/client/fixtures/sandbox/xhr-test.js]: this handler will be called in all cases

File: src/client/sandbox/xhr.js [hunk 3]
```diff
@@ -54,8 +54,16 @@ export default class XhrSandbox extends SandboxBase {
     attach (window) {
         super.attach(window);
 
-        const xhrSandbox          = this;
-        const xmlHttpRequestProto = window.XMLHttpRequest.prototype;
+        const xhrSandbox           = this;
+        const xmlHttpRequestProto  = window.XMLHttpRequest.prototype;
+        const xhrConstructorString = nativeMethods.XMLHttpRequest.toString();
```
[the remark this answers is not in the document]
Comment (LavrovArtem) [reply src/client/sandbox/xhr.js]: but it is string, it is not a function

File: test/client/fixtures/sandbox/xhr-test.js (hunk 2 above)
Comment (miherlosev) [reply test/client/fixtures/sandbox/xhr-test.js]: Ok

File: src/client/sandbox/xhr.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (miherlosev) [reply src/client/sandbox/xhr.js]: Ok. Don't move it. But rename.

[the remark this answers is not in the document]
Comment (LavrovArtem) [reply src/client/sandbox/xhr.js]: `xmlHttpRequestString` ?

[the remark this answers is not in the document]
Comment (miherlosev) [reply src/client/sandbox/xhr.js]: xmlHttpRequestToString

[the remark this answers is not in the document]
Comment (LavrovArtem) [reply src/client/sandbox/xhr.js]: sounds like a function

[the remark this answers is not in the document]
Comment (miherlosev) [reply src/client/sandbox/xhr.js]: Maybe.
You can use any notation.
`xmlHttpRequestString` of `xmlHttpRequestToString`
We already using `ToString` notation: 
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/window.js#L18

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/xhr.js [hunk 4]
```diff
@@ -73,6 +81,38 @@ export default class XhrSandbox extends SandboxBase {
...
+        window.XMLHttpRequest           = xmlHttpRequestWrapper;
+        xmlHttpRequestWrapper.prototype = xmlHttpRequestProto;
+        xmlHttpRequestWrapper.toString  = () => xmlHttpRequestToString;
+
+        // NOTE: We cannot just assign constructor property in OS X 10.11 safari 9.0
+        nativeMethods.objectDefineProperty.call(window.Object, xmlHttpRequestProto, 'constructor', {
+            value: xmlHttpRequestWrapper
+        });
+
+        const defineConstructorConst = (name, value) => {
```
Comment (miherlosev) [inline src/client/sandbox/xhr.js]: `defineProperty(obj, name, value)`

File: src/client/sandbox/xhr.js [hunk 5]
```diff
@@ -73,6 +81,38 @@ export default class XhrSandbox extends SandboxBase {
...
+            nativeMethods.objectDefineProperty.call(window.Object, xmlHttpRequestWrapper, name, {
+                value,
+
+                enumerable: true
+            });
+        };
+
+        defineConstructorConst('UNSENT', 0);
```
Comment (miherlosev) [inline src/client/sandbox/xhr.js]: `defineProperty(xmlHttpRequestWrapper, 'UNSENT', XMLHttpRequest.UNSENT)`
and etc.

I propose this variant because it is more readable.

Also XMLHttpRequest has another static properties such as `name`, `valueOf` and etc.
But I think we can skip it.

File: test/client/fixtures/sandbox/xhr-test.js [hunk 6]
```diff
@@ -69,10 +73,23 @@ test('createNativeXHR', function () {
     }
 });
 
+test('constructor', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/xhr-test.js]: `toString, instanceof, constructor and static properties`
or simple `properties`

File: src/client/sandbox/xhr.js [hunk 7]
```diff
@@ -90,6 +90,13 @@ export default class XhrSandbox extends SandboxBase {
             return xhr;
         };
 
+        for (const prop of ['UNSENT', 'OPENED', 'HEADERS_RECEIVED', 'LOADING', 'DONE']) {
```
Comment (miherlosev) [inline src/client/sandbox/xhr.js]: Store as `const  XML_HTTP_REQUEST_READY_STATES = ['UNSENT', 'OPENED', 'HEADERS_RECEIVED', 'LOADING', 'DONE']`

File: src/client/sandbox/xhr.js [hunk 8]
```diff
@@ -73,6 +81,31 @@ export default class XhrSandbox extends SandboxBase {
...
+        const xmlHttpRequestWrapper = function () {
+            const xhr = new nativeMethods.XMLHttpRequest();
+
+            nativeMethods.xhrAddEventListener.call(xhr, 'readystatechange', emitXhrCompletedEvent);
+            nativeMethods.xhrAddEventListener.call(xhr, 'readystatechange', syncCookieWithClient);
+
+            return xhr;
+        };
+
+        for (const prop of ['UNSENT', 'OPENED', 'HEADERS_RECEIVED', 'LOADING', 'DONE']) {
```
Comment (miherlosev) [inline src/client/sandbox/xhr.js]: Store as `const XHR_READY_STATES = ['UNSENT', 'OPENED', 'HEADERS_RECEIVED', 'LOADING', 'DONE']

 and rewrite as

`for (const readyState of XML_HTTP_REQUEST_READY_STATES)...`

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

File: test/client/fixtures/sandbox/xhr-test.js [hunk 9]
```diff
@@ -201,3 +218,27 @@ asyncTest('authorization headers by client should be processed (GH-1016)', funct
     });
     xhr.send();
 });
+
+asyncTest('"XHR_COMPLETED_EVENT" for completed requests should be raised before calling outer handlers (GH-1283)', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/xhr-test.js]: `'XHR_COMPLETED_EVENT' should be raised when xhr is prevented`

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest
