### PR TITLE
fix `Iframe init script `INIT_SCRIPT_FOR_IFRAME_TEMPLATE` isn't executing in IE11` (close #871)

### LINKED ISSUE #871: Iframe init script `INIT_SCRIPT_FOR_IFRAME_TEMPLATE` isn't executing in IE11
Iframe init script `INIT_SCRIPT_FOR_IFRAME_TEMPLATE` isn't executing (and removing then), but appends to body and head in IE11. As result - we have extra node.
[Internal link](http://172.22.7.46:8080/RegressionTestsSite/ASPxSpreadsheet/Initial/Blank.aspx) to reproduce. 
Hint: the iframe is created [here](http://screencast.com/t/198oxHjzmm) and changed [here](http://screencast.com/t/d41fkxu1LkSP)

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

File: src/client/sandbox/node/document/index.js [hunk 1]
```diff
@@ -92,6 +93,15 @@ export default class DocumentSandbox extends SandboxBase {
             if (isIE && !IframeSandbox.isWindowInited(window))
                 nativeMethods.restoreDocumentMeths(document);
 
+            // NOTE: IE doesn't run scripts in iframe if iframe.documentContent.designMode equals on (GH-871)
+            if (document.designMode === 'on') {
```
Comment (churkin) [inline src/client/sandbox/node/document/index.js]: What about `On` or `ON` ?

File: src/client/sandbox/node/document/index.js [hunk 2]
```diff
@@ -92,6 +93,15 @@ export default class DocumentSandbox extends SandboxBase {
...
+                var selfRemovingScripts = nativeMethods.querySelectorAll.call(document,
+                    '.' + SHADOW_UI_CLASSNAME.selfRemovingScript);
+
+                for (var i = 0; i < selfRemovingScripts.length; i++)
+                    nativeMethods.removeChild.call(selfRemovingScripts[i].parentNode, selfRemovingScripts[i]);
+            }
```
Comment (churkin) [inline src/client/sandbox/node/document/index.js]: I propose to move this code to `shadowUI` sandbox

**Comment by LavrovArtem** [comment]
FPR
