### PR TITLE
fix ''Invalid calling object' error appears in IE11 when active element is changed' (close #768). Bump version

### LINKED ISSUE #768: 'Invalid calling object' error appears in IE11 when active element is changed
To reproduce:
1. Open via playground [internal page](http://builder03/Demos-15.2/ASPxGridViewDemos/UserControls/FullScreenViewer.aspx?url=/Demos-15.2/ASPxGridViewDemos/Adaptivity/AdaptiveLayoutWithFormLayoutPage.aspx&width=768&height=576)
2. Take any column header from second line and drop it to first line.

Hammerhead will throw the 'Invalid calling object' error, which leads to `activeElement` isn't dom element here:

### PR DESCRIPTION
**Pull request by miherlosev**
@AlexanderMoskovkin @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

File: test/client/fixtures/sandbox/event/focus-blur-change-test.js [hunk 1]
```diff
@@ -1042,3 +1042,26 @@ asyncTest('focus() must not raise the event if the element is in an invisible if
 
     document.body.appendChild(iframe);
 });
+
+test('should correctly handle the case when document.activeElement is null or an empty object (GH-768)', function () {
```
Comment (AlexanderMoskovkin) [inline test/client/fixtures/sandbox/event/focus-blur-change-test.js]: I've tried to run this test locally in IE11 without your changes in src/client/sandbox/event/focus-blur.js and it's ok. Please ensure that this test is failed without your fix.

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
No need retest. I am performing an additional investigation

**Comment by miherlosev** [comment]
FPR

File: src/client/sandbox/event/focus-blur.js [hunk 2]
```diff
@@ -181,7 +181,13 @@ export default class FocusBlurSandbox extends SandboxBase {
         this.activeWindowTracker.attach(window);
         this.topWindow = domUtils.isCrossDomainWindows(window, window.top) ? window : window.top;
 
-        this.listeners.addInternalEventListener(window, ['focus', 'blur'], () => this._onChangeActiveElement(this.document.activeElement));
+        this.listeners.addInternalEventListener(window, ['focus', 'blur'], () => {
+            // NOTE: Sometimes document.activeElement returns an empty object or null (IE11).
+            // https://github.com/DevExpress/testcafe-hammerhead/issues/768
```
Comment (AlexanderMoskovkin) [inline src/client/sandbox/event/focus-blur.js]: Let's move this comment to `domUtils.getActiveElement` function. And I suppose we should use `domUtils.getActiveElement(document)` instead of `document.getActiveElement` everywhere

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
FPR

**Comment by LavrovArtem** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm
