### PR TITLE
Prevented the opening of the inputs' native dialogs (close #1984)

### LINKED ISSUE #1984: TestCafe should not show the upload dialog in Firefox after a simulated click
Related to: https://www.devexpress.com/Support/Center/Question/Details/T722723/in-firefox-only-when-uploading-file-the-file-upload-system-dialog-stays-open

### What is your Test Scenario?
Upload a file.
 
### What is the Current behavior?
If I add a `click` action which targets an upload element, it will open the upload dialog in Firefox, that won't be closed until the browser is terminated.
  
### What is the Expected behavior?
`t.click` should not open upload dialogs in Firefox.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): https://angular-file-upload.appspot.com/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture `TestMe`
    .page `https://angular-file-upload.appspot.com/`;

test('New Test', async t => {
    await t
        .typeText(Selector('[name="myForm"].ng-pristine.ng-invalid.ng-invalid-required').find('[name="userName"]'), 'TestMe')
        .click(Selector('[name="myForm"].ng-dirty.ng-valid.ng-valid-required').find('[name="file"]'))
        .setFilesToUpload(Selector('[name="myForm"].ng-dirty.ng-valid.ng-valid-required').find('[name="file"]'), ['C:\\Users\\belym.andrey\\TestCafeStudio\\Examples\\_uploads_\\IE 1.png'])
        .click(Selector('button').withText('Submit'))
        .expect(Selector('#editArea').find('span').withText('Upload Successful').exists).eql(true);
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1.Run the attached test in Firefox
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    any
* command-line arguments:  n/a
* browser name and version: Firefox 65
* platform and version:          any

### PR DESCRIPTION
**Pull request by miherlosev**

### CODE REVIEW

**Comment by miherlosev** [comment]
FPR

File: src/client/sandbox/event/index.ts [hunk 1]
```diff
@@ -139,32 +148,47 @@ export default class EventSandbox extends SandboxBase {
...
+        }
 
         this.initDocumentListening(window.document);
-
         this.listeners.initElementListening(window, DOM_EVENTS.concat(['load', 'beforeunload', 'pagehide', 'unload', 'message']));
-
         this.listeners.addInternalEventListener(window, ['focus'], this.onFocus);
         this.listeners.addInternalEventListener(window, ['focus', 'blur', 'change', 'focusin', 'focusout'], this.cancelInternalEvents);
 
+        preventInputNativeDialogs(window, this.listeners);
```
Comment (LavrovArtem) [inline src/client/sandbox/event/index.ts]: I think that we don't need to move this code to the separate file.
