### PR TITLE
fix 'Page without slash after location's host reloads if we set only hash' (close #1426)

### LINKED ISSUE #1426: Page without slash after location's host reloads if we set only hash
see https://github.com/DevExpress/testcafe/issues/2005

### PR DESCRIPTION
**Pull request by Farfurix**
Reference: https://github.com/DevExpress/testcafe/issues/2005

Example test is passed (https://github.com/DevExpress/testcafe/issues/2005)

Todo:
- [x] ensureOriginTrailingSlash test (test/client/fixtures/utils/url-test.js)
- [x] location header test (test/server/proxy-test.js)
- [x] openSession test
- [x] navigateTo test
- [x] getProxiedHref (href.set(), assign() and replace())
- [x] investigate a necessary of ensureTrailingSlash function

### CODE REVIEW

File: src/client/index.js [hunk 1]
```diff
@@ -197,10 +197,12 @@ class Hammerhead {
             destLocation = parsedProxyUrl && parsedProxyUrl.destUrl;
         }
 
-        if (destLocation === 'about:blank' && isRelativeUrl(url))
+        if (isSpecialPage(destLocation) && isRelativeUrl(url))
             return;
 
-        this.win.location = urlUtils.getProxyUrl(url);
+        const proxyUrl = urlUtils.getProxyUrl(ensureHostEndedTrailingSlash(url));
```
Comment (miherlosev) [inline src/client/index.js]: 1)Rewrite in two lines of code:
```js
url = ensureHostEndedTrailingSlash(url);

const proxyUrl = urlUtils.getProxyUrl(url);
```
2)Host, port and protocol is named as 'origin'. See https://developer.mozilla.org/ru/docs/Web/API/Location.
So, let's rename function to `ensureOriginTrailingSlash(url)`.
Add this comment in function body
```js
If you request an url containing only port, host and protocol
then browser adds the trailing slash itself.
```

Comment (Farfurix) [reply src/client/index.js]: Done. May be add window.location.href in comment?

    // NOTE: If you request an url containing only port, host and protocol
    // then browser adds the trailing slash to window.location.href.

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 2]
```diff
@@ -10,6 +10,27 @@ var Promise       = hammerhead.Promise;
...
+    'https://example.com',
+    'http://localhost',
+    'https://localhost',
+    'http://localhost:8080',
+    'https://localhost:8080',
+    'http://127.0.0.1',
+    'https://127.0.0.1',
+    'http://127.0.0.1:8080',
+    'https://127.0.0.1:8080'
+];
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: Let's reduce testcases and combine them to the single contant:
```js
var testcases = [
     {
       url: 'http://example.com'     /*protocol + host*/
       shoudAddTrailingSlash: true
      }, 
      {
         url: https://localhost:8080 /*protocol + host + port*/,
         shoudAddTrailingSlash: true
      },
      {  
         url: about:blank  /*special page*/,
         shoudAddTrailingSlash: false
      }, 
      {
       url: http://example.com/page.html, /*url with path*/
         shoudAddTrailingSlash: false      
      },
     linux file protocol url,
    window file protocol url
];
```

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 3]
```diff
@@ -157,6 +178,54 @@ test('special pages (GH-339)', function () {
...
+            destLocation.forceLocation(urlUtils.getProxyUrl(url));
+
+            var windowMock = {
+                location: {},
+                document: document
+            };
+
+            var locationWrapper = new LocationWrapper(windowMock);
+
+            strictEqual(locationWrapper.href, url + (trailingSlashIsNeeded ? '/' : ''));
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: It's a wrong test because we add a trailing slash on `href` property setter.

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 4]
```diff
@@ -157,6 +178,54 @@ test('special pages (GH-339)', function () {
...
+        return {
+            navigateToUrl: navigateTo,
+
+            win: {
+                location: ''
+            },
+        };
+    };
+
+    var windowMock = getWindowMock();
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: Bad test algorithm.
`window` does not contain the `navigateTo` method.
Rewrite as:
```js
var storedWindow = hammerhead.win;

hammerhead.win = windowMock;

test action with hammerhead.navigateTo()

restore hammerhead.win = storedWindow;
```

File: test/client/fixtures/utils/url-test.js [hunk 5]
```diff
@@ -105,6 +105,41 @@ test('isRelativeUrl', function () {
     ok(sharedUrlUtils.isRelativeUrl('C:\\index.htm'));
 });
 
+test('ensureOriginTrailingSlash', function () {
+    const SHOULD_ADD_TRAILING_SLASH = [
```
Comment (miherlosev) [inline test/client/fixtures/utils/url-test.js]: Use testcases from the comment above.

File: test/server/proxy-test.js [hunk 6]
```diff
@@ -296,6 +296,13 @@ describe('Proxy', () => {
                 .end();
         });
 
+        app.get('/location-header-with-trailing-slash/:url', (req, res) => {
```
Comment (miherlosev) [inline test/server/proxy-test.js]: Don't dublicate routes without necessary.
See https://github.com/DevExpress/testcafe-hammerhead/blob/8b633956eaa7c872cb1d8a49cdd00ff4664bfa96/test/server/proxy-test.js#L292

File: test/server/proxy-test.js [hunk 7]
```diff
@@ -2606,5 +2622,49 @@ describe('Proxy', () => {
...
+                return request(options)
+                    .then(res => {
+                        const parsedUrl = urlUtils.parseProxyUrl(res.headers['location']);
+
+                        expect(parsedUrl.destUrl).eql(redirectLocation + (trailingSlashIsNeeded ? '/' : ''));
+                    });
+            }
+
+            return Promise.all([
+                testRedirectRequest('http://example.com', true),
```
Comment (miherlosev) [inline test/server/proxy-test.js]: Reduce testcases count according the comment above.

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js (hunk 3 above)
Comment (Farfurix) [reply test/client/fixtures/sandbox/code-instrumentation/location-test.js]: Done, new test: 'should add the trailing slash to location.href using href.set(), assign() and replace() functions if url consist of origin (GH-1426)'

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js (hunk 2 above)
Comment (Farfurix) [reply test/client/fixtures/sandbox/code-instrumentation/location-test.js]: Done.

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js (hunk 4 above)
Comment (Farfurix) [reply test/client/fixtures/sandbox/code-instrumentation/location-test.js]: Done.

File: test/client/fixtures/utils/url-test.js (hunk 5 above)
Comment (Farfurix) [reply test/client/fixtures/utils/url-test.js]: Done.

File: test/server/proxy-test.js (hunk 6 above)
Comment (Farfurix) [reply test/server/proxy-test.js]: Done.

File: test/server/proxy-test.js (hunk 7 above)
Comment (Farfurix) [reply test/server/proxy-test.js]: Done.

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 8]
```diff
@@ -157,6 +192,83 @@ test('special pages (GH-339)', function () {
     destLocation.forceLocation(storedForcedLocation);
 });
 
+test('should add the trailing slash to location.href using href.set(), assign() and replace() functions if url consist of origin (GH-1426)', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: `should ensure a trailing slash on page navigation using href setter, assign and replace methods (GH-1426)`

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 9]
```diff
@@ -157,6 +192,83 @@ test('special pages (GH-339)', function () {
...
+    var setHref = function (url) {
+        this.href = url;
+    };
+
+    function proxyUrl (url) {
+        urlUtils.getProxyUrl(url);
+    }
+
+    function proxyUrlTrailingSlash (urlCase) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: `function getExpectedProxyUrl(testCase)`

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 10]
```diff
@@ -157,6 +192,83 @@ test('special pages (GH-339)', function () {
...
+        return proxiedUrl + (urlCase.shoudAddTrailingSlash ? '/' : '');
+    }
+
+    var windowMock = {
+        location: {
+            href:     '',
+            replace:  setHref,
+            assign:   setHref,
+            toString: function () {
+                return proxyUrl(this.location.href);
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: use inplace declaration `urlUtils.getProxyUrl(url)`

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 11]
```diff
@@ -157,6 +192,83 @@ test('special pages (GH-339)', function () {
...
+    function proxyUrlTrailingSlash (urlCase) {
+        var proxiedUrl = urlUtils.getProxyUrl(urlCase.url);
+
+        return proxiedUrl + (urlCase.shoudAddTrailingSlash ? '/' : '');
+    }
+
+    var windowMock = {
+        location: {
+            href:     '',
+            replace:  setHref,
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: use inplace declaration `this.href = url;` in two places

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 12]
```diff
@@ -11,6 +11,41 @@ var nativeMethods = hammerhead.nativeMethods;
 var browserUtils  = hammerhead.utils.browser;
 var domUtils      = hammerhead.utils.dom;
 
+var URL_TEST_CASES = [
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: var ENSURE_URL_TRAILING_SLASH_TEST_CASES = ...

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 13]
```diff
@@ -157,6 +192,83 @@ test('special pages (GH-339)', function () {
...
+
+            locationWrapper.assign(urlCase.url);
+            strictEqual(windowMock.location.href, proxyUrlTrailingSlash(urlCase));
+        });
+    }
+
+    checkTrailingSlash(URL_TEST_CASES);
+});
+
+test('should add the trailing slash to location when navigateTo() is called (GH-1426)', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: should ensure a trailing slash on page navigation using `hammerhead.navigateTo` method (GH-1426)

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 14]
```diff
@@ -157,6 +192,83 @@ test('special pages (GH-339)', function () {
...
+    var storedWindow = hammerhead.win;
+
+    function proxyUrlTrailingSlash (urlCase) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: Rename according the comment above.

Comment (miherlosev) [reply test/client/fixtures/sandbox/code-instrumentation/location-test.js]: Also need to investigate a necessary of `ensureTrailingSlash` function. As I understand, we can remove it in this PR.

File: src/utils/url.js [hunk 15]
```diff
@@ -369,3 +370,14 @@ export function isValidUrl (url) {
 
     return parsedUrl.protocol === 'file:' || parsedUrl.hostname && (!parsedUrl.port || isValidPort(parsedUrl.port));
 }
+
+export function ensureOriginTrailingSlash (url) {
+    // NOTE: If you request an url containing only port, host and protocol
+    // then browser adds the trailing slash to window.location.href.
```
Comment (miherlosev) [inline src/utils/url.js]: Change
`...then browser adds the trailing slash to window.location.href`.
to 
`...then browser adds the trailing slash itself`

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 16]
```diff
@@ -157,6 +192,82 @@ test('special pages (GH-339)', function () {
...
+                return urlUtils.getProxyUrl(this.location.href);
+            }
+        }
+    };
+
+    windowMock.top = windowMock;
+
+    var locationWrapper = new LocationWrapper(windowMock);
+
+    function checkTrailingSlash (testCases) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: `function testAddingTrailingSlash (testCases) {`
here and below

File: test/client/fixtures/sandbox/code-instrumentation/location-test.js [hunk 17]
```diff
@@ -157,6 +192,82 @@ test('special pages (GH-339)', function () {
...
+        return proxiedUrl + (testCase.shoudAddTrailingSlash ? '/' : '');
+    }
+
+    var getWindowMock = function () {
+        return {
+            location: ''
+        };
+    };
+
+    var windowMock = getWindowMock();
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/location-test.js]: `getWindowMock` function is necessary.
Rewrite as 
```js
var windowMock = {
    location: '';
};
```

File: test/client/fixtures/utils/url-test.js [hunk 18]
```diff
@@ -105,6 +105,53 @@ test('isRelativeUrl', function () {
     ok(sharedUrlUtils.isRelativeUrl('C:\\index.htm'));
 });
 
+test('ensureOriginTrailingSlash', function () {
```
Comment (miherlosev) [inline test/client/fixtures/utils/url-test.js]: Let's remove this test.

File: test/server/proxy-test.js [hunk 19]
```diff
@@ -2606,5 +2664,43 @@ describe('Proxy', () => {
...
+                    simple:                  false,
+                };
+
+                return request(options)
+                    .then(res => {
+                        expect(res.headers['location']).eql(getExpectedProxyUrl(proxiedCase));
+                    });
+            };
+
+            return Promise.all(proxyUrls.map(testPageRequest));
```
Comment (miherlosev) [inline test/server/proxy-test.js]: Rename `testPageRequest` to `testLocationHeaderValue`.

Combine `proxyUrls` with `testPageRequest`.

Returned Promise should looks like `return Promise.all(ENSURE_URL_TRAILING_SLASH_TEST_CASES.map(testLocationHeaderValue))`

**Comment by miherlosev** [comment]
@LavrovArtem review too
