### PR TITLE
fix 'HH opens new window if the form target attribute points to a nonexistent window name' (close #247)

### LINKED ISSUE #247: HH opens new window if the form target attribute points to a nonexistent window name

### PR DESCRIPTION
**Pull request by miherlosev**
After discussion with @churkin we decide to implement the partial fix:
If `element.target` contains non-existing window name then we set to target `_self` value.
Now, we don't update existing element's url after changing set of the avalible window names.
Because it may cause perfomance problem - we need to update all `form.action` and `a.href` attribute values for all windows in the page.

### CODE REVIEW

**Comment by miherlosev** [comment]
ping @churkin @LavrovArtem

File: src/client/sandbox/node/element.js [hunk 1]
```diff
@@ -29,6 +30,10 @@ export default class ElementSandbox extends SandboxBase {
         this.BEFORE_FORM_SUBMIT = 'hammerhead|event|before-form-submit';
     }
 
+    static _isNamedTarget (value) {
+        return value[0] !== '_';
+    }
```
Comment (churkin) [inline src/client/sandbox/node/element.js]: Is '_' can not be in the middle of target?

**Comment by churkin** [comment]
-\r

File: src/client/sandbox/node/element.js (hunk 1 above)
Comment (miherlosev) [inline src/client/sandbox/node/element.js]: `_isNamedTarget` is a unclear function name.
It checks that target is not in reserved words - `_self`, `_parent`, `_top`.
Maybe rename it to `_isBuildInTarget` or `_isReservedTarget`.
@churkin What do you think?

**Comment by miherlosev** [comment]
FPR

File: src/client/sandbox/node/element.js [hunk 2]
```diff
@@ -27,6 +28,12 @@ export default class ElementSandbox extends SandboxBase {
         this.overridedMethods = null;
 
         this.BEFORE_FORM_SUBMIT = 'hammerhead|event|before-form-submit';
+
+        this.keywordTargets = ['_blank', '_self', '_parent', '_top'];
+    }
+
+    _isKeywordTarget (value) {
+        return this.keywordTargets.indexOf(value) !== -1;
```
Comment (churkin) [inline src/client/sandbox/node/element.js]: Is keyword target case sensitivity?

File: src/client/sandbox/node/element.js [hunk 3]
```diff
@@ -27,6 +28,12 @@ export default class ElementSandbox extends SandboxBase {
         this.overridedMethods = null;
 
         this.BEFORE_FORM_SUBMIT = 'hammerhead|event|before-form-submit';
+
+        this.keywordTargets = ['_blank', '_self', '_parent', '_top'];
```
Comment (churkin) [inline src/client/sandbox/node/element.js]: Make KEYWORD_TARGETS const

```javascript
const KEYWORD_TARGETS = ['_blank', '_self', '_parent', '_top'];
```

File: src/client/sandbox/node/element.js (hunk 2 above)
Comment (miherlosev) [inline src/client/sandbox/node/element.js]: No. Keyword target is case insensitive.

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm
