### PR TITLE
The  "postMessage" mechanism does not work for embedded frames (close #803)

### LINKED ISSUE #803: The `postMessage` mechanism does not work for embedded frames
top window
    -> iframe
         -> iframe without src

If we try to send a message from the embedded iframe to the parent iframe we will get an error.

### PR DESCRIPTION
**Pull request by churkin**
\cc @miherlosev @LavrovArtem

### CODE REVIEW

File: src/client/sandbox/event/message.js [hunk 1]
```diff
@@ -195,7 +195,7 @@ export default class MessageSandbox extends SandboxBase {
         var message = MessageSandbox._wrapMessage(MESSAGE_TYPE.service, msg);
 
         // NOTE: For iframes without src.
```
Comment (LavrovArtem) [inline src/client/sandbox/event/message.js]: Change comment

**Comment by churkin** [comment]
@testcafe-build-bot \retest

**Comment by churkin** [comment]
FPR
