### PR TITLE
Multiple document.write works incorrectly (close #416)

### LINKED ISSUE #416: Multiple document.write works incorrectly
```javascript
test('', function () {
    var iframe = document.createElement('iframe');

    iframe.id = 'test';
    document.body.appendChild(iframe);

    var iframeDoc = iframe.contentDocument;

    iframeDoc.open();
    iframeDoc.write('<div></div>', "__begin$");
    iframeDoc.write('<script>');
    iframeDoc.write('var x = 5');
    iframeDoc.write('<\/script>', "__end$");
    iframeDoc.close();

    ok(iframeDoc.getElementsByTagName('script')[0].innerHTML.indexOf('var x = 5') > -1);
});
```
image

### PR DESCRIPTION
**Pull request by LavrovArtem**
\сс @churkin @inikulin

### CODE REVIEW

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 1]
```diff
@@ -217,15 +234,25 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
             },
 
             innerText: {
-                condition: el => typeof el.tagName === 'string' && domUtils.isScriptElement(el) &&
-                                 typeof el.innerText === 'string',
+                condition: el => typeof el.tagName === 'string' && typeof el.innerText === 'string' &&
+                                 (domUtils.isScriptElement(el) || domUtils.isStyleElement(el)),
```
Comment (churkin) [inline src/client/sandbox/code-instrumentation/properties/index.js]: `typeof el.tagName === 'string' && typeof el.innerText === 'string' ` 

is it necessary ?

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 2]
```diff
@@ -217,15 +234,25 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
...
 
-                get: el => typeof el.innerText === 'string' ? removeProcessingHeader(el.innerText) : el.innerText,
+                get: el => {
+                    if (domUtils.isScriptElement(el))
+                        return getStoredWriteContent(el) || removeProcessingHeader(el.innerText);
+                    else if (domUtils.isScriptElement(el))
```
Comment (churkin) [inline src/client/sandbox/code-instrumentation/properties/index.js]: double `isScriptElement` check

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 3]
```diff
@@ -415,25 +442,49 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
...
+                    return text;
                 }
             },
 
             textContent: {
                 // NOTE: Check for tagName being a string, because it may be a function in an Angular app (T175340).
-                condition: el => typeof el.tagName === 'string' && domUtils.isScriptElement(el),
-                get:       el => typeof el.textContent === 'string' ? removeProcessingHeader(el.textContent) : el.textContent,
+                condition: el => typeof el.tagName === 'string' && typeof el.textContent === 'string' &&
+                                 (domUtils.isScriptElement(el) || domUtils.isStyleElement(el)),
```
Comment (churkin) [inline src/client/sandbox/code-instrumentation/properties/index.js]: `typeof el.tagName === 'string' && typeof el.textContent === 'string'`

is it necessary ?

File: src/client/sandbox/code-instrumentation/properties/index.js (hunk 1 above)
Comment (LavrovArtem) [inline src/client/sandbox/code-instrumentation/properties/index.js]: yes, this code ```typeof el.innerText === 'string'``` check that property is exists

File: src/client/sandbox/node/document/index.js [hunk 4]
```diff
@@ -1,25 +1,24 @@
...
     constructor (nodeSandbox) {
         super();
 
-        this.storedDocumentWriteContent = '';
-        this.writeBlockCounter          = 0;
-        this.nodeSandbox                = nodeSandbox;
-        this.readyStateForIE            = null;
+        this.nodeSandbox     = nodeSandbox;
+        this.readyStateForIE = null;
+        this.writeSandbox    = new DocumentWriteSandbox();
```
Comment (churkin) [inline src/client/sandbox/node/document/index.js]: Is it an sandbox?

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
ping

**Comment by AlexanderMoskovkin** [comment]
FYI: rebase required

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
\cc @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
rename `getWritableElContent -> getPendingElementContent`

File: src/client/sandbox/code-instrumentation/properties/index.js (hunk 1 above)
Comment (churkin) [inline src/client/sandbox/code-instrumentation/properties/index.js]: In which case it can not be?

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 5]
```diff
@@ -217,15 +234,25 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
...
+                condition: el => typeof el.tagName === 'string' && typeof el.innerText === 'string' &&
+                                 (domUtils.isScriptElement(el) || domUtils.isStyleElement(el)),
 
-                get: el => typeof el.innerText === 'string' ? removeProcessingHeader(el.innerText) : el.innerText,
+                get: el => {
+                    if (domUtils.isScriptElement(el))
+                        return getPendingElementContent(el) || removeProcessingHeader(el.innerText);
+                    else if (domUtils.isStyleElement(el))
+                        return getPendingElementContent(el) || styleProcessor.cleanUp(el.innerText, urlUtils.parseProxyUrl);
+                },
```
Comment (churkin) [inline src/client/sandbox/code-instrumentation/properties/index.js]: What if it does not `script` or `style` element? `undefined` ???

**Comment by churkin** [comment]
lgtm
