### PR TITLE
fix `The `change` event shouldn't be raised on an upload input if the value wasn't changed after `setFilesToUpload `` (close #1844)

### LINKED ISSUE #1844: The `change` event shouldn't be raised on an upload input if the value wasn't changed after `setFilesToUpload `
I guess we have a different behaviour between testcafe's `setFilesToUpload` and browser users.

If we try to use `setFilesToUpload` to upload same file as before, then `input[type=file] `will updates. But if we try to do it "by hand" it will not updates. It is native behavior.

You can check it in my repo: https://github.com/dmitrykurmanov/surveyjs_testcafe
cli command: `testcafe chrome tests/questions/file.js -T "setFilesToUpload_issue"`

This test must be fail, but it is not.

Steps to reproduce native behaviour "by hand":
1. choose big file `../resources/big_Dashka.jpg`
2. click "change_file_max_size" button
3. choose same file
4. see that error message is here and there is no preview, but by testcafe's `setFilesToUpload` this is not true

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/1844

### Changes
1. Fix the `change` event behavior.

### Native `change` event behavior
Test page:
```html
<html>
<head></head>
<body>
    <label for="upload">Choose a file:</label>

    <input type="file" multiple="true" id="upload">

    <script>
        var uploadInput = document.getElementById('upload');

        ['change', 'input']
            .forEach(function (event) {
                uploadInput.addEventListener(event, function (e) {
                    console.log(e.type);
                });
            });
    </script>
</body>
</html>
```
Result:
```
Single select:
// Windows 10

Step 1: Select `file-1.txt`.
// Chrome, Firefox: input, change; Edge: change; IE11: change, input;

Step 2: Select `file-1.txt`.
// Firefox: input, change; Chrome, Edge, IE11: no events


// Multiple select:

Step 1: Select `file-1.txt`, `file-2.txt`.
// [macOS Mojave, Windows 10] Chrome: input, change; [macOS Mojave] Safari: change

Step 2: Select `file-1.txt`, `file-2.txt`.
// [macOS Mojave, Windows 10] Chrome: no events; [macOS Mojave] Safari: no events

Step 3: Select `file-2.txt`, `file-1.txt`.
// [Windows 10] Chrome: no events; [macOS Mojave] Chrome: input, change;
// [macOS Mojave] Safari: change
```

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@AndreyBelym, thank you :)

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: src/client/sandbox/upload/index.ts [hunk 1]
```diff
@@ -101,6 +101,28 @@ export default class UploadSandbox extends SandboxBase {
...
+                    break;
+                }
+            }
+
+            if (found === false)
+                return true;
+        }
+
+        return false;
+    }
```
Comment (LavrovArtem) [inline src/client/sandbox/upload/index.ts]: Let's refactor it with the `for..of` cycle.

**Comment by Farfurix** [comment]
@testcafe-build-bot retest
