### PR TITLE
fn.constructor should return wrapped Function object (closes #913)

### LINKED ISSUE #913: [todomvc] Js-error appears on the Humble demo page
page: http://todomvc.com/examples/humble
error: `Uncaught Error: interface conversion: interface is map[string]interface {}, not func(...interface {}) *js.Object`

reproduced in playground. Tested in Chrome but should be check in other browsers

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
/cc @churkin @LavrovArtem

### CODE REVIEW

File: test/client/fixtures/sandbox/node/window-test.js [hunk 1]
```diff
@@ -132,3 +132,15 @@ test('window.onerror must be overriden (B238830)', function () {
...
+test('the constructor field of a function should return a wrapped Function object (GH-913)', function () {
+    var f = function () {
+    };
+
+    switch (f.constructor) {
+        case Function:
+            ok(true);
+            break;
+        default:
+            ok(false);
```
Comment (inikulin) [inline test/client/fixtures/sandbox/node/window-test.js]: Whole `switch` can be replaced with `strictEqual(f.constructor, Function)`
