### PR TITLE
fix `We don't need to process the innerHTML property for elements without it` (close #1164)

### LINKED ISSUE #1164: We don't need to process the innerHTML property for elements without it
For example, svg elements.

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @miherlosev @churkin

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 1]
```diff
@@ -524,3 +524,48 @@ test('we should clean up html and remove extra namespaces from svg (GH-1083)', f
...
+    var svg             = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
+    var html            = '<a href="/path">link</a>';
+    var processedHtml   = processHtml(html);
+    var processedStyle  = styleProcessor.process('body {}', null, true);
+    var htmlPproperties = ['innerHTML', 'outerHTML'];
+    var textProperties  = ['innerText', 'text', 'textContent'];
+    var haveAsserts     = false;
+
+    htmlPproperties.forEach(function (property) {
+        var svgHasProperty = svg[property] !== void 0;
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: Let's change test scenario:
1. when element has target property we will check that getter returns processed value
2. when element doesn't have target property we check that getter return `void 0` on first check and set value on second check

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 2]
```diff
@@ -117,6 +117,13 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
     _createPropertyAccessors (window, document) {
         var storedDomain = '';
 
+        function hasElementProperty (el, prop) {
```
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/properties/index.js]: `innerHTML` and etc. are text properties.
Let's do more specified check for this.
```js
function elementHasTextPropertyInProtoChain (el, propName) {
    return typeof el[propName]  === string && !el.hasOwnProperty(propName);
}
```
So, name describes the function behavior and you can remove comment.

File: src/client/utils/dom.js [hunk 3]
```diff
@@ -761,3 +775,13 @@ export function getFileInputs (el) {
...
+
+export function hasElementProperty (el, prop) {
+    if (el[prop] === void 0)
+        return false;
+
+    if (isSVGElement(el))
+        return DEFAULT_SVG_ELEMENT_TEXT_ATTR_VALUES[prop] !== void 0;
+
+    return DEFAULT_HTML_ELEMENT_TEXT_ATTR_VALUES[prop] !== void 0;
+}
```
Comment (miherlosev) [inline src/client/utils/dom.js]: This code relates only for code instrumentation.
So, let's move this to the `code-instrumentation/properties/index.js`.

File: src/client/utils/dom.js [hunk 4]
```diff
@@ -16,6 +16,20 @@ const arraySlice = Array.prototype.slice;
...
+function getAttrValues (element) {
+    var values = {};
+
+    for (var property of ELEMENT_TEXT_PROPERTIES)
+        values[property] = element[property];
+
+    return values;
+}
+
+const DEFAULT_SVG_ELEMENT_TEXT_ATTR_VALUES  = getAttrValues(nativeMethods.createElementNS.call(document, 'http://www.w3.org/2000/svg', 'svg'));
```
Comment (miherlosev) [inline src/client/utils/dom.js]: `SVG_ELEMENT_TEXT_PROPERTIES`

Now it contains empty string or undefined values. 
Instead of this, you need to store property existence.

File: src/client/utils/dom.js [hunk 5]
```diff
@@ -16,6 +16,20 @@ const arraySlice = Array.prototype.slice;
...
+const DEFAULT_HTML_ELEMENT_TEXT_ATTR_VALUES = getAttrValues(nativeMethods.createElement.call(document, 'div'));
```
Comment (miherlosev) [inline src/client/utils/dom.js]: `HTML_ELEMENT_TEXT_PROPERTIES`

File: src/client/utils/dom.js [hunk 6]
```diff
@@ -761,3 +775,13 @@ export function getFileInputs (el) {
 export function getIframes (el) {
     return isIframeElement(el) ? [el] : getNativeQuerySelectorAll(el).call(el, 'iframe,frame');
 }
+
+export function hasElementProperty (el, prop) {
```
Comment (miherlosev) [inline src/client/utils/dom.js]: `elementHasTextProperty`

File: src/client/utils/dom.js [hunk 7]
```diff
@@ -761,3 +775,13 @@ export function getFileInputs (el) {
...
+    if (el[prop] === void 0)
```
Comment (miherlosev) [inline src/client/utils/dom.js]: `if (typeof el[prop] === 'string')`

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 8]
```diff
@@ -525,3 +525,63 @@ test('we should clean up html and remove extra namespaces from svg (GH-1083)', f
...
+    var svg             = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
+    var html            = '<a href="/path">link</a>';
+    var processedHtml   = processHtml(html);
+    var style           = 'body {}';
+    var processedStyle  = styleProcessor.process(style, null, true);
+    var textProperties  = ['innerText', 'text', 'textContent'];
+
+    div.appendChild(svg);
+
+    var svgHasInnerHTML = svg.innerHTML !== void 0;
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: Lets' change test logic as following:
 - there are native elements and processed elements
- if native element contains text or html property then overridden element should returns processed value
- else if it should return origin value

Comment (LavrovArtem) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: I don't understand. Why we need native element?

File: src/client/utils/dom.js (hunk 3 above)
Comment (LavrovArtem) [inline src/client/utils/dom.js]: I think that the `elementHasTextProperty` is an utility function and it must be stored in the `utils`.

Comment (miherlosev) [inline src/client/utils/dom.js]: Utility function can be used in several places.
So, I don't know an another place where we should use this function.
This is why, this should be placed in code instumentation.

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js (hunk 8 above)
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: Your are right. We can do without native elements

File: src/client/utils/dom.js (hunk 3 above)
Comment (LavrovArtem) [inline src/client/utils/dom.js]: ok, I agree

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 9]
```diff
@@ -28,6 +28,18 @@ import { emptyActionAttrFallbacksToTheLocation } from '../../../utils/feature-de
 
 const ORIGINAL_WINDOW_ON_ERROR_HANDLER_KEY = 'hammerhead|original-window-on-error-handler-key';
 
+function checkoutAttrs (element) {
```
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/properties/index.js]: `getElementTextProperties (element)`

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 10]
```diff
@@ -28,6 +28,18 @@ import { emptyActionAttrFallbacksToTheLocation } from '../../../utils/feature-de
...
+    var values = {};
```
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/properties/index.js]: This variable name can confuse.
`var result = {}` is better.

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 11]
```diff
@@ -28,6 +28,18 @@ import { emptyActionAttrFallbacksToTheLocation } from '../../../utils/feature-de
...
+
+    for (var property of ['innerHTML', 'outerHTML', 'innerText', 'textContent', 'text'])
```
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Store array to `ELEMENT_TEXT_PROPERTIES` constant
It will be easy to read

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 12]
```diff
@@ -525,3 +525,56 @@ test('we should clean up html and remove extra namespaces from svg (GH-1083)', f
...
+
+    if (svgHasOuterHTML)
+        strictEqual(div.innerHTML, processedHtml);
+    else
+        strictEqual(svg.outerHTML, html);
+
+    textProperties.forEach(function (property) {
+        var svgHasProperty = svg[property] !== void 0;
+
+        svg[property] = processedStyle;
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: As for `innerHTML` and `outerHTML`:
Change to `setProperty(svg, property, style)`

File: src/client/sandbox/code-instrumentation/properties/index.js (hunk 9 above)
Comment (LavrovArtem) [inline src/client/sandbox/code-instrumentation/properties/index.js]: May be `checkElementTextProperties`?
Because we check list of properties https://github.com/DevExpress/testcafe-hammerhead/pull/1166/files/06cec7bc260014bbaef58a672d04162c36421fa4#diff-8a9510bf5230ab2620f64db8801899c9R35

File: src/client/sandbox/code-instrumentation/properties/index.js (hunk 10 above)
Comment (LavrovArtem) [inline src/client/sandbox/code-instrumentation/properties/index.js]: agree

File: src/client/sandbox/code-instrumentation/properties/index.js (hunk 11 above)
Comment (LavrovArtem) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Maybe just create local variable into function?
```javascript
var values     = {};
var properties = ['innerHTML', 'outerHTML', 'innerText', 'textContent', 'text'];

for (var property of properties)
...
```

Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Ok

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
ping @churkin

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 13]
```diff
@@ -28,6 +28,19 @@ import { emptyActionAttrFallbacksToTheLocation } from '../../../utils/feature-de
 
 const ORIGINAL_WINDOW_ON_ERROR_HANDLER_KEY = 'hammerhead|original-window-on-error-handler-key';
 
+function checkElementTextProperties (element) {
```
Comment (churkin) [inline src/client/sandbox/code-instrumentation/properties/index.js]: We are using `el` anywhere

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 14]
```diff
@@ -525,3 +525,58 @@ test('we should clean up html and remove extra namespaces from svg (GH-1083)', f
...
+    var processedHtml  = processHtml(html);
+    var style          = 'body {}';
+    var textProperties = ['innerText', 'textContent'];
+    var styleElement   = document.createElement('style');
+
+    div.appendChild(svg);
+
+    var svgHasInnerHTML = svg.innerHTML !== void 0;
+
+    if (svgHasInnerHTML)
```
Comment (churkin) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: `strictEqual(getProperty(svg, 'innerHTML'), svgHasInnerHTML ? '' : void 0);`

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
ping @churkin

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 15]
```diff
@@ -525,3 +525,46 @@ test('we should clean up html and remove extra namespaces from svg (GH-1083)', f
...
+
+    setProperty(svg, 'innerHTML', html);
+
+    strictEqual(svg.innerHTML, svgHasInnerHTML ? processedHtml : html);
+
+    svg.innerHTML = '';
+
+    var svgHasOuterHTML = svg.outerHTML !== void 0;
+
+    strictEqual(getProperty(svg, 'outerHTML'), svgHasOuterHTML ? svg.outerHTML : void 0);
```
Comment (churkin) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]:
```javascript
var svgHasOuterHTML = svg.outerHTML !== void 0;
 
strictEqual(getProperty(svg, 'outerHTML'), svgHasOuterHTML ? svg.outerHTML : void 0);
```
I don't understand this. Why not
```javascript
strictEqual(getProperty(svg, 'outerHTML'), svg.outerHTML);
```

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR
