### PR TITLE
fix 'on calling without parameters we should return the native resultof 'fetch' function instead of window.Promise.reject' (close #1099)

### LINKED ISSUE #1099: On calling without parameters we should return the native result of 'fetch' function instead of window.Promise.reject
It blocks the `core-js` library loading and, accordingly, `angular2` applications.

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem

### CODE REVIEW

File: src/client/sandbox/fetch.js [hunk 1]
```diff
@@ -127,6 +127,9 @@ export default class FetchSandbox extends SandboxBase {
             window.Request.prototype = nativeMethods.Request.prototype;
 
             window.fetch = function (...args) {
+                if (!args.length)
+                    return nativeMethods.fetch.apply(this, args);
```
Comment (LavrovArtem) [inline src/client/sandbox/fetch.js]: just `return nativeMethods.fetch.call(this);`

Comment (miherlosev) [inline src/client/sandbox/fetch.js]: Ok

**Comment by miherlosev** [comment]
FPR
