### PR TITLE
fix xhr issues (close #545, close #552)

### LINKED ISSUE #545: Xhr request without credentials should not send cookie and authorization headers to the destination server
Then `xhr.withCredentials=false` (it is default value) cookie and authorization headers is sended to destination server.
It is wrong.  We should manually discard it on server side before sending to the destination server.
See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

Files to reproduce:
```javascript
index.html
...
  <script>
        document.cookie = 'key=value';

        var xhr = new XMLHttpRequest();
        xhr.addEventListener("load", function () {
            alert('load complete');
        }, false);
        xhr.addEventListener("error", function () {
            alert('error completed');
        }, false);

        xhr.open('GET', 'http://localhost:3001/test', true);
        xhr.withCredentials = false;
        xhr.send(null);
</script>
```

```javascript
index.js
var http = require('http');
var fs   = require('fs');

http.createServer(function (req, res) {
    var content = fs.readFileSync('index.html');
    res.end(content);
}).listen(3000);

http.createServer(function (req, res) {
    var content = '';

    console.log(req.url);
    console.log(req.headers.cookie);

    if (req.url === '/test')
        content = 'test';

    res.end(content);
}).listen(3001);
```

### LINKED ISSUE #552: We should remove our xhr headers before sending request
Before sending xhr request to the destination server we should remove our custom headers (`x-hammerhead|xhr|request-marker-header`, `x-hammerhead|xhr|cors-supported-header`, etc).

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem 

1)Xhr request without credentials should not send cookie and authorization headers to the destination server (#545)
2)We should remove our xhr headers before sending request (#552)

### CODE REVIEW

File: src/request-pipeline/index.js [hunk 1]
```diff
@@ -110,6 +112,15 @@ function createReqOpts (ctx) {
     // NOTE: All headers, including 'content-length', are built here.
     var headers = headerTransforms.forRequest(ctx, this);
 
+    // NOTE: Need to remove cookie and authorization headers manually if the request is sent without credentials
+    if (ctx.isXhr && !!ctx.req.headers[XHR_HEADERS.corsSupported] && !ctx.req.headers[XHR_HEADERS.withCredentials]) {
+        delete headers.cookie;
```
Comment (LavrovArtem) [inline src/request-pipeline/index.js]: I think that this logic needs to moves to the `headers-transforms.js` like [this](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/header-transforms.js#L49)

Comment (inikulin) [inline src/request-pipeline/index.js]: > I think that this logic needs to moves to the headers-transforms.js like this

correct

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
Waiting for #557

**Comment by miherlosev** [comment]
FPR

File: src/request-pipeline/header-transforms.js [hunk 2]
```diff
@@ -1,25 +1,36 @@
...
-
-    [XHR_HEADERS.requestMarker]: skip
+    'cookie':         skip
 };
 
+Object.keys(XHR_HEADERS).forEach(headerKey => requestTransforms[XHR_HEADERS[headerKey]] = skip);
+
+REQUEST_AUTHENTICATION_HEADERS.forEach(headerName => {
+    requestTransforms[headerName] = (src, ctx) => isXhrWithoutCredentials(ctx) ? void 0 : src;
+});
```
Comment (churkin) [inline src/request-pipeline/header-transforms.js]: I support the idea to write all headers directly to the `requestTransforms`

**Comment by churkin** [comment]
\r

**Comment by inikulin** [comment]
Title should contatin `close #545, close #552`. Otherwise #552 will not be closed

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm
