### PR TITLE
outerHTML property is not overridden (fix #538)

### LINKED ISSUE #538: outerHTML property is not overridden
Some ASPxEditors regression tests use it to perform markup checks.

### PR DESCRIPTION
**Pull request by LavrovArtem**
\cc @churkin @AndreyBelym

### CODE REVIEW

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 1]
```diff
@@ -229,6 +229,40 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
...
+                        // NOTE: For the iframe with an empty src.
+                        if (parentWindow && parentWindow !== window &&
+                            parentWindow[INTERNAL_PROPS.processDomMethodName])
+                            parentWindow[INTERNAL_PROPS.processDomMethodName](parentEl, parentDocument);
+                        else if (window[INTERNAL_PROPS.processDomMethodName])
+                            window[INTERNAL_PROPS.processDomMethodName](parentEl);
+
+                        // NOTE: This check is required for an element in an unavailable window.
+                        // NOTE: Use timeout, so that changes take effect.
+                        if (window.self && domUtils.isBodyElement(el))
```
Comment (AndreyBelym) [inline src/client/sandbox/code-instrumentation/properties/index.js]: You can't use `el` after `el.outerHTML` was executed (in Chrome, at least), because:
```js
var body = document.body;

body.outerHTML;
//<body>BODY1</body>

body.outerHTML = '<body>BODY2</body>'
//"<body>BODY2</body>"

body.outerHTML
//"<body>BODY1</body>"

body.parentNode
//null

document.body
//<body>BODY2</body>
```
At least for `<body>`, rewiting `el.outerHTML` leads to behavior like `el.parentNode.replaceChild(newElFromOuterHTML, el)`, and `el` points to original element which HTML is not changed and that is removed from DOM.

**Comment by AndreyBelym** [comment]
\r-

File: src/client/sandbox/code-instrumentation/properties/index.js (hunk 1 above)
Comment (AndreyBelym) [inline src/client/sandbox/code-instrumentation/properties/index.js]: On second thought, I realized that purpose of this code is to emit an if 'body' has been changed, so it's probably fine.

Comment (AndreyBelym) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Wow, that is a really twisted thing actually:
```js
document.head
//<head></head>

document.body
//<body></body>

document.head.outerHTML = '<head id="myhead"></head><body id="mybody"></body>';
//'<head id="myhead"></head><body id="mybody"></body>'

document.head
//<head id="myhead"></head>

document.body
//<body id="mybody"></body>

document.documentElement
//<html>
//    <head id="myhead"></head>
//    <body id="mybody"></body>
//    <body></body>
//</html>
```
Don't know, will be there a practical point of messing with that case?
I just need getter that cleans HTML to fix ASP tests.

Comment (LavrovArtem) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Hmmm, @churkin what you think about this?

Comment (AndreyBelym) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Also, if `outerHTML` is `<body>...</body>` or `<head>...</head>`, note that they need special handling in processHtmlInternal [here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/html.js#L160). `container.innerHTML = html` will not work if `container` is '<div>'.

Comment (LavrovArtem) [inline src/client/sandbox/code-instrumentation/properties/index.js]: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/html.js#L134

```preparePageHtml``` wrap ```html```, ```body```, ```head``` and ```doctype``` tags

Comment (AndreyBelym) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Oh, I see it now. 
BTW tests for that I need this fix are fine, but I want to check it on complete test suite, so give me some time.

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 2]
```diff
@@ -229,6 +229,40 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
                 }
             },
 
+            outerHTML: {
+                condition: domUtils.isElementNode,
+                get:       el => cleanUpHtml(el.outerHTML, el.parentNode && el.parentNode.tagName),
```
Comment (AndreyBelym) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Need to check if `el.outerHTML` is not `undefined`, otherwise it will break `wrapTextNodes` inside `cleanUpHtml`.

Comment (LavrovArtem) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Before call of `get` function, call `condition` which checks that `el` is node element

Comment (AndreyBelym) [inline src/client/sandbox/code-instrumentation/properties/index.js]: It doesn't work. In ASPxUpload control uses `XMLDocument` instance with content like 
```xml
<status progress="100" totalSize="4" totalUploadedSize="4" contentType="" fileProgress="100" fileUploadedSize="4" fileSize="4" fileName="test.txt"></status>
```

It checks for  `xml.documentElement.outerHTML` being `undefined` to detect, it is valid XML document or not. In case of invalid XML, `documentElement` doesn't have `outerHTML` property, but it's `nodeType` is `1`, so it passes our `domUtils.isElementNode` check.

**Comment by LavrovArtem** [comment]
FPR

File: test/client/fixtures/sandbox/code-instrumentation/setters-test.js [hunk 3]
```diff
@@ -304,6 +291,26 @@ if (!browserUtils.isIE) {
...
+    parentDiv.appendChild(childDiv);
+
+    strictEqual(parentDiv.children.length, 1);
+    strictEqual(parentDiv.firstChild, childDiv);
+
+    eval(processScript('childDiv.outerHTML = htmlText', true, false));
+
+    strictEqual(parentDiv.children.length, 2);
+    strictEqual(parentDiv.firstChild.href, urlUtils.getProxyUrl('http://domain.com/'));
+    strictEqual(parentDiv.lastChild.src, urlUtils.getProxyUrl('http://domain.com/script', null, null, null, 's'));
```
Comment (AndreyBelym) [inline test/client/fixtures/sandbox/code-instrumentation/setters-test.js]: I'd add a test for IE where `outerHTML` is undefined:
```js
if (browserUtils.isIE) {
   var doc = document.implementation.createDocument(null, 'status', null);
   strictEqual(doc.documentElement.outerHTML, void 0);
}
```

**Comment by AndreyBelym** [comment]
\r-, please, add a test where `outerHTML` is undefined.

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 4]
```diff
@@ -205,6 +207,30 @@ test('get style body', function () {
...
+    var div      = document.createElement('div');
+
+    eval(processScript('div.innerHTML = htmlText', true, false));
+
+    var a = div.firstChild;
+
+    strictEqual(a.outerHTML, processHtml(htmlText));
+    strictEqual(eval(processScript('a.outerHTML', true, false)), htmlText);
+});
+
```
Comment (AndreyBelym) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: I'd add a test for IE where `outerHTML` is undefined:
```js
if (browserUtils.isIE) {
   var doc = document.implementation.createDocument(null, 'status', null);
   strictEqual(eval(processScript('doc.documentElement.outerHTML', true, false)), void 0);
}
```

**Comment by LavrovArtem** [comment]
FPR

**Comment by AndreyBelym** [comment]
lgtm

**Comment by churkin** [comment]
lgtm
