### PR TITLE
fix `Reach Router doesn't navigate in Testcafe tests` (close #1863)

### LINKED ISSUE #1863: Reach Router doesn't navigate in Testcafe tests
### What is your Test Scenario?

A single-page app built using [Reach Router](https://reach.tech/router).
 
### What is the Current behavior?

Any navigation using Reach Router doesn't work.
 
### What is the Expected behavior?

Links are followed.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): https://lyzwj8w0qz.codesandbox.io/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { Selector } from "testcafe";

fixture("reach router")
  .page("https://lyzwj8w0qz.codesandbox.io/");

test("can click links using history api", async (t) => {
  await t.click(Selector("a").withExactText("Dashboard"))
    .expect(Selector("h2").withExactText("Dashboard").exists).ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
testcafe chrome 'test.ts'
 Running tests in:
 - Chrome 70.0.3538 / Mac OS X 10.14.1

 reach router
 ✖ can click links using history api

   1) AssertionError: expected false to be truthy

      Browser: Chrome 70.0.3538 / Mac OS X 10.14.1

          3 |fixture("reach router")
          4 |  .page("https://lyzwj8w0qz.codesandbox.io/");
          5 |
          6 |test("can click links using history api", async (t) => {
          7 |  await t.click(Selector("a").withExactText("Dashboard"))
       >  8 |    .expect(Selector("h2").withExactText("Dashboard").exists).ok();
          9 |});

         at Object.<anonymous> (/Users/jag/dev/demo/test.ts:8:63)
         at <anonymous> (/Users/jag/dev/demo/test.ts:7:71)
         at __awaiter (/Users/jag/dev/demo/test.ts:3:12)
         at test (/Users/jag/dev/demo/test.ts:6:55)
         at markeredfn (/Users/jag/dev/demo/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at step (/Users/jag/dev/demo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
         at <anonymous> (/Users/jag/dev/demo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14)
         at new F (/Users/jag/dev/demo/node_modules/core-js/library/modules/_export.js:36:28)
         at <anonymous> (/Users/jag/dev/demo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
         at <anonymous> (/Users/jag/dev/demo/node_modules/testcafe/src/api/wrap-test-function.js:7:5)



 1/1 failed (14s)
```
</details>

### Steps to Reproduce:

Open the codesandbox, click the Dashboard link and see the heading text change. Repeat that in testcafe and see it not change...
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    v8.11.4
* command-line arguments:  testcafe chrome test.ts
* browser name and version: Chrome 70.0.3538
* platform and version:          Mac OS X 10.14.1

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/1863

### Changes
1. Fix the `isLocation` check: `isLocation` for the **cloned location object** should not return the `true` value.

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: src/client/utils/dom.ts [hunk 1]
```diff
@@ -528,19 +528,27 @@ export function isBlob (instance): boolean {
...
-    try {
-        // eslint-disable-next-line no-restricted-properties
-        return instance && typeof instance === 'object' && instance.href !== void 0 && instance.assign !== void 0;
-    }
-    catch (e) {
-        // NOTE: Try to detect cross-domain window location.
-        // A cross-domain location has no the "assign" function in Safari.
-        return instance.replace && (isSafari || !!instance.assign);
+    if (isIE || isSafari) {
+        let instanceCtor = null;
```
Comment (miherlosev) [inline src/client/utils/dom.ts]: I propose to move this part to separate non-exported function `isLocationByPrototype (instance)`

Comment (Farfurix) [reply src/client/utils/dom.ts]: Ok. How about the `...Proto` function name based on this: `instance.__proto__;`?

Non-exportable `isLocationByProto`:
```js
function isLocationByProto (instance): boolean {
    ...
}

export function isLocation (instance): boolean {
    ....
    if (isIE || isSafari)
        return isLocationByProto(instance);
    ....
}
```

Comment (miherlosev) [reply src/client/utils/dom.ts]: Ok. Let it be 'Proto'

**Comment by Farfurix** [comment]
@testcafe-build-bot retest
