### PR TITLE
fix `Convert mocking response headers to lowercase` (close #1660)

### LINKED ISSUE #1660: Convert mocking response headers to lowercase
https://github.com/DevExpress/testcafe/issues/2534

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe/issues/2534

### CODE REVIEW

File: src/request-pipeline/request-hooks/response-mock.js [hunk 1]
```diff
@@ -12,13 +12,26 @@ export default class ResponseMock {
...
+        this.headers    = this._lowerCaseHeaderNames(headers);
 
         this.requestOptions = null;
 
         this._validateParameters();
     }
 
+    _lowerCaseHeaderNames (headers) {
+        if (!headers)
+            return void 0;
```
Comment (miherlosev) [inline src/request-pipeline/request-hooks/response-mock.js]: `return headers`;

File: test/server/request-hook-test.js [hunk 2]
```diff
@@ -8,6 +8,14 @@ const ConfigureResponseEventOptions = require('../../lib/session/events/configur
 const noop                          = require('lodash').noop;
 
 describe('ResponseMock', () => {
+    it('Custom headers should be converted to lowercase', () => {
```
Comment (miherlosev) [inline test/server/request-hook-test.js]: `it('Header names should be lowercased', () `
