### PR TITLE
fix `Nodejs sends headers in lower case but destination server ignores it` (close #1380)

### LINKED ISSUE #1380: Nodejs sends headers in lower case but destination server ignores it
Site: https://www.exblog.jp/
Script comes to client without content if hammerhead sends the `user-agent` header in lower case. Everything works right if we replace `user-agent` to `User-Agent`.

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

File: src/request-pipeline/destination-request/index.js [hunk 1]
```diff
@@ -52,14 +53,17 @@ export default class DestinationRequest extends EventEmitter {
...
 
-            this.req = this.protocolInterface.request(this.opts, res => {
+            this.opts.headers = transformHeadersCaseToRaw(this.opts.headers, this.opts.rawHeaders);
+            this.req          = this.protocolInterface.request(this.opts, res => {
                 if (waitForData) {
                     res.on('data', noop);
                     res.once('end', () => this._onResponse(res));
                 }
             });
+            this.opts.headers = storedHeaders;
```
Comment (churkin) [inline src/request-pipeline/destination-request/index.js]: Add a comment here

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest
