### PR TITLE
fix 'Should emulate native behaviour on calling 'Worker' constructor without parameters' (close #1132)

### LINKED ISSUE #1132: Should emulate native behaviour on calling 'Worker' constructor without parameters
Without proxy:
```js
new Worker()
Uncaught TypeError: Failed to construct 'Worker': 1 argument required, but only 0 present.
```

With proxy:
```js
new Worker()
Failed to load resource: the server responded with a status of 404 (Not Found)
http:<proxy-server-url>/<site-url>/undefined
```

See https://html.spec.whatwg.org/multipage/workers.html#dom-worker

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
FPR

File: src/client/sandbox/node/window.js [hunk 1]
```diff
@@ -128,11 +128,17 @@ export default class WindowSandbox extends SandboxBase {
         }
 
         if (window.Worker) {
-            window.Worker           = scriptURL => {
+            window.Worker           = function (scriptURL, options) {
+                if (this instanceof window.Worker === false)
```
Comment (miherlosev) [inline src/client/sandbox/node/window.js]: After moving check to a separate method we with @churkin decide that comment is unnecessary.
So @LavrovArtem review this
