### PR TITLE
fix `Cookie processing problem related to applications running on 'localhost' with non-default port` (close #1491)

### LINKED ISSUE #1491: Cookie processing problem related to applications running on 'localhost' with non-default port
Steps to reproduce:
Click button 'XHR: Get cookie using ...' and observe 'XSRF-TOKEN=<number>' message in browser console (if run site without proxy).
With proxy, the message does not show. It indicates that cookie sets incorrectly.

[Files to reproduce](https://github.com/DevExpress/testcafe-hammerhead/files/1716312/index.zip)

### PR DESCRIPTION
**Pull request by Farfurix**
### Example
https://github.com/DevExpress/testcafe-hammerhead/issues/1491

### Changes:
1. Refactor default port omitting (the default port is omitted in Chrome, Firefox, Edge, Internet Explorer browsers)
2. localhost/127.0.0.1 (http/https) with default port (80/443) case. If the cookie domain and the current url hostname are equal to localhost/127.0.0.1, we should remove Domain=... form cookie (see tough-cookie: getPublicSuffix('localhost') check)
3. Non-default localhost/127.0.0.1 (http/https) case. Host name check in `_isValidCookie()` instead of same origin check

### Reference:
https://github.com/DevExpress/testcafe-hammerhead/issues/659

### CODE REVIEW

File: src/utils/url.js [hunk 1]
```diff
@@ -20,6 +20,8 @@ export const REQUEST_DESCRIPTOR_VALUES_SEPARATOR = '!';
 export const TRAILING_SLASH_RE                   = /\/$/;
 export const SPECIAL_PAGES                       = ['about:blank', 'about:error'];
 
+export const DEFAULT_PORT = ':80';
```
Comment (miherlosev) [inline src/utils/url.js]: Don't duplicate constants.
Create a shared function `omitDefaultPort ()` and use it on client and server.
Use implementation from server side - https://github.com/DevExpress/testcafe-hammerhead/blob/4ea7ec3b78993f48db4863eee8852391dc12f46e/src/request-pipeline/context.js#L82.

File: src/client/utils/destination-location.js [hunk 2]
```diff
@@ -31,6 +31,9 @@ export function sameOriginCheck (location, checkedUrl, rejectForSubdomains) {
     if (checkedUrl)
         checkedUrl = resolveUrl(checkedUrl);
 
+    // NOTE: exclude the default port from 'same origin check'
+    location = location.replace(sharedUrlUtils.DEFAULT_PORT, '');
```
Comment (miherlosev) [inline src/client/utils/destination-location.js]: We should omit default port inside `sameOriginCheck` function.

File: src/utils/url.js (hunk 1 above)
Comment (miherlosev) [reply src/utils/url.js]: Add tests for `http` and `https` protocol values.

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: src/session/cookies.js [hunk 3]
```diff
@@ -1,6 +1,10 @@
-import { CookieJar } from 'tough-cookie';
+import { CookieJar, Cookie } from 'tough-cookie';
 import BYTES_PER_COOKIE_LIMIT from './cookie-limit';
 import { castArray } from 'lodash';
+import { parseUrl } from '../utils/url';
+
+const LOCALHOST_NAME = 'localhost';
```
Comment (miherlosev) [inline src/session/cookies.js]: `const LOCALHOST_DOMAIN = ...`

File: src/session/cookies.js [hunk 4]
```diff
@@ -14,6 +18,19 @@ export default class Cookies {
             if (cookieStr.length > BYTES_PER_COOKIE_LIMIT)
                 return;
 
+            const cookie = Cookie.parse(cookieStr);
+
+            // NOTE: If cookie.domain and url hostname are equal to localhost/127.0.0.1,
+            // we should remove 'Domain=...' form cookieStr (GH-1491)
+            if (cookie && cookie.domain) {
+                const isCookieDomainLocalhost = cookie.domain === LOCALHOST_NAME || cookie.domain === LOCALHOST_IP;
```
Comment (miherlosev) [inline src/session/cookies.js]: Move to separate function `_hasLocalhostDomain (cookie)`

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest
