### PR TITLE
fix ``setFilesToUpload` not raising `change` event on Linux/Chrome?` (close #2007)

### LINKED ISSUE #2007: `setFilesToUpload` not raising `change` event on Linux/Chrome?
Since testcafe v1.1.3 our tests are failing on Linux/Chrome while they are passing on Linux/Firefox or MacOS/Chrome. Manual testing also works fine on Linux/Chrome.

It seems that on Linux/Chrome the `change` event is fired only for the first call to `setFilesToUpload`. Any subsequent call to `setFilesToUpload` (even with a different `filePath`) don't seem to be firing the `change` event.

It feels this issue could be related or even was introduced with #1844.

Our frontend code looks like this (Vue.js):
```
<input
id="file-upload"
ref="file"
class="uploader"
type="file"
accept=".txt"
@change="handleFileUpload"
>
```

Our test code looks like this:
```js
let files = [
  'file1.txt',
  'file2.txt',
  'file3.txt',
];

for (let i = 0; i < files.length; i += 1) {
    await t.setFilesToUpload(Selector('#file-upload'), files[i]);
}
```

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/2007

### Changes
1. Call `_shouldRaiseChangeEvent` before `setUploadInfo`.

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: test/client/fixtures/sandbox/upload-test.js [hunk 1]
```diff
@@ -543,6 +543,23 @@ asyncTest('change event', function () {
     uploadSandbox.doUpload(fileInput, './file.txt');
 });
 
+test('change event in the case of another file selection (GH-2007)', function () {
+    expect(2);
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/upload-test.js]: In my opinion, using of the counter is more clear.
