### PR TITLE
fix `Missing localStorage property after redirect` (close #1999, close #1507)

### LINKED ISSUE #1507: Page infinitely reloads
https://testcafe-discuss.devexpress.com/t/browserstack-page-is-constantly-loaded/843

Our local storage wrapper saves to native `localStorage` when the `pagehide` event is triggered. The problem occurs because of this event isn't triggered on origin site. I've created simple example for demonstration but it works properly and event is triggered.

```js
const http = require('http')

http.createServer((req, res) => {
    if (req.url === '/') {
        res.writeHead(200, { 'content-type': 'text/html' });
        res.end(`
            <h1></h1>
            <script>
                if (localStorage.getItem('key123') !== 'value') {
                    localStorage.setItem('key123', 'value');
                    location.reload();
                } else
                    document.querySelector('h1').textContent = 'Done!';
            </script>
        `);
    } else
        res.end();
}).listen(1993);
```

### LINKED ISSUE #1999: Missing localStorage property after redirect
### What is your Test Scenario?

I am trying to test login integration. We are using OAuth2 for authentication. After a succesfull login on backend, client get redirected to the http://localhost:3000/oauth_callback.html

The code there looks something like:

`oauth_callback.html`

```html
<html>
  <head>
    <script type="text/javascript">
       const accessToken = getAccessTokenFromUrl(window.location.hash)
       localStorage.setItem("app", accessToken)
       const redirectUrl = window.location.href.split('oauthCallback')[0];
       location.assign(redirectUrl); # http://localhost:3000/
    </script>
  </head>
  <body></body>
</html>

```

At this point I can confirm that the accessToken gets stored into the localStorage. However, after the `location.assign(redirectUrl)` happens, React app starts, and in the code we check if there is a token in localStorage and else redirect back to the login (backend). At this point, `localStorage` that was previously set is missing the property thus there is a infinite loop between backend and client.

### What is the Current behavior?

localStorage that I set inside my callback is empty on app start
 
### What is the Expected behavior?

localStorage should be preserved
 
### What is your web application and your TestCafe test code?

Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

const baseUrl = 'http://localhost:3000/';

fixture('<Login />').page(baseUrl);

const emailInput = Selector('input[name=username]');
const passwordInput = Selector('input[name=password]');

const loginButton = Selector('button[type=submit]');

const reactRootElement = Selector('#root');

test('Logs in with correct credentials', async t => {
  await t
    .typeText(emailInput, 'mail@gmail.com')
    .typeText(passwordInput, 'password')
    .click(loginButton)
    .wait(10000)
    .expect(reactRootElement.exists)
    .ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   v1.1.0
* node.js version:                    v10.8.0
* command-line arguments:  testcafe chrome src/test/e2e --hostname 127.0.0.1
* browser name and version: Chrome 73.0.3683
* platform and version:          Mac OS X 10.14.3

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

File: src/client/sandbox/storages/index.ts [hunk 1]
```diff
@@ -64,12 +65,18 @@ export default class StorageSandbox extends SandboxBase {
             // @ts-ignore
             this.sessionStorageWrapper = new StorageWrapper(this.window, this.nativeMethods.winSessionStorageGetter.call(this.window), storageKey);
 
-            this.unloadSandbox.on(this.unloadSandbox.BEFORE_UNLOAD_EVENT, () => {
+            const pageNavigationHandler = () => {
```
Comment (miherlosev) [inline src/client/sandbox/storages/index.ts]: const saveToNativeStorages => ()...
