### PR TITLE
Fix wrong document.write executing in iframe with srcdoc (close #2494)

### LINKED ISSUE #2494: Scripts in iframe's srcdoc not executing
### What is your Scenario?
An iframe with srcdoc containing a script.
 
### What is the Current behavior?
The script does not execute under TestCafe.
MicrosoftTeams-image (1)

 
### What is the Expected behavior?
The script executes.
MicrosoftTeams-image
 

### What is your public web site URL?

Your website URL (or attach your complete example): 
```html
<!DOCTYPE html>
<html>
    <body>
        <iframe srcdoc="<script>document.write(123)</script>"></iframe>
    </body>
</html>
```

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 fixture `1`;

test.page('./page.html')('srcdoc', async t => {
    await t.debug();
})
```
</details>
 
### Your Environment details:

* node.js version:                    v14.8.0
* browser name and version: Chrome 86.0.4240.198
* platform and version:          Windows 10
* TestCafe version:                 1.10.0-rc.4

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

File: src/utils/init-script-for-iframe-template.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+import INTERNAL_PROPS from '../processing/dom/internal-properties';
```
Comment (miherlosev) [inline src/utils/init-script-for-iframe-template.ts:1]: I guess it's time to create folder structure for the self-removing scripts
```js
src/utils/self-removing-script/
    create.js
    init-script-for-iframe-template.ts
    ...
    put here all self-removing scripts from client and server sides
                                               
```

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest
