### PR TITLE
fix `Implement support for proxying pages inside ASAR archives` (close #2033)

### LINKED ISSUE #2033: Implement support for proxying pages inside ASAR archives
It's very common for Electron apps to ship their resources (including pages) inside [ASAR](https://electronjs.org/docs/tutorial/application-packaging) archives. Since Hammerhead can't read packed files, it leads to difficulties in testing builded Electron apps. We can modify the `FileRequest` class to use the [electron/asar](https://github.com/electron/asar) module to reads an archived content on the fly and provide it to the browser under test.

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/2033

### Changes
1. Fix `FileRequest` (`asar` case).
2. Update **src/.babelrc** to the **Node 8** target without the `@babel/plugin-transform-async-to-generator` plugin.

### "File not exists" error codes
- Windows: `ENOENT`
- **Linux: `ENOTDIR` (found it on travis server tests):**
```
ENOTDIR: not a directory,
stat \'/home/travis/build/testcafe-build-bot/testcafe-hammerhead/test/server/data/file-in-asar-archive/directory-looks-like-archive.asar/app.asar/non-exist-file.txt\'
```

### Notes
https://electronjs.org/docs/tutorial/application-packaging:
> `asar` archives are treated as **directories**

### CODE REVIEW

File: src/request-pipeline/file-request.ts [hunk 1]
```diff
@@ -5,34 +5,71 @@ import { EventEmitter } from 'events';
...
+                        throw new Error(TARGET_IS_NOT_FILE);
+
+                    return access(this.path, fs.constants.R_OK);
+                })
+                .then(() => this._onOpen())
+                .catch((err: Error) => this._onError(err));
+        }
+    }
+
+    static _getAsarArchivePath (path: string) : string {
```
Comment (miherlosev) [inline src/request-pipeline/file-request.ts]: Move all ASAR related code to the separate file and the following method signatures:
```js
asar.getArchivePath(...)
asar.getFilePathInArchive(...)
asar.getReadStream(...)
```

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: src/request-pipeline/file-request.ts [hunk 2]
```diff
@@ -13,23 +14,36 @@ const TARGET_IS_NOT_FILE = 'The target of the operation is not a file';
...
+                    throw new Error(`The asar archive target ("${getArchivePath(this.url)}") of the operation is not found`);
+
+                throw err;
+            })
             .then((stats: fs.Stats) => {
-                if (!stats.isFile())
-                    throw new Error(TARGET_IS_NOT_FILE);
+                if (!stats.isFile()) {
+                    throw new Error(this.isAsarPath
+                        ? `The asar archive target ("${getArchivePath(this.url)}") of the operation is not a file`
```
Comment (AndreyBelym) [inline src/request-pipeline/file-request.ts]: I think we shouldn't throw an error if `isAsarPath === true` and `stats.isDirectory() === true`. It's a pretty ligitimate to use `.asar` in a name of a directory. Maybe we can just set `isAsarPath` to `false` in this case?

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: src/request-pipeline/file-request.ts [hunk 3]
```diff
@@ -5,34 +5,54 @@ import { EventEmitter } from 'events';
...
 import { MESSAGE, getText } from '../messages';
 import { stat, access } from '../utils/promisified-functions';
+import Asar from '../utils/asar';
 
 const DISK_RE: RegExp = /^\/[A-Za-z]:/;
 
-const TARGET_IS_NOT_FILE = 'The target of the operation is not a file';
+const TARGET_IS_NOT_FILE: string = 'The target of the operation is not a file';
+
+const asar = Asar.getInstance();
```
Comment (AndreyBelym) [inline src/request-pipeline/file-request.ts]: Looks a bit overcomplicated, I think we can just create an `Asar`  instance here.

File: src/utils/asar.ts [hunk 4]
```diff
@@ -0,0 +1,111 @@
+// @ts-ignore
```
Comment (AndreyBelym) [inline src/utils/asar.ts]: I understand that you have to put this since the `asar` package doesn't come with TS definitions, but it's still better to add an explaining comment here.

File: src/utils/asar.ts [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+import asar from 'asar';
+import { toReadableStream } from './buffer';
+import path from 'path';
+import fs from 'fs';
+/*eslint-disable no-unused-vars*/
```
Comment (AndreyBelym) [inline src/utils/asar.ts]: Not nice, but out of this PR's scope. I created a new issue about it: https://github.com/DevExpress/testcafe-hammerhead/issues/2068

File: src/utils/asar.ts [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+
+    private _findArchivePath (fullPath: string) : string {
+        let currentPath = fullPath;
+        let currentDir  = path.dirname(currentPath);
+
+        while (currentPath !== currentDir) {
+            let isFile = false;
+
+            try {
+                isFile = fs.statSync(currentPath).isFile();
```
Comment (AndreyBelym) [inline src/utils/asar.ts]: It will be nice if we can avoid using the synchronous version here.

Comment (Farfurix) [reply src/utils/asar.ts]: 1)
```js
try {
    const stats = await stat(currentPath);

    isFile = stats.isFile();
}
// eslint-disable-next-line no-empty
catch (e) {
}
```
2)
```js
let isFile;

await stat(currentPath).then(() => { isFile = true; }, () => { isFile = false; });
```
3)
```js
private _isFile (fullPath: string) : Promise<boolean> {
    return stat(fullPath)
        .then(() => true, () => false);
}
```
```js
if (await this._isFile(currentPath) && path.extname(currentPath) === ASAR_EXTNAME)
    return currentPath;
```

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: src/utils/asar.ts [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+        const parsedPath    = this._parse(fullPath);
+        const extractedFile = asar.extractFile(parsedPath.archive, parsedPath.fileName);
+
+        return toReadableStream(extractedFile);
+    }
+
+    getFileInAsarNotFoundMessage (fullPath: string) : string {
+        const parsedAsarPath = this._parse(fullPath);
+
+        return 'The target file ("' + parsedAsarPath.fileName + '") in asar archive ("' + parsedAsarPath.archive + '") is not found';
```
Comment (LavrovArtem) [inline src/utils/asar.ts]:
```js
`The target file ("${parsedAsarPath.fileName}") in asar archive ("${parsedAsarPath.archive}") is not found`
```

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: src/request-pipeline/file-request/asar-resource.ts [hunk 8]
```diff
@@ -0,0 +1,42 @@
...
+            this._error = e;
+        }
+    }
+
+    get isArchiveFound () : boolean {
+        return !!this._archive;
+    }
+
+    async init () : Promise<void> {
+        if (await asar.isAsar(this._path)) {
```
Comment (LavrovArtem) [inline src/request-pipeline/file-request/asar-resource.ts]:
```js
if (!await asar.isAsar(this._path))
    return;
```

File: src/request-pipeline/file-request/index.ts [hunk 9]
```diff
@@ -47,17 +39,17 @@ export default class FileRequest extends EventEmitter {
...
-        let stream = fs.createReadStream(this.path);
+    private _onOpen (contentStream: any) {
+        let stream = contentStream;
 
         stream = Object.assign(stream, {
             statusCode: 200,
             trailers:   {},
             headers:    {
-                'content-type': mime.lookup(this.path)
+                'content-type': mime.lookup(this._path)
```
Comment (AndreyBelym) [inline src/request-pipeline/file-request/index.ts]: Could we write a test asserting that we correctly determine MIME types of resources from ASAR?

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: src/utils/asar.ts [hunk 10]
```diff
@@ -0,0 +1,93 @@
...
+    }
+
+    extractFileToReadStream (archive: string, fileName: string) : Readable {
+        const extractedFile = asar.extractFile(archive, fileName);
+
+        return toReadableStream(extractedFile);
+    }
+
+    getFileInAsarNotFoundMessage (archive: string, fileName: string) : string {
+        return `The target file ("${fileName}") in the "asar" archive ("${archive}") is not found`;
```
Comment (VasilyStrelyaev) [inline src/utils/asar.ts]:
```
        return `Cannot find the "${fileName}" file in the "${archive}" archive.
```

Comment (VasilyStrelyaev) [reply src/utils/asar.ts]: Checked by correctors

**Comment by Farfurix** [comment]
@testcafe-build-bot retest
