### PR TITLE
fix wrong url processing in iframe without src when we change only location's hash (close #714)

### LINKED ISSUE #714: Wrong url processing in iframe without src when we change only location's hash
Example page:
```html
<body>
<script>
    var iframe = document.createElement('iframe');
    document.body.appendChild(iframe);
    iframe.contentDocument.write('<script>location.replace(location.toString() + "#hash");<\/script>');
</script>
</body>
```

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

**Comment by LavrovArtem** [comment]
FPR

**Comment by miherlosev** [comment]
lgtm

**Comment by LavrovArtem** [comment]
@VasilyStrelyaev 
https://github.com/DevExpress/testcafe-hammerhead/pull/715/files#diff-f17475e116c70c73c37dd369b8d12b6bR125
check comment please

File: src/client/utils/url.js [hunk 1]
```diff
@@ -118,3 +120,10 @@ export function parseResourceType (resourceType) {
 export function stringifyResourceType (resourceType) {
     return sharedUrlUtils.getResourceTypeString(resourceType);
 }
+
+export function isChangedOnlyHash (currentUrl, newUrl) {
+    // NOTE: we compare proxied urls because urls passed into the function may be not proxied or proxied
+    // or relatives but the getProxyUrl function solves all problems related with it
```
Comment (VasilyStrelyaev) [inline src/client/utils/url.js]:
```
    // NOTE: we compare proxied urls because urls passed into the function may be proxied, non-proxied
    // or relative. The getProxyUrl function solves all the corresponding problems.
```

**Comment by VasilyStrelyaev** [comment]
\r-

**Comment by LavrovArtem** [comment]
FPR

**Comment by churkin** [comment]
lgtm
