### PR TITLE
fix 'Url processing on server side always adds traling slash for proxy url' (close #351)

### LINKED ISSUE #351: Url processing on server side always adds traling slash for proxy url
Problem located inside standard module `url`.
Example:
`require('url').resolve('', 'http://www.example.org/') -> 'http://www.example.org/'`
`require('url').resolve('', 'http://www.example.org') -> 'http://www.example.org/'`

It causes problem for `element.querySelector([attribute$=value])`.
Selector `[attribute$=value]` means that attribute value ends with specified value.

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @churkin @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
FPR

File: src/utils/url.js [hunk 1]
```diff
@@ -241,3 +241,12 @@ export function prepareUrl (url) {
     // For example, the "//////google.com" url is equal to "//google.com".
     return url.replace(/^\/+(\/\/.*$)/, '$1');
 }
+
+export function fixUrlAfterResolving (urlBefore, urlAfter) {
```
Comment (inikulin) [inline src/utils/url.js]: It should be `ensureTrailingSlash` or something like that. I also don't like arg names. Maybe `srcUrl` and `processedUrl` or smthg like this. 
\cc @VasilyStrelyaev 
Overall this feels extremely hacky, mostly because currently URL-related stuff is a completely fucked up. But  for now, this is just fine

**Comment by inikulin** [comment]
\r-

File: src/utils/url.js (hunk 1 above)
Comment (VasilyStrelyaev) [inline src/utils/url.js]: ok

**Comment by miherlosev** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm

**Comment by churkin** [comment]
lgtm
