### PR TITLE
fix `The 'formtarget' attribute should be overriden` (close #1513)

### LINKED ISSUE #1513: The 'formtarget' attribute should be overriden
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/1513
### References:
https://github.com/DevExpress/testcafe-hammerhead/issues/1670
### Changes
1. Override `formtarget` attribute.
2. Add `formaction` change logic for an element with an `formtarget` attribute
3. Fix `<a>` `tagName` in test/client/fixtures/target-attr-test.js
4. Remove 'anchor with target attribute' test from test/client/fixtures/sandbox/node/dom-processor-test.js

### Remove 'anchor with target attribute' test form test/client/fixtures/sandbox/node/dom-processor-test.js
```diff
- test('anchor with target attribute', function () {
-     var anchor   = nativeMethods.createElement.call(document, 'a');
-     var testUrl  = 'http://url.com/';
-     var proxyUrl = urlUtils.getProxyUrl(testUrl, { resourceType: 'i' });
-
-     nativeMethods.setAttribute.call(anchor, 'href', testUrl);
-     nativeMethods.setAttribute.call(anchor, 'target', 'iframeName');
-
-     domProcessor.processElement(anchor, function (url, resourceType) {
-         return urlUtils.getProxyUrl(url, { resourceType: resourceType });
-     });
-
-     strictEqual(nativeMethods.getAttribute.call(anchor, 'href'), proxyUrl);
-     strictEqual(nativeMethods.getAttribute.call(anchor, DomProcessor.getStoredAttrName('href')), testUrl);
- });
```
Now, we don't have the `i` iframe flag in this case. See `_processUrlAttrs` -> `getElementResourceType` -> `_isOpenLinkInIframe`

### Notes
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button:
> `formtarget`
If the button is a submit button, this attribute is a name or keyword indicating where to display the response that is received after submitting the form. This is a name of, or keyword for, a browsing context (for example, tab, window, or inline frame). If this attribute is specified, it overrides the target attribute of the button's form owner. The following keywords have special meanings:
> - _self: Load the response into the same browsing context as the current one. This value is the default if the attribute is not specified.
> - _blank: Load the response into a new unnamed browsing context.
> - _parent: Load the response into the parent browsing context of the current one. If there is no parent, this option behaves the same way as _self.
> - _top: Load the response into the top-level browsing context (that is, the browsing context that is an ancestor of the current one, and has no parent). If there is no parent, this option behaves the same way as _self.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input:
> `formtarget`
If the input element is a submit button or image, this attribute is a name or keyword indicating where to display the response that is received after submitting the form. This is a name of, or keyword for, a browsing context (e.g. tab, window, or inline frame). If this attribute is specified, it overrides the target attribute of the elements's form owner. The following keywords have special meanings:
> - _self: Load the response into the same browsing context as the current one. This value is the default if the attribute is not specified.
> - _blank: Load the response into a new unnamed browsing context.
> - _parent: Load the response into the parent browsing context of the current one. If there is no parent, this option behaves the same way as _self.
> - _top: Load the response into the top-level browsing context (i.e. the browsing context that is an ancestor of the current one, and has no parent). If there is no parent, this option behaves the same way as _self.

### CODE REVIEW

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: src/processing/dom/index.js [hunk 1]
```diff
@@ -434,19 +457,20 @@ export default class DomProcessor {
...
+            let attrValue = this.adapter.getAttr(el, targetAttr);
 
             // NOTE: Value may have whitespace.
             attrValue = attrValue && attrValue.replace(/\s/g, '');
 
             if (attrValue === '_blank' || attrValue === 'blank') {
-                this.adapter.setAttr(el, 'target', '_top');
-                this.adapter.setAttr(el, storedTargetAttr, attrValue);
+                this.adapter.setAttr(el, targetAttr, '_top');
+                this.adapter.setAttr(el, storedFormTargetAttr, attrValue);
```
Comment (LavrovArtem) [inline src/processing/dom/index.js]: ~~storedFormTargetAttr~~ storedTargetAttr

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

**Comment by Farfurix** [comment]
@testcafe-build-bot retest

File: test/client/fixtures/sandbox/node/attributes-test.js [hunk 2]
```diff
@@ -160,6 +160,48 @@ if (!browserUtils.isIE || browserUtils.version > 9) {
     });
 }
 
+if (!browserUtils.isIE || browserUtils.version > 9) {
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/attributes-test.js]: remove this condition

File: test/client/fixtures/target-attr-test.js [hunk 3]
```diff
@@ -159,6 +172,158 @@ test('all possible elements', function () {
...
+    function testFormtargetAttr (el, real, primary) {
+        el.setAttribute('formtarget', primary);
+
+        checkElementFormTarget(el, real, primary);
+    }
+
+    form.appendChild(input);
+    form.appendChild(button);
+
+    testFormtargetAttr(input, '_top', '_blank');
```
Comment (LavrovArtem) [inline test/client/fixtures/target-attr-test.js]:
```js
[input, button].forEach(function(el) {
    testFormtargetAttr(el, '_top', '_blank');
    testFormtargetAttr(el, '_parent', '_parent');
    // ...
    testFormtargetAttr(el, '_top', 'unknown_window');
})
```

File: src/client/dom-processor/client-dom-adapter.js [hunk 4]
```diff
@@ -110,4 +111,8 @@ export default class ClientDomAdapter extends BaseDomAdapter {
     sameOriginCheck (location, checkedUrl) {
         return sameOriginCheck(location, checkedUrl);
     }
+
+    isExistingTarget (target) {
+        return findByName(target);
```
Comment (miherlosev) [inline src/client/dom-processor/client-dom-adapter.js]: `findByName` returns window. `isExistingTarget` should returns boolean.
So, rewrite as
```js
 isExistingTarget (target) {
        return !!findByName(target);
}
```

File: src/client/sandbox/node/element.js [hunk 5]
```diff
@@ -184,15 +191,17 @@ export default class ElementSandbox extends SandboxBase {
 
             args[valueIndex] = 'off';
         }
-        else if (loweredAttr === 'target' && DomProcessor.isTagWithTargetAttr(tagName)) {
-            const currentTarget = nativeMethods.getAttribute.call(el, 'target');
+        else if (loweredAttr === 'target' && DomProcessor.isTagWithTargetAttr(tagName) ||
```
Comment (miherlosev) [inline src/client/sandbox/node/element.js]: Use `TARGET_ATTRS` from https://github.com/DevExpress/testcafe-hammerhead/pull/1664/files#diff-94b2df7ad47ba85d634a6c72c32343c0R17 here and below

```js
...
else if (TARGET_ATTRS.indexOf(loweredAttr) > -1 && DomProcessor.isTagWithTargetAttr(tagName))
```

**Comment by Farfurix** [comment]
@testcafe-build-bot retest
