### PR TITLE
fix '404 errors for xhr request in https://twitter.com/' (close #711)

### LINKED ISSUE #711: 404 errors for xhr request in  https://twitter.com/
See [video](http://screencast.com/t/2oFUay3HP)

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 1]
```diff
@@ -700,6 +700,17 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
 
                     return style.listStyleImage;
                 }
+            },
+
+            // xhr
+            responseURL: {
+                condition: domUtils.isXMLHttpRequest,
```
Comment (inikulin) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Do we really need code instrumentation here? Can't we just define property on xhr object?

Comment (LavrovArtem) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Yes, we do. I tried to define the property but it's impossible.

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/code-instrumentation/properties/index.js (hunk 1 above)
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/properties/index.js]: I change code in `xhr.js` to
```javascript
  var orscHandler = () => {
                if (this.readyState === 4) {
                    Object.defineProperty(xhr, 'responseURL', {  value: 'test'  });
                    xhrSandbox.emit(xhrSandbox.XHR_COMPLETED_EVENT, { xhr });
                }

            };
```
and all works good.

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 2]
```diff
@@ -251,6 +251,23 @@ test('clean up outerHTML', function () {
     }
 });
 
+asyncTest('xhr.responseURL', function () {
+    var xhr   = new XMLHttpRequest();
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: remove uncessary spaces before `=new XMLHttpRequest`.

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 3]
```diff
@@ -251,6 +251,23 @@ test('clean up outerHTML', function () {
...
+
+    xhr.addEventListener('readystatechange', function () {
+        if (this.readyState === XMLHttpRequest.DONE) {
+            if (this.responseURL)
+                strictEqual(eval(processScript('this.responseURL')), 'https://example.com/xhr-test/');
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: More simple:
`strictEqual(getProperty('this.responseURL')), 'https://example.com/xhr-test/');`

File: test/client/fixtures/sandbox/code-instrumentation/getters-test.js [hunk 4]
```diff
@@ -251,6 +251,23 @@ test('clean up outerHTML', function () {
...
+            else
+                expect(0);
+
+            start();
+        }
+    });
+    xhr.open('GET', '/xhr-test/');
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/code-instrumentation/getters-test.js]: You got 404 error.
Change url to `/xhr-test/100` because parameter `:delay` from 
https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/config-qunit-server-app.js#L42 is required.

**Comment by miherlosev** [comment]
\r-

File: src/client/sandbox/code-instrumentation/properties/index.js (hunk 1 above)
Comment (LavrovArtem) [inline src/client/sandbox/code-instrumentation/properties/index.js]: I agree. If we define the `responseURL` property in this place it won't be the cause of any errors and after if we check the `xhr.responseURL` it will be equal to the 'test' string.
But if we append in the test in a `readystatechange` handler the following code:
```javascript
console.log(this.readyState + ' - ' + this.responseURL);
```
it will print the following logs:
```
1 - 
2 - http://localhost:2000/sessionId/https://example.com/xhr-large-response
3 - http://localhost:2000/sessionId/https://example.com/xhr-large-response
4 - http://localhost:2000/sessionId/https://example.com/xhr-large-response
```

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/code-instrumentation/properties/index.js (hunk 1 above)
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Ok. Then revert to `readystatechange` event in your test.

**Comment by miherlosev** [comment]
\r-
see https://github.com/DevExpress/testcafe-hammerhead/pull/724#discussion_r74232849
https://github.com/DevExpress/testcafe-hammerhead/pull/724/files#r74232953

**Comment by LavrovArtem** [comment]
FPR

File: src/client/utils/dom.js [hunk 5]
```diff
@@ -521,6 +521,12 @@ export function isDocument (instance) {
     }
 }
 
+export function isXMLHttpRequest (instance) {
+    return instance && (instance instanceof XMLHttpRequest ||
+                        typeof instance === 'object' && instance.toString &&
+                        instance.toString() === '[object XMLHttpRequest]');
+}
+
 export function isBlob (instance) {
```
Comment (miherlosev) [inline src/client/utils/dom.js]: Add tests for XMLHttpRequest from top window and iframe.

File: src/client/utils/dom.js [hunk 6]
```diff
@@ -521,6 +521,12 @@ export function isDocument (instance) {
     }
 }
 
+export function isXMLHttpRequest (instance) {
+    return instance && (instance instanceof XMLHttpRequest ||
```
Comment (miherlosev) [inline src/client/utils/dom.js]: Add tests for XMLHttpRequest from top window and iframe.

**Comment by miherlosev** [comment]
\r-

File: src/client/utils/dom.js (hunk 6 above)
Comment (LavrovArtem) [inline src/client/utils/dom.js]: ok

**Comment by miherlosev** [comment]
lgtm

**Comment by LavrovArtem** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by miherlosev** [comment]
Lgtm
