### PR TITLE
fix `Tests sometimes (frequently) lose connection` (for Linux) (close  #1647)

### LINKED ISSUE #1647: Tests sometimes (frequently) lose connection
Sometimes when I launch tests, the tests suddenly stops; I get this error message when I look at the console. 

It doesn't matter what browser I use. I am on MacOS

```
.../node_modules/testcafe-hammerhead/lib/request-pipeline/connection-reset-guard.js:20
        throw new Error(err);
        ^

Error: Error: write EPIPE
    at Domain.<anonymous> (.../node_modules/testcafe-hammerhead/lib/request-pipeline/connection-reset-guard.js:20:15)
    at Domain.emit (events.js:182:13)
    at Domain.EventEmitter.emit (domain.js:442:20)
    at Domain._errorHandler (domain.js:224:23)
    at Object.setUncaughtExceptionCaptureCallback (domain.js:140:29)
    at process._fatalException (internal/bootstrap/node.js:447:31)```

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

File: src/request-pipeline/connection-reset-guard.js [hunk 1]
```diff
@@ -5,8 +5,10 @@ const connectionResetDomain = domain.create();
 
 connectionResetDomain.on('error', err => {
     // NOTE: The nodejs throw the EPIPE error instead of the ECONNRESET error
-    // when the connection is broken in some cases on MacOS
-    if (err.code === 'ECONNRESET' || os.type() === 'Darwin' && err.code === 'EPIPE')
+    // when the connection is broken in some cases on MacOS and Linux
+    const isMacOrLinux = os.type() === 'Darwin' || os.type() === 'Linux';
```
Comment (miherlosev) [inline src/request-pipeline/connection-reset-guard.js]: Let's use the [os-family](https://www.npmjs.com/package/os-family) module to simplify readability.

File: src/request-pipeline/connection-reset-guard.js [hunk 2]
```diff
@@ -1,12 +1,12 @@
 import domain from 'domain';
-import os from 'os';
+import osFamily from 'os-family';
```
Comment (miherlosev) [inline src/request-pipeline/connection-reset-guard.js]: `import os from 'os-family';`
