### PR TITLE
Fix 'Clicking anchor tags does not navigate to target destinations' (close #2080)

### LINKED ISSUE #2080: Clicking anchor tags does not navigate to target destinations
### What is your Scenario?
https://stackoverflow.com/questions/57037042/clicking-anchor-tags-does-not-navigate-to-target-destinations
 
### What is your public web site URL?
https://tw.bid.yahoo.com/search/auction/product?qt=product&kw=iphone&p=iphone

For team:
~~Check the `anchor` event listeners.~~
Chrome (iPhone emulation mode)
`isLocation` -> `_browser.isSafari === true` -> `isLocationByProto`:
```js
return instanceCtor && _nativeMethods.default.objectToString.call(instanceCtor) === '[object LocationPrototype]';
// _nativeMethods.default.objectToString.call(instanceCtor) === [object Location]
```

### PR DESCRIPTION
**Pull request by Farfurix**
https://github.com/DevExpress/testcafe-hammerhead/issues/2080

### Changes
1. Fix `isLocationByProto` in the case of the "iPhone X" Chrome emulation mode.

### Details
"iPhone X" Chrome emulation mode (before the fix):
`__get$Loc(location)` -> `isLocation()` -> `_browser.isSafari === true` (emulation mode) -> `isLocationByProto()`:
```js
return instanceCtor && _nativeMethods.default.objectToString.call(instanceCtor) === '[object LocationPrototype]';
// _nativeMethods.default.objectToString.call(instanceCtor) === [object Location]
```

### `browserUtils` differences
"-" - Chrome 76 (no emulation mode)
"+" - Chrome 76 ("iPhone X" emulation mode).
```diff
- fullVersion: "76.0"
+ fullVersion: "11.0"
isAndroid: false
- isChrome: true
+ isChrome: false
isElectron: false
isFirefox: false
isIE: false
isIE9: false
isIE10: false
isIE11: false
- isIOS: false
+ isIOS: true
isMSEdge: false
isMacPlatform: false
- isMobile: false
+ isMobile: true
- isSafari: false
+ isSafari: true
isTablet: false
isWebKit: true
- version: 76
+ version: 11
- webkitVersion: "537.36"
+ webkitVersion: "604.1.38"
```

### CODE REVIEW

File: src/client/utils/dom.ts [hunk 1]
```diff
@@ -61,7 +61,9 @@ function isLocationByProto (instance: any): boolean {
         return instance.replace && (isSafari || !!instance.assign);
     }
 
-    return instanceCtor && nativeMethods.objectToString.call(instanceCtor) === '[object LocationPrototype]';
+    return instanceCtor &&
```
Comment (LavrovArtem) [inline src/client/utils/dom.ts]: Store `nativeMethods.objectToString.call(instanceCtor)` value to new variable.

Comment (Farfurix) [reply src/client/utils/dom.ts]:
```js
if (!instanceCtor)
    return false;

const instanceCtorToString = nativeMethods.objectToString.call(instanceCtor);

return instanceCtorToString === '[object LocationPrototype]' ||
    instanceCtorToString === '[object Location]'; // NOTE: "iPhone" Chrome device emulation case (GH-2080)
```

**Comment by Farfurix** [comment]
@testcafe-build-bot retest
