### PR TITLE
fix `Adobe Launch Analytics requests are not fired when accessing a page with TestCafe` (close #2453)

### LINKED ISSUE #2453: Adobe Launch Analytics requests are not fired when accessing a page with TestCafe
### What is your Scenario?
If accessing the test website with the TestCafe the Adobe Launch Analytics requests are not displayed.
If accessing the page manually in browser, Adobe Launch Analytics requests are displayed.
 

### Steps to Reproduce:
- For TestCafe - Run the attached code
  - While the page is loading open the Developer Tools and filter the requests by **b/ss** and observe that there are no requests
- Manually: it cannot be reproduced.

### What is the Current behavior?
- When accessing the website the TestCafe no Adobe Launch Analytics requests are fired.
- Also one or more JavaScript errors are displayed in Console: ***Cannot read property 'indexOf' of undefined*** 
  - Note that these JavaScript errors are not displayed when visiting the page manually.
image

 
### What is the Expected behavior?
- When visiting the page with TestCafe Adobe Launch Analytics can be fired:
- No JavaScript errors are displayed after accepting the cookies
 
### What is your public web site URL?
https://www.newegg.com/

<summary>Your complete test code (or attach your test files):</summary>

```

import {Selector} from "testcafe";

fixture`Analytics`
    .beforeEach(async t => {
        await t.maximizeWindow();
    })

test('Adobe Launch Analytics', async t => {
    await t.navigateTo("https://www.newegg.com/");
    await t.click(Selector("#onetrust-pc-btn-handler"));
    await t.click(Selector('div:nth-child(3) label span.ot-switch-nob').filterVisible());
    await t.click(Selector('div:nth-child(4) label span.ot-switch-nob').filterVisible());
    await t.click(Selector('div:nth-child(5) label span.ot-switch-nob').filterVisible());
    await t.click('.save-preference-btn-handler.onetrust-close-btn-handler');
    await t.debug();
})


```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "screenshotPath": "screenshots",
  "browsers": "chrome",
  "screenshots": {
    "takeOnFails": true,
    "fullPage": true
  },
  "debugOnFail": false,
  "skipJsErrors": true,
  "disablePageCaching": false,
  "color": true,
  "speed": 0.90,
  "pageLoadTimeout": 30000,
  "assertionTimeout": 30000,
  "selectorTimeout": 30000,
  "concurrency": 1
}

```
</details>

 
### Your Environment details:

* testcafe version: 1.9.4
* node.js version:                    v11.2.0
command-line arguments: no additional parameters
* platform and version:        Chrome - Version 85.0.4183.121 (Official Build) (64-bit) 
* other:                                 win 10

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

File: src/client/sandbox/node/document/index.ts [hunk 1]
```diff
@@ -247,7 +247,13 @@ export default class DocumentSandbox extends SandboxBase {
 
         const referrerOverriddenDescriptor = createOverriddenDescriptor(docPrototype, 'referrer', {
             getter: function () {
-                return getDestinationUrl(nativeMethods.documentReferrerGetter.call(this));
+                const nativeReferrer = nativeMethods.documentReferrerGetter.call(this);
+                const referrer       = getDestinationUrl(nativeReferrer);
+
+                if (referrer !== nativeReferrer && isSpecialPage(referrer))
```
Comment (miherlosev) [inline src/client/sandbox/node/document/index.ts:253]: For which cases the `referrer !== nativeReferrer` condition is necessary?

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]

**Comment by mariuspahontu** [comment]
thank you, for your work!
