### PR TITLE
fix `Hammerhead memory leak in IE` (close #1262)

### LINKED ISSUE #1262: Hammerhead memory leak in IE for live node collections
Reproduces on tests from internal farm tasks: 
DashboardTests.v17.1.TestCafe - old testcafe
DashboardTests.v17.1.TestCafe.IE - new testcafe

Contact person: Denis Kuznetsov

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@churkin please review this

File: src/client/sandbox/node/live-node-list/wrapper.js [hunk 1]
```diff
@@ -1,64 +1,35 @@
 import nativeMethods from '../../native-methods';
 import { isShadowUIElement } from '../../../utils/dom';
-
-const arrayFilter = Array.prototype.filter;
+import WrapperInternalInfo from './wrapper-internal-info';
```
[the remark this answers is not in the document]
Comment (LavrovArtem) [reply src/client/sandbox/node/live-node-list/wrapper.js]: Internal info of the wrapper

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+        if (isDocumentFragmentNode(el))
+            children = nativeMethods.documentFragmentQuerySelectorAll.call(el, '*');
+        else
+            children = nativeMethods.elementQuerySelectorAll.call(el, '*');
+
+        for (const child of children)
+            this._processElement(child);
+    }
+
+    onElementAddedOrRemoved (el) {
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: `onElementChanged`

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+        this._processElement(el);
+        this._processAllChildren(el);
+    }
+
+    onChildrenAddedOrRemoved (el) {
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: `onChildrenChanged`

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+        if (!el.tagName || isShadowUIElement(el))
+            return;
+
+        const tagName = getTagName(el);
+
+        this._updateVersion('*');
+        this._updateVersion(tagName);
+    }
+
+    _processAllChildren (el) {
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: `_processChildren`

File: src/client/sandbox/code-instrumentation/properties/index.js [hunk 5]
```diff
@@ -93,6 +93,8 @@ export default class PropertyAccessorsInstrumentation extends SandboxBase {
     static _setTextProp (el, propName, text) {
         const processedText = text !== null && text !== void 0 ? String(text) : text;
 
+        DOMMutationTracker.onChildrenAddedOrRemoved(el);
```
Comment (miherlosev) [inline src/client/sandbox/code-instrumentation/properties/index.js]: Why do we call this before element's children is changed?
Where and below in code.

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 6]
```diff
@@ -0,0 +1,81 @@
+import nativeMethods from '../../native-methods';
+import { getTagName, isDocumentFragmentNode, isShadowUIElement } from '../../../utils/dom';
+
+const MAX_SAFE_INTEGER = Math.pow(2, 53) - 1;
+const MIN_SAFE_INTEGER = -MAX_SAFE_INTEGER;
+
+class DOMMutationTracker {
+    constructor () {
+        this._tags               = nativeMethods.objectCreate.call(window.Object, null);
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: `this.mutations`

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 7]
```diff
@@ -0,0 +1,81 @@
...
+        this._isDomContentLoaded = false;
+
+        nativeMethods.addEventListener.call(document, 'DOMContentLoaded', () => {
+            this._isDomContentLoaded = true;
+        });
+    }
+
+    _updateVersion (tagName) {
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: `_updateMutationVersion`

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 8]
```diff
@@ -0,0 +1,81 @@
...
+        this._updateVersion(tagName);
+    }
+
+    _processAllChildren (el) {
+        if (!el.querySelectorAll)
+            return;
+
+        let children;
+
+        if (isDocumentFragmentNode(el))
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: Use the `getNativeQuerySelectorAll` method from `src/client/utils/get-native-query-selector-all.js`

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+    onElementAddedOrRemoved (el) {
+        this._processElement(el);
+        this._processAllChildren(el);
+    }
+
+    onChildrenAddedOrRemoved (el) {
+        this._processAllChildren(el);
+    }
+
+    isWrapperOutdated (tagName, version) {
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: `isOutdated` is a better name because you don't pass wrapper as function parameter.

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js (hunk 4 above)
Comment (LavrovArtem) [reply src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: This function process all children. The `_processChildren` name tell me that function process only children of element.

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js (hunk 7 above)
Comment (LavrovArtem) [reply src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: https://github.com/ryanmcdermott/clean-code-javascript#dont-add-unneeded-context

Comment (miherlosev) [reply src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: Yep

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 10]
```diff
@@ -0,0 +1,77 @@
...
+            return;
+
+        const tagName = getTagName(el);
+
+        this._updateVersion('*');
+        this._updateVersion(tagName);
+    }
+
+    _processChildren (el) {
+        if (!el.querySelectorAll)
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: Add test for this case

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 11]
```diff
@@ -0,0 +1,77 @@
...
+                this._mutations[tagName] = MIN_SAFE_INTEGER;
+            else
+                ++this._mutations[tagName];
+        }
+        else
+            this._mutations[tagName] = MIN_SAFE_INTEGER;
+    }
+
+    _processElement (el) {
+        if (!el.tagName || isShadowUIElement(el))
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: Add test case for `!el.tagName`

Comment (LavrovArtem) [reply src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: https://github.com/DevExpress/testcafe-hammerhead/pull/1322/files#diff-2511acd18edd5a40b5ab70fe3ef86068R191

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js (hunk 10 above)
Comment (LavrovArtem) [reply src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: https://github.com/DevExpress/testcafe-hammerhead/pull/1322/files#diff-2511acd18edd5a40b5ab70fe3ef86068R191

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js [hunk 12]
```diff
@@ -0,0 +1,77 @@
...
+        this._processChildren(el);
+    }
+
+    isOutdated (tagName, version) {
+        if (!this._isDomContentLoaded)
+            return true;
+
+        const lastVersion = this._mutations[tagName];
+
+        if (typeof lastVersion === 'number')
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: As I understand the `lastVersion` can be `number` or `undefined`.
In this case we can simplify code to `if (lastVersion)`
Also add a testcafe then `lastVersion` is `undefined`.

File: src/client/sandbox/node/live-node-list/wrapper-state-manager.js [hunk 13]
```diff
@@ -0,0 +1,22 @@
+import DOMMutationTracker from './dom-mutation-tracker';
+import { isShadowUIElement } from '../../../utils/dom';
+
+const arrayFilter = Array.prototype.filter;
+
+export default class WrapperStateManager {
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/wrapper-state-manager.js]: Let's simplify to `WrapperState`

File: src/client/sandbox/node/live-node-list/dom-mutation-tracker.js (hunk 12 above)
Comment (LavrovArtem) [reply src/client/sandbox/node/live-node-list/dom-mutation-tracker.js]: lastVersion = 0
if (lastVersion)

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/node/live-node-list/wrapper.js [hunk 14]
```diff
@@ -1,64 +1,35 @@
...
-        });
+                    return state.filteredNodeList[index];
+                }
+            },
 
-        if (this.namedItem) {
-            nativeMethods.objectDefineProperty.call(window.Object, this, 'namedItem', {
-                value: (...args) => {
-                    const findNamedItem = this._nodeList.namedItem.apply(this._nodeList, args);
+            namedItem: {
```
Comment (miherlosev) [inline src/client/sandbox/node/live-node-list/wrapper.js]: Use the old way for this
image

File: src/client/utils/dom.js [hunk 15]
```diff
@@ -738,14 +739,25 @@ export function hasClass (el, className) {
     return hasClassFallback(el, className);
 }
 
+export function getClassList (el) {
```
Comment (miherlosev) [inline src/client/utils/dom.js]: It is a redurant function

File: test/client/fixtures/sandbox/node/live-node-list-factory-test.js [hunk 16]
```diff
@@ -260,63 +210,111 @@ module('getElementsByTagName', function () {
...
+
+            assertions.push([refreshNodeListCount, 9, 'access after element was added after begin text div']);
+
+            testDiv.insertAdjacentHTML('beforeend', '<textarea></textarea>');
+
+            elements[0];
+
+            assertions.push([refreshNodeListCount, 10, 'access after element was added before end text div']);
+
+            testDiv.insertAdjacentHTML('afterend', '<textarea></textarea>');
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/node/live-node-list-factory-test.js]: Add test for `documentFragment`

Comment (LavrovArtem) [reply test/client/fixtures/sandbox/node/live-node-list-factory-test.js]: Test for `documentFragment` does not work, need to fix [this](https://github.com/DevExpress/testcafe-hammerhead/issues/1334) issue.

Comment (miherlosev) [reply test/client/fixtures/sandbox/node/live-node-list-factory-test.js]: Ok

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
ping @churkin

**Comment by miherlosev** [comment]
Health Monitor runs:
https://testcafe-hhhm.devexpress.com/history?timestamp=1506971015449
https://testcafe-hhhm.devexpress.com/history?timestamp=1507057401194
Everything works fine (sites with errors are flashers).

**Comment by miherlosev** [comment]
I've created the [example page](https://miherlosev.github.io/issue-pages/hammerhead/1262/index.html) for checking this issue.

### Testing procedure 
open an example uisng hammerhead playground, reload 10 times and measure memory usage.
### Results
this PR - 75 - 85 mb.
the latest commint in master (https://github.com/DevExpress/testcafe-hammerhead/commit/5855bd9769b1c3b419730e08225c4551a001d587) - 105 - 115 mb

Health monitor doesnot found issue for this PR. see https://github.com/DevExpress/testcafe-hammerhead/pull/1322/issuecomment-334090061

@churkin review please
