### PR TITLE
event should not work on iframe content (closes #1791, closes #1822 in testcafe)

### LINKED ISSUE #1791: Mouse events in iframe raise not correctly

### LINKED ISSUE #1822: Fetch Calls Removes Authorization Header
Hi guys. I believe this issue is back, or hasn't been fully resolved. I am using TestCafe and I have an API call that errors with `401 (Unauthorized)` and it's due to the Authorization header is being removed from my Fetch calls. jQuery works fine, leaving all headers in tact.

**Current Behavior**
* TestCafe logs in (jQuery ajax -- works)
* TestCafe get user personal info (jQuery ajax -- works)
* TestCafe gets user projects (Fetch call -- **breaks, 401, no authorization header**)

**Expected Behavior**
* TestCafe logs in (jQuery ajax -- works)
* TestCafe get user personal info (jQuery ajax -- works)
* TestCafe gets user projects (Fetch call -- _**works**_)

TestCafe version: 0.23.1
Node version: 8.11.4
Browser: Chrome and Firefox (haven't tested Edge and IE yet)
OS: WIndows 10

### PR DESCRIPTION
**Pull request by AlexKamaev**

### CODE REVIEW

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

File: test/client/fixtures/sandbox/event/event-test.js [hunk 1]
```diff
@@ -336,3 +346,134 @@ test('event.preventDefault call should change the event.defaultPrevented propert
...
+
+            start();
+        });
+
+});
+
+asyncTest('hover style in iframe', function () {
+    return createTestIframe()
+        .then(function (iframe) {
+            var $style  = $('<style>').appendTo('body');
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/event/event-test.js]: Don't use jquery for elements and property manipulation.

File: src/client/utils/position.js [hunk 2]
```diff
@@ -226,6 +226,19 @@ export function getElementRectangle (el) {
     return rectangle;
 }
 
+export function isPositionInsideElement (el, x, y) {
```
Comment (miherlosev) [inline src/client/utils/position.js]: `export function shouldRaiseMouseoverInsideIframe (iframe, { x, y })`

File: src/client/sandbox/event/hover.js [hunk 3]
```diff
@@ -56,6 +58,14 @@ export default class HoverSandbox extends SandboxBase {
         return jointParent;
     }
 
+    _onHover ({ target, clientX, clientY }) {
+        const isIframeContent = domUtils.getTagName(target) === 'iframe' && positionUtils.isPositionInsideElement(target, clientX, clientY);
```
Comment (miherlosev) [inline src/client/sandbox/event/hover.js]: 1)Convert expression
 `domUtils.getTagName(target) === 'iframe' && positionUtils.isPositionInsideElement(target, clientX, clientY)` 
to utility function `isPositionInsideIframe(el, {x, y})` and move this to the `src/client/utils/position.js` file.

2)Merge `onHover` and `_hover` function together. And rewrite using fast forward paradigm
```js
_hover() {
 const isPositionIsInIframe = postionUtils.isInIframe(el, x, y);
 const shouldMarkElement = browserUtils.isIE && isPositionIsInIframe;

if (!shouldMarkElement)
  return;

....
}

```

File: src/client/utils/position.js [hunk 4]
```diff
@@ -226,6 +226,19 @@ export function getElementRectangle (el) {
...
+    const rect    = getElementRectangle(el);
+    const borders = styleUtils.getBordersWidth(el);
+    const padding = styleUtils.getElementPadding(el);
+
+    const left   = rect.left + borders.left + padding.left;
+    const top    = rect.top + borders.top + padding.top;
+    const right  = rect.left + rect.width - borders.right - padding.right;
```
Comment (miherlosev) [inline src/client/utils/position.js]: Add comment for this line

File: test/client/fixtures/sandbox/event/event-test.js [hunk 5]
```diff
@@ -314,6 +315,15 @@ test('should not wrap invalid event handlers (GH-1251)', function () {
         });
 
         strictEqual(listeningCtx.getEventCtx(target, 'click').wrappers.length, storedHandlerWrappersCount);
+
+        handlers.forEach(function (handler) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/event/event-test.js]: Why do we need a `try/catch` statement?

Comment (AlexKamaev) [reply test/client/fixtures/sandbox/event/event-test.js]: It is a test for invalid event handlers. See the line above: `var handlers = [void 0, 1, null, 'str', {}];`. The test adds some wrong event handlers, but does not remove them, so it leads to problems with next texts. I've added code which removes handlers in the same manner as code which adds handlers

File: src/client/sandbox/event/hover.js (hunk 3 above)
Comment (AlexKamaev) [reply src/client/sandbox/event/hover.js]: 1) ok
2) I've separated them intentionally, because `_onHover` method takes `x,y` params while `_hover` is just api method without any extra params. Besides `_hover` is used in our tests

File: src/client/sandbox/event/simulator.js [hunk 6]
```diff
@@ -529,6 +529,9 @@ export default class EventSimulator {
     }
 
     _dispatchMouseRelatedEvents (el, args, dataTransfer) {
+        if (shouldIgnoreMouseEventInsideIframe(el, args.clientX, args.clientY) && args.type !== 'mouseover' && args.type !== 'mouseenter')
```
Comment (LavrovArtem) [inline src/client/sandbox/event/simulator.js]: I think that the type conditions should be the first for performance improvement.
