### PR TITLE
fix events names (close #678)

### LINKED ISSUE #678: Rename Hammerhead.EVENTS.xhrSend, Hammerhead.EVENTS.fetchSend to ...Sent

### PR DESCRIPTION
**Pull request by miherlosev**
@churkin @LavrovArtem 

Rename:
`XHR_SEND_EVENT` -> `XHR_SENT_EVENT`
`FETCH_REQUEST_SEND_EVENT` -> `FETCH_REQUEST_SENT_EVENT`

Now, all event ends with `_EVENT` postfix.

### CODE REVIEW

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/xhr.js [hunk 1]
```diff
@@ -95,7 +95,7 @@ export default class XhrSandbox extends SandboxBase {
         xmlHttpRequestProto.send = function () {
             var xhr = this;
 
-            xhrSandbox.emit(xhrSandbox.XHR_SEND_EVENT, { xhr });
+            xhrSandbox.emit(xhrSandbox.XHR_SENT_EVENT, { xhr });
```
Comment (churkin) [inline src/client/sandbox/xhr.js]: XHR not sent yet

Comment (miherlosev) [inline src/client/sandbox/xhr.js]: Yes, you are right. 
I propose to rename event as `XHR_BEFORE_SEND_EVENT`. 
/cc @LavrovArtem @churkin

**Comment by miherlosev** [comment]
Problem in tests under MicrosoftEdge. I'm investigating the problem...

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
@testcafe-build-bot \retest
