### PR TITLE
Bump version (v17.1.15); Fix `An uncaught exception is thrown when using fetch, Request and a data: URL` (close #2428) + refactoring

### LINKED ISSUE #2428: An uncaught exception is thrown when using fetch, Request and a data: URL
### What is your Scenario?
Test a page that uses Web Workers and `fetch` with a `data:` URL. 
 
### What is the Current behavior?
An uncaught error is thrown:
```
worker-hammerhead.js:1 Uncaught (in promise) TypeError: Cannot read property 'destUrl' of null
    at Function.t._sameOriginCheck (worker-hammerhead.js:1)
    at r.fetch (worker-hammerhead.js:1)
```
 
### What is the Expected behavior?
Ther should be no error (as it was in TestCafe 1.9.1).
 
##### test.html
```html
<html>
  <head>
    <title></title>
  </head>
  <body id="hehe">
    <input id="hehe" type="email"/>
    <script>
      new Worker('w.js');
    </script>
  </body>
</html>

```

##### w.js
```js
(async () => {
    console.log(await fetch(new Request('data:text/javascript;base64,KGFzeW5jICgpID0+IHsKICAgIGNvbnNvbGUubG9nKGF3YWl0IGZldGNoKCdodHRwczovL2FwaS5naXRodWIuY29tL3VzZXJzL29jdG9jYXQnKSkKfSkoKQ==')))
})()
```

### Steps to Reproduce:

1. Go to: ...
2. Execute this command: ...
3. See the error: ...
 
### Your Environment details:

* node.js version:                    12.0.0
* browser name and version: Chrome 84
* platform and version:          Windows 10
* other:

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Review by AndreyBelym — APPROVED** [review]

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

File: src/client/sandbox/node/window.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ import {
     parseProxyUrl,
     convertToProxyUrl,
     stringifyResourceType,
-    resolveUrlAsDest
+    resolveUrlAsDest, getDestinationUrl
```
Comment (miherlosev) [inline src/client/sandbox/node/window.ts:17]: Move to new line.

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/sandbox/node/window.ts (hunk 1 above)
Comment (miherlosev) [reply src/client/sandbox/node/window.ts:17]: Also, update `package.json` and then publish a new version.

**Review by miherlosev — APPROVED** [review]
