### PR TITLE
fix `window.Blob returns a wrong result when Array of ArrayBuffer is passed as parameter` (close #1599)

### LINKED ISSUE #1599: window.Blob returns a wrong result when Array of ArrayBuffer is passed as parameter
https://stuk.github.io/jszip/documentation/howto/read_zip.html
```
file.async('blob')
```
returns a blob with the content of `[object ArrayBuffer]` instead of the real result.

we are using this library to fetch all our images that are above the fold in a zip so currently they are broken:
image

### PR DESCRIPTION
**Pull request by Farfurix**
### References
https://github.com/DevExpress/testcafe-hammerhead/issues/1599
https://github.com/DevExpress/testcafe-hammerhead/issues/1610

### Changes
1. Fix data mime-type definition in the overridden `Blob` constructor in case of `options.type=''`

### `DataView` browser native behavior
```javascript
new DataView(new ArrayBuffer(2)); // [object Object] in IE11;
                                  // [object DataView] in Chrome, Firefox, Edge on Win 10

ArrayBuffer.isView(new DataView(new ArrayBuffer(2))); // true

var b = new Blob([new DataView(new ArrayBuffer(2))]); // InvalidStateError in IE11;
                                                      // OK in Chrome, Firefox, Edge on Win 10

var b = new Blob([new DataView(new ArrayBuffer(2)).buffer]); // [object Blob]{size: 2, type: ""}
```
fix test/client/fixtures/sandbox/node/classes-test.js:
```javascript
else if (testCase.type === 'DataView') {
    ...
    data = browserUtils.isIE11 ? dataView.buffer : dataView;
}
...
var resultBlob = new Blob([data], { type: '' });
```

### `TypedArray` test case
We check only `Uint8Array` that is used in code

### Notes
https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob

> var aBlob = new Blob( array[, options]);
> array is an Array of ArrayBuffer, ArrayBufferView, Blob, DOMString objects, or a mix of any of such objects, that will be put inside the Blob. DOMStrings are encoded as UTF-8.

https://developer.mozilla.org/en-US/docs/Web/API/Blob:
> The only way to read content from a Blob is to use a FileReader. The following code reads the content of a Blob as a typed array.

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypedArray
> where TypedArray() is one of: 
> Int8Array();
> Uint8Array();
> Uint8ClampedArray();
> Int16Array();
> Uint16Array();
> Int32Array();
> Uint32Array();
> Float32Array();
> Float64Array();

https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView
> ...
> DataView

### CODE REVIEW

File: test/client/fixtures/sandbox/node/classes-test.js [hunk 1]
```diff
@@ -22,6 +23,160 @@ if (window.PerformanceNavigationTiming) {
     });
 }
 
+test('window.Blob([data], { type: \'\' }) should return correct result for all possible data type cases (ArrayBuffer, TypedArray, ...) (GH-1599)', function () {
+    var testCases = [
+        // Image types
+        {
+            mime:      'image/x-icon',
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/node/classes-test.js]: You should not validate mime types. You need to check all Array like types as blob arguments.
Rewrite test as:
```js
Pseudo code

var data = {
    mime: '...',
    signature: '...'
};

['ArrayBuffer', 'Uint8Array' and etc.].forEach(type => {
    data = ... //convert data to an appropriate type
    check(window.Blob(data) 
} )
```

File: src/client/utils/dom.js [hunk 2]
```diff
@@ -636,15 +637,22 @@ export function isPerformanceNavigationTiming (entry) {
...
         return true;
 
-    return array[0] && IS_ARRAY_BUFFER_RE.test(instanceToString(array[0]));
+    return data && IS_ARRAY_BUFFER_RE.test(instanceToString(data));
 }
 
-export function isViewData (array) {
-    return ArrayBuffer.isView(array[0]);
+export function isArrayBufferView (data) {
+    return ArrayBuffer.isView(data);
```
Comment (miherlosev) [inline src/client/utils/dom.js]: return data && ArrayBuffer.isView(data);

File: src/client/utils/dom.js [hunk 3]
```diff
@@ -636,15 +637,22 @@ export function isPerformanceNavigationTiming (entry) {
     return instanceToString(entry) === '[object PerformanceNavigationTiming]';
 }
 
-export function isArrayBufferData (array) {
-    if (array[0] instanceof ArrayBuffer)
+export function isArrayBuffer (data) {
+    if (data instanceof ArrayBuffer)
```
Comment (miherlosev) [inline src/client/utils/dom.js]: All constructors (`ArrayBuffer`, `DataView`) should be stored in `nativeMethods` and used from it

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/sandbox/node/classes-test.js [hunk 4]
```diff
@@ -22,6 +23,121 @@ if (window.PerformanceNavigationTiming) {
     });
 }
 
+test('window.Blob([data], { type: \'\' }) should return correct result for all possible data type cases (GH-1599)', function () {
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/classes-test.js]: replace `\'\'` to `""`

File: test/client/fixtures/sandbox/node/classes-test.js [hunk 5]
```diff
@@ -22,6 +23,121 @@ if (window.PerformanceNavigationTiming) {
...
+    var pngExample = {
+        mime:      'image/bmp',
+        signature: [0x42, 0x4D]
+    };
+
+    var testCases = [
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/classes-test.js]: `testCases` is unnecessary

File: test/client/fixtures/sandbox/node/classes-test.js [hunk 6]
```diff
@@ -22,6 +23,121 @@ if (window.PerformanceNavigationTiming) {
...
+            type:        'Float64Array',
+            constructor: Float64Array.prototype.constructor
+        },
+        {
+            type:        'DataView',
+            constructor: DataView.prototype.constructor
+        }
+    ];
+
+    var createTestCasePromise = function (testCase) {
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/classes-test.js]: `var testConstructor = function (constructor) {`

File: test/client/fixtures/sandbox/node/classes-test.js [hunk 7]
```diff
@@ -22,6 +23,121 @@ if (window.PerformanceNavigationTiming) {
...
+        return new Promise(function (resolve) {
+            var arrayBuffer;
+            var data;
+            var typedArray;
+            var i;
+
+            if (testCase.type === 'ArrayBuffer') {
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/classes-test.js]: `constructor === ArrayBuffer`

File: test/client/fixtures/sandbox/node/classes-test.js [hunk 8]
```diff
@@ -22,6 +23,121 @@ if (window.PerformanceNavigationTiming) {
...
+        });
+    };
+
+    var promises = [];
+
+    testCases.forEach(function (testCase) {
+        promises.push(createTestCasePromise(testCase));
+    });
+
+    return Promise.all(promises);
```
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/node/classes-test.js]:
```js
return Promise.all([
    testConstructor(Uint8Array),
    ...
    testConstructor(DataView)
])
```

File: test/client/fixtures/utils/dom-test.js [hunk 9]
```diff
@@ -192,6 +192,35 @@ if (window.PerformanceNavigationTiming) {
...
+    ok(domUtils.isArrayBufferView(new Float64Array(0)), 'Float64Array');
+    /*eslint-disable no-undefined*/
+    ok(!domUtils.isArrayBufferView(undefined), 'undefined');
+    /*eslint-enable no-undefined*/
+});
+
+test('isDataView', function () {
+    ok(domUtils.isDataView(new DataView(new ArrayBuffer(0))), 'DataView');
+    /*eslint-disable no-undefined*/
+    ok(!domUtils.isDataView(undefined), 'undefined');
```
Comment (LavrovArtem) [inline test/client/fixtures/utils/dom-test.js]: use `void 0` instead of `undefined` and remove eslint comments

File: test/client/fixtures/utils/dom-test.js [hunk 10]
```diff
@@ -192,6 +192,35 @@ if (window.PerformanceNavigationTiming) {
...
+    ok(domUtils.isArrayBufferView(new Uint8Array(0)), 'Uint8Array');
+    ok(domUtils.isArrayBufferView(new Uint8ClampedArray(0)), 'Uint8ClampedArray');
+    ok(domUtils.isArrayBufferView(new Int16Array(0)), 'Int16Array');
+    ok(domUtils.isArrayBufferView(new Uint16Array(0)), 'Uint16Array');
+    ok(domUtils.isArrayBufferView(new Int32Array(0)), 'Int32Array');
+    ok(domUtils.isArrayBufferView(new Uint32Array(0)), 'Uint32Array');
+    ok(domUtils.isArrayBufferView(new Float32Array(0)), 'Float32Array');
+    ok(domUtils.isArrayBufferView(new Float64Array(0)), 'Float64Array');
+    /*eslint-disable no-undefined*/
+    ok(!domUtils.isArrayBufferView(undefined), 'undefined');
```
Comment (LavrovArtem) [inline test/client/fixtures/utils/dom-test.js]: use `void 0` instead of `undefined` and remove eslint comments

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

File: test/client/fixtures/utils/dom-test.js [hunk 11]
```diff
@@ -192,6 +192,29 @@ if (window.PerformanceNavigationTiming) {
...
 }
 
+test('isArrayBuffer', function () {
+    ok(domUtils.isArrayBuffer(new ArrayBuffer(0)), 'ArrayBuffer');
+    ok(!domUtils.isArrayBuffer(void 0), 'undefined');
+});
+
+test('isArrayBufferView', function () {
+    ok(domUtils.isArrayBufferView(new Int8Array(0)), 'Int8Array');
+    ok(domUtils.isArrayBufferView(new Uint8Array(0)), 'Uint8Array');
```
Comment (miherlosev) [inline test/client/fixtures/utils/dom-test.js]: Why does we test all Array like data types? We need test only for two cases: true and false

File: test/client/fixtures/sandbox/node/classes-test.js [hunk 12]
```diff
@@ -22,6 +23,78 @@ if (window.PerformanceNavigationTiming) {
...
+            };
+
+            fileReader.readAsArrayBuffer(resultBlob);
+        });
+    };
+
+    return Promise.all([
+        testConstructor(ArrayBuffer),
+        testConstructor(Int8Array),
+        testConstructor(Uint8Array),
```
[the remark this answers is not in the document]
Comment (LavrovArtem) [reply test/client/fixtures/sandbox/node/classes-test.js]: Yes, I agree

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest

**Comment by Farfurix** [comment]
@testcafe-build-bot \retest
