### PR TITLE
fix `The querySelector function is overridden incorrectly` (close #1131, close #1159)

### LINKED ISSUE #1131: The querySelector function is overridden incorrectly
http://www.caranddriver.com/bmw/3-series/specs/2017/3-series-Sedan/387943

Stack trace:
```js
TypeError: Cannot read property 'parentNode' of null
    at t.insertBefore (home.js?a3fb2fa…:formatted:38660)
    at e.loadBackfiresUser (home.js?a3fb2fa…:formatted:11287)
    at e.onUniversalInit (home.js?a3fb2fa…:formatted:32144)
    at new e (home.js?a3fb2fa…:formatted:32124)
    at t.createInternal (home.js?a3fb2fa…:formatted:78120)
    at t.e.create (home.js?a3fb2fa…:formatted:1673)
    at t.createInternal (home.js?a3fb2fa…:formatted:78069)
    at t.e.create (home.js?a3fb2fa…:formatted:1673)
    at e.create (home.js?a3fb2fa…:formatted:1496)
    at t.bootstrap (home.js?a3fb2fa…:formatted:17343)
```

### LINKED ISSUE #1159: We need to refactor the duplicate code in the ShadowUI
See `_overrideElementMethods` and `_overrideDocumentMethods` methods.

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

File: src/client/sandbox/shadow-ui.js [hunk 1]
```diff
@@ -155,7 +155,17 @@ export default class ShadowUI extends SandboxBase {
...
-            return ShadowUI._filterElement(nativeMethods.querySelector.apply(this, args));
+            var element = nativeMethods.querySelector.apply(this, args);
+
+            if (!element)
+                return null;
+
+            if (ShadowUI._filterElement(element))
+                return element;
+
+            var elements = ShadowUI._filterNodeList(nativeMethods.querySelectorAll.apply(this, arguments));
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: - We don't need filter all nodes. We can check each node until first non-shadow ui element.
- Move code to separate method `this.overridenMethods.querySelector`

File: src/client/sandbox/shadow-ui.js [hunk 2]
```diff
@@ -64,6 +64,32 @@ export default class ShadowUI extends SandboxBase {
         return ShadowUI._filterList(styleSheetList, item => ShadowUI._filterElement(item.ownerNode));
     }
 
+    static _filterFirstNonShadowElement (nodeList) {
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: ` _getFirstNonShadowElement`

File: src/client/sandbox/shadow-ui.js [hunk 3]
```diff
@@ -64,6 +64,32 @@ export default class ShadowUI extends SandboxBase {
...
+            var el = ShadowUI._filterElement(nodeList[i]);
+
+            if (el)
+                return nodeList[i];
+        }
+
+        return null;
+    }
+
+    static _createWrapperForQuerySelectorFn (nativeQuerySelectorFnName, nativeQuerySelectorAllFnName) {
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: Lets' pass native functions instead of string names. It allows to write a little more readable code.

Also let's create structure that will contain all `createWrapperFor***` functions.
```js
//declaration

this.createWrapperFor.querySelector = ...
// This will be added later - https://github.com/DevExpress/testcafe-hammerhead/issues/1159
this.createWrapperFor.getElementsByTagName = ...
this.createWrapperFor.getElementsByClassName = ...
....

//usage

docProto.querySelector = this.createWrapperFor.querySelector(nativeMethods.querySelector, nativeMethods.querySelectorAll)
```

**Comment by LavrovArtem** [comment]
FPR

File: test/client/fixtures/sandbox/shadow-ui-test.js [hunk 4]
```diff
@@ -340,11 +340,22 @@ test('body.querySelector', function () {
     pageElem.className = 'test-class cli2';
     document.body.appendChild(pageElem);
 
-    uiElem   = document.body.querySelector('.cl1');
+    uiElem   = document.body.querySelector('.cli');
     pageElem = document.body.querySelector('.cli2');
 
     ok(!uiElem);
     strictEqual(pageElem.id, 'pageElem');
+
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/shadow-ui-test.js]: Let's create a separate test for document and element's querySelector with th following scenario:
- create shadowUI and regular elements with equal classes.
- insert element so that shadow is first element and reqular is second
- querySelector elements by class and check that shadowUI element is skipping and found the second reqular element

File: test/client/fixtures/sandbox/shadow-ui-test.js [hunk 5]
```diff
@@ -340,11 +340,22 @@ test('body.querySelector', function () {
...
+    uiElem = document.createElement('div');
+
+    uiElem.className = 'ui-div' + SHADOW_UI_CLASSNAME.postfix;
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/shadow-ui-test.js]: For marking elements as shadow use the public function ShadowUI.addClass

File: src/client/sandbox/shadow-ui.js (hunk 3 above)
Comment (LavrovArtem) [inline src/client/sandbox/shadow-ui.js]: We can't pass the native functions instead of string names because it saves in closure and we can't test them with the `checkNativeFunctionArgs` function.

File: src/client/sandbox/shadow-ui.js [hunk 6]
```diff
@@ -28,6 +28,7 @@ export default class ShadowUI extends SandboxBase {
         this.root                    = null;
         this.lastActiveElement       = null;
         this.uiStyleSheetsHtmlBackup = null;
+        this.createWrapperFor        = ShadowUI._generateWrapperFunctions();
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: ShadowUI._createWrapperFunctions

File: test/client/fixtures/sandbox/shadow-ui-test.js [hunk 7]
```diff
@@ -537,6 +537,28 @@ test('querySelectorAll', function () {
     strictEqual(elems[0].id, 'pageElem');
 });
 
+test('document.querySelector and head.querySelector', function () {
+    var meta       = document.createElement('meta');
+    var shadowMeta = document.createElement('meta');
+
+    meta.className       = 'metas';
+    shadowMeta.className = 'metas ' + SHADOW_UI_CLASSNAME.charset;
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/shadow-ui-test.js]: ShadowUI.addClass(shadowMeta, 'metas');

File: test/client/fixtures/sandbox/shadow-ui-test.js [hunk 8]
```diff
@@ -537,6 +537,28 @@ test('querySelectorAll', function () {
     strictEqual(elems[0].id, 'pageElem');
 });
 
+test('document.querySelector and head.querySelector', function () {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/shadow-ui-test.js]: `test(querySelector call should return a first non-shadowUI element (GH-1131)`

File: test/client/fixtures/sandbox/shadow-ui-test.js (hunk 7 above)
Comment (LavrovArtem) [inline test/client/fixtures/sandbox/shadow-ui-test.js]: It will add one `metas-hammerhead-shadow-ui` class, but I need to add two class `metas` and `SHADOW_UI_CLASSNAME.charset`

Comment (miherlosev) [inline test/client/fixtures/sandbox/shadow-ui-test.js]: Ok. You are right

File: src/client/sandbox/shadow-ui.js [hunk 9]
```diff
@@ -28,6 +28,7 @@ export default class ShadowUI extends SandboxBase {
         this.root                    = null;
         this.lastActiveElement       = null;
         this.uiStyleSheetsHtmlBackup = null;
+        this.createWrapperFor        = ShadowUI._createFunctionWrappers();
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: Let's rename to `this.functionWrappers`

Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: After discussing we decide to keep old property name

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
rebase with master branch

**Comment by miherlosev** [comment]
FPR. ping @churkin

File: src/client/sandbox/shadow-ui.js (hunk 9 above)
Comment (churkin) [inline src/client/sandbox/shadow-ui.js]: May be `wrapperCreators` ?

Comment (LavrovArtem) [inline src/client/sandbox/shadow-ui.js]: Looks good.
`this.wrapperCreators        = ShadowUI._createWrapperCreators();`
@miherlosev What do you think?

Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: Ok

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest
