### PR TITLE
fix `React error on a DevExtreme Demo Page` (close #2000)

### LINKED ISSUE #2000: React error on a DevExtreme Demo Page
Open http://localhost:1401/sB8yF3fY7/https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/ in Playground. Result:
```js
hammerhead.js:10808 Invariant Violation: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:435
    at i (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:559)
    at Object.Bl [as createPortal] (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:102229)
    at t.value (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:87:7890)
    at t.value (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:87:8188)
    at Ra (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:63993)
    at ja (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:63788)
    at Ia (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:67622)
    at qi (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:91822)
    at $i (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:92206)
window.console.(anonymous function) @ hammerhead.js:10808
fi @ index.js?v=1553778960:78
Ci.n.callback @ index.js?v=1553778960:78
oi @ index.js?v=1553778960:78
ri @ index.js?v=1553778960:78
Hi @ index.js?v=1553778960:78
Bi @ index.js?v=1553778960:78
(anonymous) @ index.js?v=1553778960:78
t.unstable_runWithPriority @ index.js?v=1553778960:87
Nl @ index.js?v=1553778960:78
Rl @ index.js?v=1553778960:78
Tl @ index.js?v=1553778960:78
xl @ index.js?v=1553778960:78
Ji @ index.js?v=1553778960:78
Ml @ index.js?v=1553778960:78
Gl @ index.js?v=1553778960:78
Vl.render @ index.js?v=1553778960:78
(anonymous) @ index.js?v=1553778960:78
Il @ index.js?v=1553778960:78
Wl @ index.js?v=1553778960:78
render @ index.js?v=1553778960:78
(anonymous) @ index.js?v=1553778960:115
(anonymous) @ index.js?v=1553778960:115
n @ index.js?v=1553778960:2
(anonymous) @ index.js?v=1553778960:62
n @ index.js?v=1553778960:2
(anonymous) @ index.js?v=1553778960:2
(anonymous) @ index.js?v=1553778960:2
index.js?v=1553778960:78 Uncaught Invariant Violation: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:435
    at i (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:559)
    at Object.Bl [as createPortal] (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:102229)
    at t.value (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:87:7890)
    at t.value (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:87:8188)
    at Ra (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:63993)
    at ja (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:63788)
    at Ia (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:67622)
    at qi (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:91822)
    at $i (http://localhost:1401/sB8yF3fY7!s!utf-8/https://devexpress.github.io/devextreme-reactive/react/grid/demos/dist/index.js?v=1553778960:78:92206)
```

No errors without hammerhead

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

File: src/client/utils/html.ts [hunk 1]
```diff
@@ -315,8 +315,14 @@ export function processHtml (html, options: ProcessHTMLOptions = {}) {
 
         if (!parentTag) {
             if (htmlElements.length) {
-                for (const htmlElement of htmlElements)
-                    nativeMethods.insertAdjacentHTML.call(htmlElement, 'afterbegin', INIT_SCRIPT_FOR_IFRAME_TEMPLATE);
+                for (const htmlElement of htmlElements) {
+                    const firstScriptOrStyle = nativeMethods.elementQuerySelector.call(htmlElement, 'script,link[rel="stylesheet"]');
+
+                    if (firstScriptOrStyle)
+                        nativeMethods.insertAdjacentHTML.call(firstScriptOrStyle, 'beforebegin', INIT_SCRIPT_FOR_IFRAME_TEMPLATE);
```
Comment (miherlosev) [inline src/client/utils/html.ts]: I guess we can create an enumeration contained the insert element position ('beforebegin', 'afterbegin' and etc.) because these string constants are used in several files.

File: src/client/utils/html.ts [hunk 2]
```diff
@@ -315,8 +315,14 @@ export function processHtml (html, options: ProcessHTMLOptions = {}) {
 
         if (!parentTag) {
             if (htmlElements.length) {
-                for (const htmlElement of htmlElements)
-                    nativeMethods.insertAdjacentHTML.call(htmlElement, 'afterbegin', INIT_SCRIPT_FOR_IFRAME_TEMPLATE);
+                for (const htmlElement of htmlElements) {
+                    const firstScriptOrStyle = nativeMethods.elementQuerySelector.call(htmlElement, 'script,link[rel="stylesheet"]');
```
Comment (miherlosev) [inline src/client/utils/html.ts]: Create a constant on the module level:
const SCRIPT_AND_STYLE_SELECTOR = 'script,link[rel="stylesheet"]';

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
Tests were passed.

File: src/client/utils/html.ts [hunk 3]
```diff
@@ -71,6 +71,15 @@ export const INIT_SCRIPT_FOR_IFRAME_TEMPLATE = createSelfRemovingScript(`
         parentHammerhead.sandbox.onIframeDocumentRecreated(window.frameElement);
 `);
 
+const SCRIPT_AND_STYLE_SELECTOR = 'script,link[rel="stylesheet"]';
+
+export enum InsertPosition {
```
Comment (miherlosev) [inline src/client/utils/html.ts]: Move to a separate file and use it in all necessary places.
