### PR TITLE
fix `https://www.starbucks.com - login doesn't work` (close #905)

### LINKED ISSUE #905: https://www.starbucks.com - login doesn't work

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot  \retest

File: test/client/fixtures/sandbox/xhr-test.js [hunk 1]
```diff
@@ -142,3 +143,22 @@ if (!browserUtils.isIE9) {
...
+    strictEqual(getProperty(document, 'cookie'), '');
+
+    xhr.open('GET', '/xhr-set-cookie-header-test/', true);
+    xhr.addEventListener('readystatechange', function () {
+        if (this.readyState === this.DONE) {
+            strictEqual(getProperty(document, 'cookie'), 'hello=world');
+            strictEqual(xhr.getResponseHeader(XHR_HEADERS.setCookie), null);
+            strictEqual(xhr.getAllResponseHeaders().indexOf(XHR_HEADERS.setCookie), -1);
+            strictEqual(xhr.getAllResponseHeaders().indexOf('hello=world'), -1);
+
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/xhr-test.js]: Should restore initial cookie value

File: src/request-pipeline/xhr/headers.js [hunk 2]
```diff
@@ -9,5 +9,6 @@ export default {
     corsSupported:           'x-hammerhead|xhr|cors-supported-header',
     withCredentials:         'x-hammerhead|xhr|with-credentials-header',
     origin:                  'x-hammerhead|xhr|origin',
```
Comment (miherlosev) [inline src/request-pipeline/xhr/headers.js]: Rename to `x-hammerhead|xhr|cors-supported`, `x-hammerhead|xhr|with-credentials`.
Do this in the current pull request because it is very simple

Comment (miherlosev) [inline src/request-pipeline/xhr/headers.js]: Also we need to create separate issues for fetch, image, script and style requests

Comment (LavrovArtem) [inline src/request-pipeline/xhr/headers.js]: How we can get the `set-cookie` header from image, script and style requests?

Comment (miherlosev) [inline src/request-pipeline/xhr/headers.js]: Sorry. Only for fetch request

Comment (LavrovArtem) [inline src/request-pipeline/xhr/headers.js]: https://github.com/DevExpress/testcafe-hammerhead/issues/962

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/cookie.js [hunk 3]
```diff
@@ -100,7 +100,7 @@ export default class CookieSandbox extends SandboxBase {
         return this._getSettings().cookie;
     }
 
-    setCookie (document, value) {
+    setCookie (document, value, onlyClient) {
```
Comment (churkin) [inline src/client/sandbox/cookie.js]: `syncWithServer` ?

File: src/client/sandbox/node/index.js [hunk 4]
```diff
@@ -51,6 +51,7 @@ export default class NodeSandbox extends SandboxBase {
 
             el[INTERNAL_PROPS.processedContext] = this.window;
 
+            // NOTE: We need to reprocess url attribute of element, if it's moved to different window
```
Comment (churkin) [inline src/client/sandbox/node/index.js]: More details, pls.

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Comment by churkin** [comment]
lgtm
