### PR TITLE
fix `Service workers don't receive the 'fetch' events because of our URL-rewriting mechanism` (close #2412)

### LINKED ISSUE #2412: Service workers don't receive the 'fetch' events because of our URL-rewriting mechanism

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

File: src/client/worker/set-sw-settings-command.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+const SET_SW_SETTINGS = 'hammerhead|set-sw-settings';
```
Comment (miherlosev) [inline src/client/worker/set-sw-settings-command.ts:1]: `const SET_SERVICE_WORKER_SETTINGS = 'hammerhead|set-service-worker-settings'; `

File: src/client/worker/set-sw-settings-command.ts [hunk 2]
```diff
@@ -0,0 +1,3 @@
...
+
+export default SET_SW_SETTINGS;
```
Comment (miherlosev) [inline src/client/worker/set-sw-settings-command.ts:3]: Rename file to `set-settings-command` because it's located in `/worker` folder.

File: src/client/sandbox/node/window.ts [hunk 3]
```diff
@@ -654,28 +656,33 @@ export default class WindowSandbox extends SandboxBase {
...
-                    args[1].scope = getProxyUrl(args[1].scope, {
-                        resourceType: stringifyResourceType({ isScript: true })
-                    });
-                }
+                args[1] = { scope: '/' };
+
+                return nativeMethods.registerServiceWorker.apply(window.navigator.serviceWorker, args)
+                    .then(reg => {
+                        const parsedProxyUrl = parseProxyUrl(args[0]);
+                        const serviceWorker  = reg.installing || reg.waiting || reg.active;
```
Comment (miherlosev) [inline src/client/sandbox/node/window.ts:667]: Should we postpone sending the `set-settings` message until a service worker became active?

File: src/client/worker/service-worker-fetch.ts [hunk 4]
```diff
@@ -0,0 +1,96 @@
+//import { overrideDescriptor } from '../utils/property-overriding';
```
Comment (miherlosev) [inline src/client/worker/service-worker-fetch.ts:1]: Rename file to `fetch-event.ts`

File: src/client/worker/service-worker-fetch.ts [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
+
+export default function overrideFetchEvent () {
+    let waitSettingsPromise = new Promise((resolve, reject) => {
+        nativeMethods.windowAddEventListener.call(self, 'message', function onMessage (e: MessageEvent) {
+            const data = e.data;
+
+            if (data.cmd !== SET_SW_SETTINGS)
+                return;
+
+            const curentScope = self[INSTRUCTION.swScopeHeaderValue] !== void 0
```
Comment (miherlosev) [inline src/client/worker/service-worker-fetch.ts:31]: `const currentScope = ...`

File: src/client/worker/service-worker-fetch.ts [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+                : data.currentScope;
+
+            let scope = data.optsScope;
+
+            if (!scope)
+                scope = curentScope;
+            else if (!scope.startsWith(curentScope)) {
+                // @ts-ignore
+                self.registration.unregister();
+                reject(new Error('Wrong scope!'));
```
Comment (miherlosev) [inline src/client/worker/service-worker-fetch.ts:42]: As I understand, it's an internal error. Add a more service information to it: tested page url, scope and etc.

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/worker/service-worker-fetch.ts [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+            resolve();
+        });
+    });
+
+    nativeMethods.windowAddEventListener.call(self, 'fetch', (e: Event) => {
+        // @ts-ignore
+        const request        = e.request as Request;
+        const proxyUrl       = nativeMethods.requestUrlGetter.call(request);
+        const parsedProxyUrl = parseProxyUrl(proxyUrl);
+
```
Comment (miherlosev) [inline src/client/worker/service-worker-fetch.ts:62]: Declare variable and remove comment

`const isInternalRequest  = !parsedProxyUrl;`

File: src/client/worker/service-worker-fetch.ts [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+        // NOTE: It is internal request
+        if (!parsedProxyUrl) {
+            // @ts-ignore
+            e.respondWith(nativeMethods.fetch.call(self, request));
+            stopPropagation(e);
+
+            return;
+        }
+        // NOTE: Settings is not initialized
```
Comment (miherlosev) [inline src/client/worker/service-worker-fetch.ts:71]: ` // NOTE: Settings is not initialized yet`

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/worker/service-worker-fetch.ts [hunk 9]
```diff
@@ -0,0 +1,96 @@
...
+
+            nativeMethods.windowRemoveEventListener.call(self, 'message', onMessage);
+            stopPropagation(e);
+
+            waitSettingsPromise = null;
+            resolve();
+        });
+    });
+
+    nativeMethods.windowAddEventListener.call(self, 'fetch', (e: Event) => {
```
[the remark this answers is not in the document]
Comment (LavrovArtem) [reply src/client/worker/service-worker-fetch.ts:57]: error TS2304: Cannot find name 'FetchEvent'

File: src/client/sandbox/node/window.ts (hunk 3 above)
Comment (LavrovArtem) [reply src/client/sandbox/node/window.ts:667]: `ServiceWorkerRegistration` has no events for this.

File: src/client/worker/service-worker-fetch.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (miherlosev) [reply src/client/worker/service-worker-fetch.ts:57]: It looks like you need to plug `WebWorker` library to typescript compiler.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28342

The `FetchEvent` declaration exists in `node_modules/typescript/lib/lib.webworker.d.ts` file.

**Comment by LavrovArtem** [comment]
@testcafe-build-bot retest

File: test/client/config-qunit-server-app.js [hunk 10]
```diff
@@ -35,10 +35,15 @@ function fetchContent (req) {
 
         req.on('data', chunk => chunks.push(chunk));
         req.on('end', () => resolve(Buffer.concat(chunks).toString()));
-    });
+    });ServiceWorker.prototype.postMessage
```
Comment (miherlosev) [inline test/client/config-qunit-server-app.js:38]: Remove dev artifact.

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]

File: src/client/worker/fetch-event.ts [hunk 11]
```diff
@@ -0,0 +1,95 @@
...
+        const request           = e.request as Request;
+        const proxyUrl          = nativeMethods.requestUrlGetter.call(request);
+        const parsedProxyUrl    = parseProxyUrl(proxyUrl);
+        const isInternalRequest = !parsedProxyUrl;
+
+        if (!isInternalRequest) {
+            // @ts-ignore Chrome has a non-standard the "iframe" destination
+            const isPage = request.destination === 'document' || request.destination === 'iframe';
+
+            if (isPage) {
```
Comment (miherlosev) [inline src/client/worker/fetch-event.ts:78]: Rewrite as  `if (isPage && isCorrectScope(parsedProxyUrl.destResourceInfo))`

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/worker/fetch-event.ts (hunk 11 above)
Comment (LavrovArtem) [reply src/client/worker/fetch-event.ts:78]: I don't need to check the referrer if a request is a page with incorrect scope.

Comment (miherlosev) [reply src/client/worker/fetch-event.ts:78]: Yes, it's my mistake.

**Review by miherlosev — APPROVED** [review]

**Review by wentwrong — APPROVED** [review]
