### PR TITLE
fix `Service messages with cookies don't have time to come to server before new page is loaded` (close #1086)

### LINKED ISSUE #1086: Service messages with cookies don't have time to come to server before new page is loaded
It's simple example which reproduces this behouver:
```javascript
var http = require('http');

http.createServer(function(req, res) {
    switch (req.url) {
        case '/':
            return res.end(`
                <script>
                    document.cookie = 'hnet-lifetime=value';
                    document.cookie = 'hnet-session=value';

                    document.location.pathname = '/show-cookie';
                </script>
            `);
        case '/show-cookie':
            return res.end(req.headers.cookie);
        default:
            res.end('');
    }
}).listen(1993);
```
Without hammerhead:
image
With hammerhead:
image

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/cookie/server-sync.js [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+        this.activeReq   = null;
+
+        // NOTE: When unloading, we should switch to synchronous XHR to be sure that we won't lose any cookies.
+        nativeMethods.windowAddEventListener.call(window, 'beforeunload', () => this._beforeUnloadHandler(), true);
+    }
+
+    static _createXMLHttpRequest (isAsync) {
+        var xhr = XhrSandbox.createNativeXHR();
+
+        xhr.open('POST', settings.get().cookieSyncUrl, isAsync);
```
Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: Rename parameter to `async`.
It called as `async` in [documentation](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open)

Why do we need separate url for cookie synchronization?
I prefer to have an additional check in `Proxy._onServiceMessage` instead of adding the new service url.

File: src/client/sandbox/cookie/server-sync.js [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+        xhr.setRequestHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
+
+        return xhr;
+    }
+
+    static _isNoContentStatus (request) {
+        try {
+            // NOTE: XMLHTTPRequest implementation in MSXML HTTP does not handle HTTP responses
```
Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: Is there link to specification?

File: src/client/sandbox/cookie/server-sync.js [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+    static _createXMLHttpRequest (isAsync) {
+        var xhr = XhrSandbox.createNativeXHR();
+
+        xhr.open('POST', settings.get().cookieSyncUrl, isAsync);
+        xhr.setRequestHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
+
+        return xhr;
+    }
+
+    static _isNoContentStatus (request) {
```
Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: `has204StatusCode`

File: src/client/transport.js [hunk 4]
```diff
@@ -1,41 +1,22 @@
...
-            nativeMethods.setTimeout.call(window, () => {
-                this.useAsyncXhr = true;
-
-                return this.SWITCH_BACK_TO_ASYNC_XHR_DELAY;
-            });
-        }, true);
     }
 
-    static _createXMLHttpRequest (async) {
+    static _createXMLHttpRequest (isAsync) {
```
Comment (miherlosev) [inline src/client/transport.js]: rename to `async` back

File: src/client/sandbox/cookie/server-sync.js [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+            this.useAsyncXhr = true;
+        }, SWITCH_BACK_TO_ASYNC_XHR_DELAY);
+    }
+
+    _loadHandler (request) {
+        if (ServerSync._isNoContentStatus(request)) {
+            this.sendedQueue = null;
+            this.activeReq   = null;
+
+            if (this.queue.length > 0)
```
Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: `if (this.queue.length)`

File: test/client/fixtures/sandbox/cookie-test.js [hunk 6]
```diff
@@ -228,3 +194,27 @@ test('correct work with cookie with empty key (GH-899)', function () {
 
     transport.queuedAsyncServiceMsg = savedQueuedAsyncServiceMsg;
 });
+
+if (!browserUtils.isIOS) {
```
Comment (miherlosev) [inline test/client/fixtures/sandbox/cookie-test.js]: Add comment for this - 'Browsers on iOS platform doesn't support `beforeunload` event. We cann't use the `pagehide` event for cookie synchronization. Request for a new page will be handled earlier than sync xhr request was sent from `pagehide` event handler.'

File: src/client/sandbox/cookie/server-sync.js [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+import { stringify as stringifyJSON } from '../../json';
+import { isIE9 } from '../../utils/browser';
+
+const SWITCH_BACK_TO_ASYNC_XHR_DELAY = 2000;
+
+export default class ServerSync {
+    constructor () {
+        this.useAsyncXhr = true;
+        this.queue       = [];
+        this.sendedQueue = null;
```
Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: `sendedQueue` is Array. So let's intialize it as `this.sendedQueue = []`.

File: src/client/sandbox/cookie/server-sync.js [hunk 8]
```diff
@@ -0,0 +1,122 @@
...
+        }
+        catch (e) {
+            return false;
+        }
+    }
+
+    _beforeUnloadHandler () {
+        if (this.useAsyncXhr) {
+            this.useAsyncXhr = false;
+
```
Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: We have a complex logic in this place.
So, let's add comment:
`When active request is aborted we will send message queue to the server`

File: src/client/sandbox/cookie/server-sync.js [hunk 9]
```diff
@@ -0,0 +1,122 @@
...
+                this.activeReq.abort();
+        }
+
+        // NOTE: If the unloading was canceled, switch back to asynchronous XHR.
+        nativeMethods.setTimeout.call(window, () => {
+            this.useAsyncXhr = true;
+        }, SWITCH_BACK_TO_ASYNC_XHR_DELAY);
+    }
+
+    _loadHandler (request) {
```
Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: Lets' rename to `onRequestLoad` and `onRequestError` to differ with page handler `_beforeUnloadHandler`

File: src/client/sandbox/cookie/server-sync.js [hunk 10]
```diff
@@ -0,0 +1,122 @@
...
+    _sendQueue () {
+        var isAsyncRequest = this.useAsyncXhr;
+        var request        = ServerSync._createXMLHttpRequest(isAsyncRequest);
+
+        this.sendedQueue = this.queue;
+        this.queue       = [];
+        this.activeReq   = request;
+
+        if (isAsyncRequest) {
+            if (!isIE9) {
```
Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: Difficult to read. Let's move to the separate method `_attachRequestHandlers (request)`

File: src/proxy/index.js [hunk 11]
```diff
@@ -2,16 +2,17 @@ import Router from './router';
...
 import prepareShadowUIStylesheet from '../shadow-ui/create-shadow-stylesheet';
 
 // Const
-const CLIENT_SCRIPT = read('../client/hammerhead.js');
+const CLIENT_SCRIPT             = read('../client/hammerhead.js');
+const SESSION_IS_NOT_OPENED_ERR = 'Session is not opened in proxy';
 
 // Static
-function parseServiceMsg (body) {
+function parseJsonBody (body) {
```
Comment (miherlosev) [inline src/proxy/index.js]: `function parseAsJson (msg)`

File: src/client/sandbox/cookie/server-sync.js [hunk 12]
```diff
@@ -0,0 +1,122 @@
+import nativeMethods from '../../sandbox/native-methods';
+import XhrSandbox from '../../sandbox/xhr';
+import settings from '../../settings';
+import { stringify as stringifyJSON } from '../../json';
+import { isIE9 } from '../../utils/browser';
+
+const SWITCH_BACK_TO_ASYNC_XHR_DELAY = 2000;
+
+export default class ServerSync {
```
Comment (LavrovArtem) [inline src/client/sandbox/cookie/server-sync.js]: May be `CookieSync` ?

Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: Let it be.
Then rename `synchronize` method to `perform`.
Usage
```js
cookieSync.perform({})
```

File: src/client/sandbox/cookie/server-sync.js (hunk 7 above)
Comment (LavrovArtem) [inline src/client/sandbox/cookie/server-sync.js]: But we don't change this array, we just assign him [another array](https://github.com/DevExpress/testcafe-hammerhead/pull/1128/files#diff-e693d417f378fee695a11ea6f7e61f78R78).
Therefore, it just create unnecessary empty array if we initialize it as `this.sendedQueue = []`.

Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: Ok

File: src/client/sandbox/cookie/server-sync.js (hunk 1 above)
Comment (LavrovArtem) [inline src/client/sandbox/cookie/server-sync.js]: image
In some code editors we have wrong highlight because `async` is a keyword in the es7 standard.

Comment (LavrovArtem) [inline src/client/sandbox/cookie/server-sync.js]: We need separate url for cookie synchronization because it realize another logic and in the future we well be use this url for the WebSocket connection.

File: src/client/sandbox/cookie/server-sync.js (hunk 12 above)
Comment (LavrovArtem) [inline src/client/sandbox/cookie/server-sync.js]: ok

File: src/client/sandbox/cookie/server-sync.js (hunk 1 above)
Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: At this moment we are not sure WebSocket helps us with cookie sync in iOS browsers. 
So, I propose to move on separate service url in PR are fixed iOS related issue.

File: src/client/sandbox/cookie/server-sync.js (hunk 2 above)
Comment (LavrovArtem) [inline src/client/sandbox/cookie/server-sync.js]: https://stackoverflow.com/questions/10046972/msie-returns-status-code-of-1223-for-ajax-request

Comment (miherlosev) [inline src/client/sandbox/cookie/server-sync.js]: I don't find link to specification or official docs related with Internet Explore. 
Let leave it as is.

File: src/client/transport.js (hunk 4 above)
Comment (LavrovArtem) [inline src/client/transport.js]: I was comment it above.

Comment (miherlosev) [inline src/client/transport.js]: Ok

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

File: src/client/sandbox/cookie/cookie-sync.js [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+        catch (e) {
+            return false;
+        }
+    }
+
+    _beforeUnloadHandler () {
+        if (this.useAsyncXhr) {
+            this.useAsyncXhr = false;
+
+            // NOTE: When active request is aborted we will send message queue to the server
```
Comment (miherlosev) [inline src/client/sandbox/cookie/cookie-sync.js]: Let's improve the comment.
We abort the current async request and resend message queue to a server using sync request.

File: src/client/sandbox/cookie/cookie-sync.js [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+            this._sendQueue();
+        }
+    }
+
+    _attachRequestHandlers (request) {
+        if (isIE9) {
+            // NOTE: Aborting ajax requests in IE9 does not raise the error, abort or timeout events.
+            // Getting the status code raises the c00c023f error.
+            request.addEventListener('readystatechange', () => {
+                if (request.readyState !== request.DONE)
```
Comment (miherlosev) [inline src/client/sandbox/cookie/cookie-sync.js]: A little easier:

```js
if (request.readyState === request.DONE)
    this._onRequestLoad(request);
```

File: src/client/sandbox/cookie/index.js [hunk 15]
```diff
@@ -1,15 +1,20 @@
...
+import { isCrossDomainWindows } from '../../utils/dom';
+import trim from '../../../utils/string-trim';
+import INTERNAL_PROPS from '../../../processing/dom/internal-properties';
+import BYTES_PER_COOKIE_LIMIT from '../../../session/cookie-limit';
 
 export default class CookieSandbox extends SandboxBase {
+    constructor () {
+        super();
+
+        this.serverSync = new CookieSync();
```
Comment (miherlosev) [inline src/client/sandbox/cookie/index.js]:
```js
this.cookieSync = new CookieSync();
```

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
FPR

**Comment by miherlosev** [comment]
I run health monitor on this PR - https://testcafe-hhhm.devexpress.com/history?timestamp=1495709733539&siteUrl=http://www.about.com/
There is not a new issues.

**Comment by miherlosev** [comment]
ping @churkin

**Comment by churkin** [comment]
rebase required

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
ping @churkin

File: src/client/sandbox/cookie/cookie-sync.js [hunk 16]
```diff
@@ -0,0 +1,124 @@
...
+        this.useAsyncXhr = true;
+        this.queue       = [];
+        this.sendedQueue = null;
+        this.activeReq   = null;
+
+        // NOTE: When unloading, we should switch to synchronous XHR to be sure that we won't lose any cookies.
+        nativeMethods.windowAddEventListener.call(window, 'beforeunload', () => this._beforeUnloadHandler(), true);
+    }
+
+    static _createXMLHttpRequest (isAsync) {
```
Comment (churkin) [inline src/client/sandbox/cookie/cookie-sync.js]: https://github.com/DevExpress/testcafe-hammerhead/pull/1128/files#diff-70109a386093b74fcb03372cf3b1a05cR16
Are these two identical methods?

**Comment by LavrovArtem** [comment]
FPR
