### PR TITLE
fix `Code instrumentation of the 'lenght' property is very slow` (close #979)

### LINKED ISSUE #979: Code instrumentation of the 'lenght' property is very slow
See [video](http://screencast.com/t/9cFK4zvr0)

Url for reproduce - http://demos.devexpress.com/bootstrap/GridView/Editing.aspx

On video we see that cascading comboboxes close very slowly.

Profiling result:
Profing result

`IsShadowContainerCollection` affects about 38 percent of the time.

Need to speed up instrumentation of this property.

### PR DESCRIPTION
**Pull request by LavrovArtem**
Before:
image

After:
image

### CODE REVIEW

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

File: src/client/sandbox/shadow-ui.js [hunk 1]
```diff
@@ -116,6 +118,19 @@ export default class ShadowUI extends SandboxBase {
         };
     }
 
+    static _markElementCollections (el) {
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: `markShadowUIContainerCollections (containerElement)`

File: src/client/sandbox/shadow-ui.js [hunk 2]
```diff
@@ -116,6 +118,19 @@ export default class ShadowUI extends SandboxBase {
...
+        Object.defineProperty(el.children, IS_SHADOW_CONTAINER_COLLECTION_FLAG, {
+            configurable: false,
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: `false` is a default value.
You can write as `Object.defineProperty(el.children, IS_SHADOW_CONTAINER_COLLECTION_FLAG, { value: true })`

File: src/client/sandbox/shadow-ui.js [hunk 3]
```diff
@@ -406,28 +445,16 @@ export default class ShadowUI extends SandboxBase {
     }
 
     static isShadowContainer (el) {
-        if (domUtils.isDomElement(el))
-            return domUtils.isBodyElement(el) || domUtils.isHeadElement(el);
-
-        return false;
+        return domUtils.isBodyElement(el) || domUtils.isHeadElement(el);
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: You can also mark `body` and `head` elements in the same way.
It is more fast the current condition

File: src/client/sandbox/shadow-ui.js [hunk 4]
```diff
@@ -405,29 +438,21 @@ export default class ShadowUI extends SandboxBase {
...
 
-    static isShadowContainer (el) {
-        if (domUtils.isDomElement(el))
-            return domUtils.isBodyElement(el) || domUtils.isHeadElement(el);
-
-        return false;
-    }
-
-    static isShadowContainerCollection (collection) {
+    static _checkFlag (obj, flag) {
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: `hasFlag`

File: src/client/sandbox/shadow-ui.js [hunk 5]
```diff
@@ -293,6 +302,14 @@ export default class ShadowUI extends SandboxBase {
     attach (window) {
         super.attach(window, window.document);
 
+        var document = window.document;
+
+        if (document.head)
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: I guess we can create the separate function `_markShadowUIContainers (head, body)` and check element existence incide this.
```js
_markShadowUIContainers (head, body) {
     if (head)
          ShadowUI._markShadowUIContainerCollections(head);

     if (body)
         ShadowUI._markShadowUIContainerCollections(head);
}
```

File: src/client/sandbox/shadow-ui.js [hunk 6]
```diff
@@ -405,29 +438,21 @@ export default class ShadowUI extends SandboxBase {
...
-            /*eslint-disable no-empty */
         catch (e) {
+            return false;
         }
-        /*eslint-enable no-empty */
+    }
 
-        return false;
+    static isShadowContainer (el) {
+        return ShadowUI._checkFlag(el, IS_SHADOW_CONTAINER_FLAG);
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: This PR is a performace optimization.
Also, it would be good to measure 'Bottom-Up' time (see Google Chrome Dev Tools, panel - Performance) for web page described in issue

File: src/client/sandbox/shadow-ui.js [hunk 7]
```diff
@@ -116,6 +119,12 @@ export default class ShadowUI extends SandboxBase {
         };
     }
 
+    static _markShadowUIContainerCollections (containerEl) {
```
Comment (miherlosev) [inline src/client/sandbox/shadow-ui.js]: `_markShadowUIContainerAndCollections`

**Comment by LavrovArtem** [comment]
@testcafe-build-bot \retest

**Comment by miherlosev** [comment]
Note that `test/client/views/dir.ejs`, `test/client/views/task-report.ejs`, `test/client/views/test-page-template.ejs` are redurant - we uses functionality from `qunit-harness` module.

### Performance comparison

Before:
image

After:
image

**Comment by miherlosev** [comment]
ping @churkin

File: src/client/sandbox/shadow-ui.js [hunk 8]
```diff
@@ -293,6 +310,10 @@ export default class ShadowUI extends SandboxBase {
     attach (window) {
         super.attach(window, window.document);
 
+        var document = window.document;
+
+        ShadowUI._markShadowUIContainers(document.head, document.body);
```
Comment (churkin) [inline src/client/sandbox/shadow-ui.js]: `this.document`

File: src/client/sandbox/shadow-ui.js [hunk 9]
```diff
@@ -310,6 +331,8 @@ export default class ShadowUI extends SandboxBase {
         this.nodeMutation.on(this.nodeMutation.DOCUMENT_CLEANED_EVENT, e => {
             this._restoreUIStyleSheets(e.document.head, this.uiStyleSheetsHtmlBackup);
             this.uiStyleSheetsHtmlBackup = null;
+
+            ShadowUI._markShadowUIContainers(document.head, document.body);
```
Comment (churkin) [inline src/client/sandbox/shadow-ui.js]: `this.document`

File: src/client/sandbox/shadow-ui.js [hunk 10]
```diff
@@ -332,6 +355,9 @@ export default class ShadowUI extends SandboxBase {
             if (e.message.cmd === this.BODY_CONTENT_CHANGED_COMMAND)
                 this.onBodyElementMutation();
         });
+
+        this.nodeMutation.on(this.nodeMutation.BODY_CREATED_EVENT, ({ body }) =>
+            ShadowUI._markShadowUIContainers(document.head, body));
```
Comment (churkin) [inline src/client/sandbox/shadow-ui.js]: `this.document`

File: src/client/sandbox/shadow-ui.js [hunk 11]
```diff
@@ -347,6 +373,8 @@ export default class ShadowUI extends SandboxBase {
 
         if (!(isRootInDom && isRootLastChild && isRootInBody))
             this.nativeMethods.appendChild.call(this.document.body, this.root);
+
+        ShadowUI._markShadowUIContainers(document.head, document.body);
```
Comment (churkin) [inline src/client/sandbox/shadow-ui.js]: `this.document`

**Comment by LavrovArtem** [comment]
FPR
